### ISSUE TITLE
spawn does not install interior

### ISSUE THREAD

**Issue by ezramb** [NexiusTailer/Nex-AC#103]
Hi, I have a problem
when the player connects, the interior is not installed and appears falling, it only happens if I install nex-ac, if I remove it works fine.
the debug does not show me any error.
thanks

**Comment by NexiusTailer** [comment]
Hello, just don't set the interior for player before you actually spawn him, like:
```
SetPlayerInterior(playerid, 5);
SpawnPlayer(playerid);
```
or
```
SpawnPlayer(playerid);
SetPlayerInterior(playerid, 5);
```

Set the interior in OnPlayerSpawn instead.

**Comment by ezramb** [comment]
hello thanks for responding, 
change so that it is configured in onplayerspawn but still can not configure the interior, what will be the problem?

**Comment by NexiusTailer** [comment]
Ok, then show me the code that causes this problem. Try to identify specific lines of code that are really needed to reproduce the problem, so that such code can be added to bare script and so that the problem can be seen.

**Comment by ezramb** [comment]
Hello,
for example, when the player's account is loaded it is like that.

> SetPlayerScore(playerid, player[playerid][pNivel]);
GivePlayerMoney(playerid, player[playerid][pDinero]);
SetPlayerHealth(playerid, player[playerid][pVida]);
SetPlayerArmour(playerid,player[playerid][pChaleco]);
SetSpawnInfo(playerid, 0, player[playerid][pSkin], player[playerid][pPosx], player[playerid][pPosy], player[playerid][pPosz], player[playerid][pPosa], 0, 0, 0, 0, 0, 0);
TogglePlayerSpectating(playerid, 0);
FirstSpawn[playerid] = true;
SpawnPlayer(playerid);

OnPlayerSpawn
>if(FirstSpawn[playerid] == true)
	{
	    SetPlayerInterior(playerid, player[playerid][pInterior]);
	    SetPlayerVirtualWorld(playerid, player[playerid][pMundo]);
	    FirstSpawn[playerid] = false;
	}

I really do not see where the problem is

**Comment by ezramb** [comment]
Hello,
the error was mine, when using TogglePlayerSpectating (playerid, 0); and then use SpawnPlayer (playerid); , OnPlayerSpawn was called twice and generated the error.
thanks for everything
