### ISSUE TITLE
error code 6 with pickup in other worlds

### ISSUE THREAD

**Issue by ezramb** [NexiusTailer/Nex-AC#104]
Hi
an error occurs when entering a pickup that has been created in a world other than 0,
example: I create a pickup with the world -1 to appear in all worlds, debug shows error code 6.
example 2: I create a pickup only for world 4, debug shows error code 6.
example 3: I create a pickup in the world 0, debug does not show any error.

this happens with createpickup, AddStaticPickup and createdynamicpickup.
`[10:25:54] [Nex-AC debug] Pickupid: 14, dist: 1019.138244, dist set: 1019.303405, acSet[8]: -1, playerid: 0
[10:25:54] [Nex-AC] Actuacion de 0 ID. El codigo de motivo: 006 (1)`

thanks for all

**Comment by NexiusTailer** [comment]
I don't have such a problem and can't reproduce it.

**Comment by ezramb** [comment]
Hello,
I have repaired the problem by loading the pickup 1 second after OnFilterScriptInit is started,
maybe it will be helpful
tranks
