### ISSUE TITLE
False detection #039

### ISSUE THREAD

**Issue by NemanjaMAX** [NexiusTailer/Nex-AC#105]
Hello, I'm using [PawnPlus](https://github.com/IllidanS4/PawnPlus) and I have this native:
```
native p_SPD(playerid, dialogid, style, const caption[], ConstAmxString:info, const button1[], const button2[]) = ShowPlayerDialog;
```
**It kicks player when dialog responds with this code:**
```
[Nex-AC debug] AC dialog: -1, dialogid: 7, listitem: -1, playerid: 0
[Nex-AC] Suspicious player, ID 0. Reason code: 039
```
If i try this, i get runtime error 19:
```
native p_SPD(playerid, dialogid, style, const caption[], ConstAmxString:info, const button1[], const button2[]) = acc_ShowPlayerDialog;
```

**Comment by NexiusTailer** [comment]
You can hook your p_SPD function as well as it's done with default [ShowPlayerDialog](https://github.com/NexiusTailer/Nex-AC/blob/6cfd04bf3ff65f2cd735daa1190eca8f0a6bdbb1/src/v1.9.45/nex-ac.inc#L2198-L2216) function in the anticheat, but it doesn't support compatibility with this plugin by default, so I can't give any guarantee that this will work.
