### ISSUE TITLE
many cheat types aren't being detected...

### ISSUE THREAD

**Issue by Zorono** [NexiusTailer/Nex-AC#111]
hello dude,  so i am testing an new kind of cheat programs... none of this cheat's features is being detected...

Cheat reference(SA-Multihack by saturos): https://www.solidfiles.com/v/yRr7Zja2RM2V2

**Comment by NexiusTailer** [comment]
Anticheat detected all the cheats in this bundle that can be detected in any way. For example, such a cheat as "all cars have nitro" is only visual and doesn't send nitro component to the server.
Such cheats that can be detected, like "infinite ammo/no reload", "aim while driving" etc are successfully detected.

**Comment by Zorono** [comment]
really iamn't sure why did hose cheats get undetected in my view.... but anyway thanks
