### ISSUE TITLE
Сокращение при перехвате

### ISSUE THREAD

**Issue by ronixtey** [NexiusTailer/Nex-AC#112]
Предлагаю сокращение **_ALS_OnPlayerClickPlayerTD** переделать на **_ALS_OnPlayerClickPlayerTextDra**

Т.к если при перехвате если название функции превышает допустимую длину, то принято все  равно указывать оригинальное название, хоть и не до конца.

[Кортез писал про это на форуме](http://pro-pawn.ru/showthread.php?10611-%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%B2%D0%B0%D1%82-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9-%D1%87%D0%B0%D1%81%D1%82%D1%8C-2-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0-%D0%BF%D0%B8%D1%88%D0%B5%D0%BC-%D0%B0%D0%BD%D1%82%D0%B8%D1%87%D0%B8%D1%82-%D0%BD%D0%B0-HP)

**Comment by NexiusTailer** [comment]
Насколько я помню, я решал проблему с несовместимостью хуков, в которых названия длинных функций записаны не до конца, а именно таким образом:
```
#if defined _ALS_OnPlayerEnterRaceCheckpoin\
	|| defined _ALS_OnPlayerEnterRaceCP
	#undef OnPlayerEnterRaceCheckpoint
#else
	#define _ALS_OnPlayerEnterRaceCP
#endif
```
Что означает, что это будет поддерживать и "видеть" как хуки, в которых маркер хука с _ALS_ объявлен и как "_ALS_OnPlayerEnterRaceCheckpoin", и как "_ALS_OnPlayerEnterRaceCP". Хотя с другой стороны, если в каком-то ином хуке будет проверка лишь на наличие одного из двух вариантов, то проблемы также всё равно будут, так что скорее всего изменю сам дефайн по умолчанию на вышепредложенный, спасибо.

> [Кортез писал про это на форуме](http://pro-pawn.ru/showthread.php?10611-%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%B2%D0%B0%D1%82-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9-%D1%87%D0%B0%D1%81%D1%82%D1%8C-2-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0-%D0%BF%D0%B8%D1%88%D0%B5%D0%BC-%D0%B0%D0%BD%D1%82%D0%B8%D1%87%D0%B8%D1%82-%D0%BD%D0%B0-HP)

Не читал, к сожалению

**Comment by ronixtey** [comment]
_ALS_OnPlayerPickUpDynPickup 

нашел еще один

**Comment by NexiusTailer** [comment]
Да там их несколько и я уже все исправил, а вернее даже сделал двойные и тройные дефайны разных _ALS_ вариантов, чтобы было совместимо с любыми вариантами. Следующая версия просто немного задерживается из-за других изменений.
