### ISSUE TITLE
wrong weapon id's 

### ISSUE THREAD

**Issue by reus-github** [NexiusTailer/Nex-AC#113]
https://github.com/NexiusTailer/Nex-AC/blob/ea9c22aa9b0bc6fa0e49f701359492be033fcb78/src/v1.9.46/nex-ac.inc#L5484

23 <= weaponid <= 25, because weapon Silenced 9mm (ID: 23) can glitch.

**Comment by NexiusTailer** [comment]
Can you prove it by some +c video with this weapon?
