### ISSUE TITLE
Different behaviour between local and hosted server.

### ISSUE THREAD

**Issue by codakkk** [NexiusTailer/Nex-AC#116]
Hello, I am using Nex-AC for my gamemode because it's tested and works like a charm! (so thanks for this :D ) 
I am having different behaviours between local and hosted server.
While on local every hacks are detected, on hosted server, some hacks aren't detected properly.
Example: On local, if I give myself a weapon with sobeit, I get instantly kicked.
On hosted, otherwise, I get kicked only after shooting atleast one bullet with that weapon.
Do you have some advices?

**Comment by NexiusTailer** [comment]
I think it's better to share some specific cheats this occurs with. I haven't encountered such problems before so I will be able to test it with my own local & hosted server to check if some cheats can do such a magic. Anyway check your anticheat settings in scriptfiles (maybe some codes are disabled on your hosted server) and check OnCheatDetected if you made any changes in it before your problem arose.

**Comment by codakkk** [comment]
Thanks for your answer.
Actually, both hosted and local have the same file inside scriptfiles and I didn't "forwarded" (or atleast hooked/public) OnCheatDetected.
I just put the include and made it working alone.
Anyway, I provided an example of this happening (the weapons anticheat), but I can't really provide you any code, because, apart of #include <nex-ac>, nothing added.

**Comment by codakkk** [comment]
Could it be the fact that Hosted server is Linux and local one is Windows? Because on windows everything works good.

**Comment by NexiusTailer** [comment]
No, scarcely. I can suppose you're using jit plugin with full jit-optimization or something like YSI (which uses a lot of emit-stuff) so it can be the reason. But if not, I don't know how it's even possible.

**Comment by codakkk** [comment]
Yeah, I am actually using all of them. We got the same idea. What do you think?

**Comment by NexiusTailer** [comment]
Try to disable jit at first and check what will happen. If you won't see any changes, try to disable YSI and check it again.

**Comment by codakkk** [comment]
JIT isn't active now, but YSI is. The fact is, I can't really disable it, because my whole gamemode relies on y_hooks.

**Comment by Y-Less** [comment]
Someone just linked me to this, saying they had an issue with YSI.  But honestly there's no evidence here that YSI had anything to do with it - that's a massive unfounded jump.  Nor should JIT have anything to do with it, normal code that works without JIT will work with.

If you have evidence of a bug in YSI, please report it and I'll be happy to look at it, but don't just blame other people for no reason.

**Comment by NexiusTailer** [comment]
> If you have evidence of a bug in YSI, please report it and I'll be happy to look at it, but don't just blame other people for no reason.

Nobody blames anyone here for no reason at the moment. The only fact is that libraries which use emit are only more often (speaking directly, more often in 100% cases (although I still don’t blame anyone for anything)) are subject to strange behavior this kind.

> JIT isn't active now, but YSI is. The fact is, I can't really disable it, because my whole gamemode relies on y_hooks.

If I understand correctly, you said that there is nothing added apart of include and no code to show, but your whole gamemode uses y_hooks. So anyway try to give any weapon to a player on a really clear gamemode without any dependencies (especially without YSI, amx_assembly, etc that uses emit instruction) just for test and see if this time there will be any changes in the anticheat behavior on the local and hosting server.

**Comment by codakkk** [comment]
Just did another intense test: seems that there's this problem on Windows too.
To be honest, I noticed the fact that AntiCheatGetWeapon gives the right result when cheating.
I tryied cheating a deagle, and AntiCheatGetWeapon gave me id 24. It's so strange.

**Comment by NexiusTailer** [comment]
@codakkk Is there any new information on this issue?
