### ISSUE TITLE
warning 239

### ISSUE THREAD

**Issue by plakapenka** [NexiusTailer/Nex-AC#117]
warning 239: literal array/string passed to a non-const parameter

pls fix

**Comment by NexiusTailer** [comment]
`
#pragma warning disable 214
#pragma warning disable 239
`

**Comment by plakapenka** [comment]
ну я тоже первым делом так подумал. Но это как не правильно чтоль..

**Comment by NexiusTailer** [comment]
Неправильно было делать со стороны разработчиков нового компилятора введение этих варнингов включёнными по умолчанию. Таким образом они сломали совместимость со стандартным компилятором и стандартным инклудами. А если уже выбирать между их компилятором и стандартным, то здесь, по-моему, даже вопросов не стоит.
