### ISSUE TITLE
A question about RakNet

### ISSUE THREAD

**Issue by omcho420** [NexiusTailer/Nex-AC#118]
Did u ever think about "transferring" most of the callbacks to packets in (Pawn.)RakNet detection's should be faster?

**Comment by NexiusTailer** [comment]
No, it's never be faster. Anything but speed is an advantage. And in fact, its main pros that pawn.raknet events are calling before samp events (publics) and can be desynced or even synced with rewriting some data in that packet. This is really a reason to have anticheat based on pawn.raknet, and after v1.9.48 I'm just planning to release 2.0 version, which will use the capabilities of this plugin to the maximum and which is developing right now.

**Comment by omcho420** [comment]
That's good to know, thanks for the answer
