### ISSUE TITLE
AntiCheatGetVehicleID

### ISSUE THREAD

**Issue by plakapenka** [NexiusTailer/Nex-AC#119]
на каком этапе устанавливается этот ид?

просто заменил везде, при входе(OnPlayerStateChange) ид еще неизвестен видимо
```
if(AntiCheatGetVehicleID(playerid)>= medicsls[0] && AntiCheatGetVehicleID(playerid)<= medicsls[5])
		{
			if(GetPVarInt(playerid,"Fraction_Duty") && pData[playerid][pMember] == 22) { }
			else
			{
				SCM(playerid, COLOR_GRAD1, " Вы не медик!");
				RemovePlayerFromVehicle(playerid);
			}
		}
```

**Comment by NexiusTailer** [comment]
В OnPlayerUpdate. OnPlayerStateChange вызывается как раз между старым и новым состоянием (не посредственно сразу при смене), а паблик OnPlayerUpdate уже идёт только после этого с новым состоянием. Это касаемо вопроса.

Касаемо кода - в данном случае вообще не нужно использовать функции AntiCheatGet(*что угодно), поскольку они не предназначены для замены собой обычных. Они сделаны для очень исключительных случаев, и вот для каких:
1) Если нужно вывести при кике или ином наказании наиболее полную дебаг инфу античита (а именно через эти функции предоставить доступ к значениям его переменных, которые напрямую для других скриптов сделаны недоступными)
2) Если нужно при кике читера сохранить какие-то данные в статистику с полной уверенностью того, что в них не попадают только что начитерённые данные.

Т.е. это функции, которые призваны давать надёжную, но **не обязательно актуальную** информацию, и именно поэтому для обычной логики мода их использовать не нужно без крайней на то необходимости.

**Comment by plakapenka** [comment]
спасибо
