### ISSUE TITLE
pickups

### ISSUE THREAD

**Issue by vovak155** [NexiusTailer/Nex-AC#120]
После установки некса пропали пикапы. тупо пропали пикапы может проблема и в чем то другом но я их не трогал и последнее с чем это может быть связано - некс. Создавал вручную для теста вводил команду, но они даже не создаются ни на уровне мода ни в игре

**Comment by NexiusTailer** [comment]
Стримерские ли это пикапы или обычные? Если первое, попробуй обновить стример.
