### ISSUE TITLE
OnPlayerTakeDamage

### ISSUE THREAD

**Issue by plakapenka** [NexiusTailer/Nex-AC#121]
античит чекает вызывается ли OnPlayerTakeDamage?
просто видимо нет, в новом собейте антигм от пуль не подает признаков жизни никаких, ни сообщений ни киков

**Comment by NexiusTailer** [comment]
Античит чекает, убавляется ли фактически хп у игрока после выстрела в него.
О каком именно новом GM'е речь?

**Comment by plakapenka** [comment]
дико извиняюсь. на чистом серве работает.
