### ISSUE TITLE
как правильно телепортировать игрока в авто?

### ISSUE THREAD

**Issue by plakapenka** [NexiusTailer/Nex-AC#123]
типо чувак в машине, нужно его вместе с машиной тп.. 
я так понял что нужно только setvehiclepos, позиция самого игрока и put в машину сделает античит, да?
но иногда кикает. А если делаю put сам, то кикает всегда
`[Nex-AC debug] Dist: 1221.228515, dist set: 25000.000000, old pos diff: 0.000005, speed: 0, veh: 620`

что может быть?

**Comment by NexiusTailer** [comment]
А зачем вообще его тпхать отдельно высаживая из тачки, а потом в неё же сажать?
При телепорте машины игрок тпхается вместе с ней не высаживаясь вообще, и проблем при этом с античитом никаких нет.

**Comment by plakapenka** [comment]
а если при этом еще и LinkVehicleToInterior и SetVehicleVirtualWorld делается, игроку нужно же менять?

**Comment by plakapenka** [comment]
и типо пока они не поменялись, окажется что тачка и грок в разных мирах, и его выкинет, т.е. нужен put. Нет?

**Comment by NexiusTailer** [comment]
> и типо пока они не поменялись, окажется что тачка и грок в разных мирах, и его выкинет, т.е. нужен put. Нет?

Выкидывает вроде только при разных виртуальных мирах, но если тпхать тачку и ставить виртуальный мир и игроку и тачке вместе, то никто из тачки вылететь не успеет. Так что сажать заново при тп это в принципе какой-то странный костыль непонятно от чего, который уже не у первого человека вижу. Не надо так, в общем.

**Comment by plakapenka** [comment]
ну так а что следует из кода выше?
`[Nex-AC debug] Dist: 1221.228515, dist set: 25000.000000, old pos diff: 0.000005, speed: 0, veh: 620`

в чем проблема кика может быть?

**Comment by NexiusTailer** [comment]
По логам тачка видимо просто для античита на предыдущей позиции, но такое может быть как раз при высадке игрока из тачки, телепорта тачки игрока отдельно, а потом заново его посадки в тачку. Если уже тпхаешь нормально без этого саму тачку с игроков, то нужно как-то добиться воспроизведения этой проблемы на чистом моде, чтобы можно было проанализировать конкретный кусок кода, при котором это идёт.

**Comment by plakapenka** [comment]
Пон. Спасибо.
На чистом не получается. буду искать проблему :c

**Comment by dewere** [comment]
1. RemovePlayerFromVehicle(playerid)
2. SetVehiclePos(vehicleid, x, y, z)
3. SetPlayerPos(playerid, x, y, z)
4. PutPlayerInVehicle(playerid, vehicleid, seatid)
5. ???
6. PROFIT!!

**Comment by dewere** [comment]
UPD: только увидел дату исью :D

**Comment by NexiusTailer** [comment]
> 1. RemovePlayerFromVehicle(playerid)
> 2. SetVehiclePos(vehicleid, x, y, z)
> 3. SetPlayerPos(playerid, x, y, z)
> 4. PutPlayerInVehicle(playerid, vehicleid, seatid)
> 5. ???
> 6. PROFIT!!

1. SetVehiclePos(vehicleid, x, y, z);
2. PROFIT

Игрока не высаживает из тачки при телепорте тачки...

**Comment by dewere** [comment]
> 
> 
> > 1. RemovePlayerFromVehicle(playerid)
> > 2. SetVehiclePos(vehicleid, x, y, z)
> > 3. SetPlayerPos(playerid, x, y, z)
> > 4. PutPlayerInVehicle(playerid, vehicleid, seatid)
> > 5. ???
> > 6. PROFIT!!
> 
>     1. SetVehiclePos(vehicleid, x, y, z);
> 
>     2. PROFIT
> 
> 
> Игрока не высаживает из тачки при телепорте тачки...

RemovePlayerFromVehicle для чего я отписал?)

**Comment by NexiusTailer** [comment]
> > > 1. RemovePlayerFromVehicle(playerid)
> > > 2. SetVehiclePos(vehicleid, x, y, z)
> > > 3. SetPlayerPos(playerid, x, y, z)
> > > 4. PutPlayerInVehicle(playerid, vehicleid, seatid)
> > > 5. ???
> > > 6. PROFIT!!
> > 
> > 
> > ```
> > 1. SetVehiclePos(vehicleid, x, y, z);
> > 
> > 2. PROFIT
> > ```
> > 
> > 
> > Игрока не высаживает из тачки при телепорте тачки...
> 
> RemovePlayerFromVehicle для чего я отписал?)

Не знаю, в этом нет смысла.
