### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by patryk110200** [NexiusTailer/Nex-AC#124]
C:\pawno\include\nex-ac.inc(2035) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2035) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2035) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2056) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2056) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2056) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584 -- 2586) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2584 -- 2586) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656 -- 2658) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2656 -- 2658) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674) : warning 219: local variable "X" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674 -- 2676) : warning 219: local variable "Y" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(2674 -- 2676) : warning 219: local variable "Z" shadows a variable at a preceding level
C:\pawno\include\nex-ac.inc(7013) : warning 201: redefinition of constant/macro (symbol "OnVehicleSpawn")
Pawn compiler 3.2.3664	Copyright (c) 1997-2006, ITB CompuPhase

1 Error.
[Finished in 11.9s]

I take this error IN CLEAR GAMEMODE without custom new's,public's,stock's etc.

**Comment by patryk110200** [comment]
Ok, i got it. In uf.inc creator use in enum PlayersEnum Float:X ... :/

**Comment by NexiusTailer** [comment]
> Ok, i got it. In uf.inc creator use in enum PlayersEnum Float:X ... :/

Well then change it there. Anyway it's not my problem that someone spoils and occupies the namespace at the global variables level, which is why later when creating local ones with the same names, the problems point to the last code found.

**Comment by patryk110200** [comment]
If some one get the same problem just like me, i edit uf.inc.
Here is link: https://pastebin.com/yfD6mRra

**Comment by NexiusTailer** [comment]
Ok, but this time (when it's exactly solved) can I close this issue? The previous one was open for comments, despite the fact that I closed it ahead of time..

**Comment by patryk110200** [comment]
yes
