### ISSUE TITLE
Strange issue on id player ids

### ISSUE THREAD

**Issue by codakkk** [NexiusTailer/Nex-AC#125]
Hello, I am facing a strange bug where my players get kicked when punching or shooting with a weapon for #021 (Invisible Hack).
It happens to everyone except for id 0.

**Comment by NexiusTailer** [comment]
Is there any other information about the cases? (server logs, screens, some code maybe).

**Comment by codakkk** [comment]
No server logs (just the kick logs).
I didn't made any changes to Nex-AC. So it's just strange

**Comment by codakkk** [comment]
Okay, now disabling the Anti-Invisible hack, players get kicked for #002 (2 Anti-teleport hack (onfoot))

**Comment by NexiusTailer** [comment]
Players can't be kicked by the anticheat without any logs, especially if you have them ingame.

**Comment by codakkk** [comment]
Yep, I wrote "just the kick logs". Anyway, seems fixed after restarting the server a bunch of times. Dunno what happened, seriously lol
