### ISSUE TITLE
Error about 'AC_USE_PICKUP_WEAPONS' when compiling filterscripts

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#127]
nex-ac.inc(2090) : error 017: undefined symbol "AC_USE_PICKUP_WEAPONS"
This only happens with flterscripts

**Comment by NexiusTailer** [comment]
I've tested nex-ac connection to the filterscript with "#define FILTERSCRIPT" line before & with calling CreatePickup/CreateDynamicPickup from the filterscript's code and it seems it compiles without any problems. Can you provide the code which caused these errors?

**Comment by NexiusTailer** [comment]
I seem to have finally met this error somehow. I'm working on fixing it...

**Comment by NexiusTailer** [comment]
Will be fixed in 1.9.50, thanks.
