### ISSUE TITLE
SetPlayerPos bug (?)

### ISSUE THREAD

**Issue by codakkk** [NexiusTailer/Nex-AC#129]
Hello, I wrote a little helper function that is used to prevent players to fall off the world when there are a lot of streamer objects (it's just a freeze for specific ms).
The fact is, most of times this function is called, players are reported as teleport hacks.
Any advices?
This is the function:
`
stock Character_SetSafePosition(playerid, Float:x, Float:y, Float:z, interior = -1, world = -1)
{
	if(!Character_IsLogged(playerid))
		return 0;

	if(interior == -1)
		interior = GetPlayerInterior(playerid);

	if(world == -1)
		world = Character_GetVirtualWorld(playerid);

	Streamer_UpdateEx(playerid, x, y, z, world, interior);
	SetPlayerPos(playerid, x, y, z);
	SetPlayerInterior(playerid, interior);
	Character_SetVirtualWorld(playerid, world);
	Character_FreezeForTime(playerid, 2000);
	return 1;
}

**Comment by NexiusTailer** [comment]
Try to use Streamer_UpdateEx function with compensatedtime parameter (if this one is used, streamer will teleport & freeze player for n ms automaticly without your timers or anything else).

**Comment by NexiusTailer** [comment]
Yes, try that.

**Comment by codakkk** [comment]
Still happens. Could it be the fact that I have SetSpawnInfo before spawning the player (with TogglePlayerSpectating)?
Logs:

> [Nex-AC debug] Dist: 2336.666503, dist set: 25000.000000, speed: 0, pos x, y, z: 1702.290039, -1600.640014, 13.539099, old pos x, y, z: 0.000000, 0.000000, 0.500000

**Comment by NexiusTailer** [comment]
> Still happens. Could it be the fact that I have SetSpawnInfo before spawning the player (with TogglePlayerSpectating)?

Probably. Can you provide some code to be able to reproduce the problem?

**Comment by codakkk** [comment]
Seems that SetSpawnInfo isn't the problem.
Anyway, the code is the one I wrote on the start.

**Comment by codakkk** [comment]
Could it be the fact that TogglePlayerSpectating forces the respawn?

**Comment by NexiusTailer** [comment]
Maybe. Try to reproduce this problem with the code you have on a blank gamemode. If the problem still appears, reduce the code by removing non-important functions and see again if the problem persists. Finally you'll see exactly which functions could cause such behavior.

**Comment by codakkk** [comment]
Will make tests and will let you know soon.

**Comment by NexiusTailer** [comment]
Any information?

**Comment by codakkk** [comment]
No thing, seems TogglePlayerSpectating is causing this issue. Didn't manage to handle it

**Comment by NexiusTailer** [comment]
So I've tested your function on a blank gm with some changes to have no dependent code ([function after changes](https://pastebin.com/3eHh2C2b)) and no problems were found either I was near the teleport position or so far from it.

**Comment by codakkk** [comment]
That seems strange to me. What do you think about that?

**Comment by NexiusTailer** [comment]
> That seems strange to me. What do you think about that?

I think as we both have tested that on a base gamemode, there could be some differences in additional includes/plugin list so it would be great if you test this build without any changes to make sure that exactly the same code was used for tests:
[test.zip](https://github.com/NexiusTailer/Nex-AC/files/3752476/test.zip)
