### ISSUE TITLE
Sscanf

### ISSUE THREAD

**Issue by MaxAndolini** [NexiusTailer/Nex-AC#13]
https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.8/v1.8.7/nex-ac.inc

This code is bugged.

sscanf(ac_string, "i'//'i", ac_j, ac_i);

It gives error.

sscanf error: System not initialised.

I am using sscanf2 2.8.1

http://forum.sa-mp.com/showthread.php?t=570927

How can we solve it?

**Comment by NexiusTailer** [comment]
Are you sure that is sscanf connected correctly?
When I tried to do the same, everything worked well.
Check maybe you forgotten to specify sscanf in server.cfg as a plugin or put the .dll or .so files in 'plugins' directory.

**Comment by MaxAndolini** [comment]
Yes, I am sure.Delete this line, and I've tried. There is no mistake.

**Comment by MaxAndolini** [comment]
#include <sscanf2>
#include <nex-ac>

You will see that try.

**Comment by NexiusTailer** [comment]
Okay. Which sscanf version you use?
I tested it on v2.8.2

**Comment by MaxAndolini** [comment]
Me too. I'm using it.

**Comment by MaxAndolini** [comment]
#include YSI\y_hooks
#include scanf2
#include nex-ac

The problem is y_hook. therefore it gives an error.

**Comment by MaxAndolini** [comment]
I am solved.

#include scanf2
#include YSI\y_hooks
#include nex-ac

They are change locations. Solve the problem.
