### ISSUE TITLE
Vehicle health hacks AC 

### ISSUE THREAD

**Issue by u9h5r** [NexiusTailer/Nex-AC#131]
Hi,

There appears to be an issue of some sort with the vehicle health hack anti-cheat.

In the below logs (all different players), we see players whose vehicle health was supposedly increased to 300, which seemed like an odd increase:

09/10/2019 20:32:18 [Nex-AC debug] AC veh health: 239.703979, veh health: 300.000000, veh: 1837, playerid: 3
09/10/2019 20:41:46 [Nex-AC debug] AC veh health: 298.000000, veh health: 300.000000, veh: 145, playerid: 11
09/10/2019 21:29:11 [Nex-AC debug] AC veh health: 214.000000, veh health: 300.000000, veh: 66, playerid: 25
09/10/2019 21:46:34 [Nex-AC debug] AC veh health: 211.018676, veh health: 300.000000, veh: 243, playerid: 17

There's others who saw very strange increases, to very specific values:

09/10/2019 20:50:14 [Nex-AC debug] AC veh health: 73.319999, veh health: 73.739997, veh: 99, playerid: 2
09/10/2019 21:26:40 [Nex-AC debug] AC veh health: 767.000000, veh health: 892.235107, veh: 1831, playerid: 6
09/10/2019 21:34:23 [Nex-AC debug] AC veh health: 968.000000, veh health: 968.558776, veh: 1832, playerid: 4
09/10/2019 21:34:23 [Nex-AC debug] AC veh health: 968.000000, veh health: 968.152099, veh: 1832, playerid: 4
09/10/2019 21:39:56 [Nex-AC debug] AC veh health: 890.688171, veh health: 915.438171, veh: 324, playerid: 19

There have been ban appeals and in each case the users GTA:SA installs were completely standard with no hacks/mods.

Do you have any ideas about what might be going on here?

Thank you.

**Comment by NexiusTailer** [comment]
Just don't kick or ban players for this ac code and that's on. The default punishment for health hack in vehicle is setting the old valid health to this vehicle. There were some reasons to do this instead of kick so I recommend you to do the same.

Check [https://forum.sa-mp.com/showpost.php?p=4032970&postcount=980](this example) to see which anticheat codes perform resync actions by default.
