### ISSUE TITLE
Kicks me when player is getting weapons

### ISSUE THREAD

**Issue by Sanady** [NexiusTailer/Nex-AC#133]
Good evening,

I have small issue when player is spawning and getting weapons by script, he gets kicked, I am using modular system of coding. Is there any solution?

Thanks, Sanady

**Comment by NexiusTailer** [comment]
Hello, please provide more detailed information. I need the kick logs and minimal code to reproduce the issue.

**Comment by Sanady** [comment]
Well after I posted you here issue I noticed that I am using old version of your anti-cheat, but after updating inc and restart of my GM. I tried to spawn and it kicks me because of code 002 which is teleport hack, it made me thinking that the problem is in my script because I am first spawning player then moving to the specific location, and anticheat is detecting that as teleport hack, but still I don`t know how to fix it, I even tried to include anticheat into each of modules of my script but test failed.

Do you have any solution?

**Comment by NexiusTailer** [comment]
I have only one intention to ask you again for the ac logs and minimal code on which I could reproduce it.

**Comment by Sanady** [comment]
`[19:33:37] [Nex-AC debug] Dist: 1949.582763, dist set: 25000.000000, speed: 0, pos x, y, z: 414.585784, 2533.798828, 19.148399, old pos x, y, z: 1958.329956, 1343.119995, 15.859999
[19:33:37] {FFD900}[Anti-Cheat]{FFFFFF} Suspicion on the ID 0. Reason code: 002 (2)
[19:33:38] [part] Sanady has left the server (0:2)
`

Here is the log from console.

**Comment by Sanady** [comment]
And this is the piece of code which is causing this problem:
`hook OnPlayerSpawn(playerid)
{
    ShowPlayerGangZone(playerid);
	for(new i = 0; i < sizeof(GangZone); i++)
	{
		GangZoneShowForPlayer(playerid, i, GetTeamColor(GangZone[i][OwnerTeam]));

	    SetPlayerPos(playerid,GangZone[NextSpawn[playerid]][ZoneSpawnPos][0],GangZone[NextSpawn[playerid]][ZoneSpawnPos][1],GangZone[NextSpawn[playerid]][ZoneSpawnPos][2]);

        UpdateZoneTextLabel(i);
	}
	return 1;
}
`

**Comment by NexiusTailer** [comment]
Try to use ALS Hook Method 7 instead of y_hooks (just for test) and see if something will happen again.

**Comment by NexiusTailer** [comment]
Are there any shifts with this using als hooks?
