### ISSUE TITLE
Code 009 - heliblade

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#135]
On my server, we have teams, and if you're on the same team as another player, you can't damage them. 

I just noticed the issue shown in this video:

https://streamable.com/qo74w

15/01/2020 17:47:35 [Nex-AC debug] Speed: 195, old speed: 198, veh speed: 0
15/01/2020 17:47:35 [Nex-AC] ID 0 appears suspicious. Reason code: 009 (3)

Is there anything that can be done here?

**Comment by NexiusTailer** [comment]
Should be fixed in 1.9.50.
