### ISSUE TITLE
Code 002 - false detection

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#136]
**What happened?**

A few weeks ago it was bought to my attention of a false anti-cheat kick that can occur, which also just happened to me as shown in the below logs. I have SA:MP 0.3.7-R4 with no mods, and a low ping of ~100 with >150 FPS, so client lag can be ruled out completely here.

27/01/2020 17:47:52 [Nex-AC debug] Veh model: 579, dist: 1718.782592
27/01/2020 17:47:52 [Nex-AC] ID 11 appears suspicious. Reason code: 002 (4)
27/01/2020 17:47:52 [death] elvianod982 died 255
27/01/2020 17:47:52 OnPlayerDisconnect(11)
27/01/2020 17:47:52 [part] elvianod982 has left the server (11:2)

**How did it happen?**

I was driving a car (Huntley). I also had a passenger in my car. 

Two players on another team then came along on an NRG-500, and the passenger blew the Huntley up with a Desert Eagle. Due to the explosion, I immediately died whilst still sitting in the Huntley. I then got kicked by the anti-cheat as shown in the above logs.

**Other potentially helpful information:**
- This has occurred with both Nex-AC 1.9.49 and 1.9.50. I am not sure about previous versions, as I wasn't using it at the time.
- My server runs the latest release of weapon-config and SKY, on CentOS 7 64-bit. The server version is 0.3.7-R2.

**Comment by NexiusTailer** [comment]
Thanks for the report. Do you have some code which destroys/teleport the vehicle when its driver die or anything similar?

**Comment by elvianod982** [comment]
In the event a driver dies, vehicles do **not** get respawned, they stay in the same position.

Here is what my OnVehicleSpawn and OnVehicleDeath publics look like, though: https://pastebin.com/vdbdLQhf

If it would be beneficial I can send you more of the gamemode script in private.

**Comment by NexiusTailer** [comment]
Okay, maybe you have any custom death system? I see that the code 002 (4) checks player only if the previous state was driver and current state becomes onfoot (so seems that you've changed your state to onfoot, not to wasted).

**Comment by elvianod982** [comment]
Thanks for the quick reply.

We don't have a custom death system (only weapon-config).

Here is my OnPlayerDeath public if it means anything: https://pastebin.com/Ptzmf5Hs

**Comment by NexiusTailer** [comment]
If this problem occurs stably often, could you record a short video then?

**Comment by elvianod982** [comment]
I've managed to get a recording now :)

https://streamable.com/elh0d

07/02/2020 19:23:56 [Nex-AC debug] Veh model: 579, dist: 324.070007
07/02/2020 19:23:56 [Nex-AC] ID 20 appears suspicious. Reason code: 002 (4)
07/02/2020 19:23:56 [death] Rover died 255
07/02/2020 19:23:56 OnPlayerDisconnect(20)
07/02/2020 19:23:56 [part] Rover has left the server (20:2)

**Comment by NexiusTailer** [comment]
So it can be clearly seen that the vehicle destroys (or respawns) for some little time after its death and it can't stay at least 3-5 seconds after explosion. Guess somewhere you have a timer or something similar witch destroy/respawn the vehicle after death.

**Comment by elvianod982** [comment]
Thank you! I think it was the timer used when destroying vehicles that was responsible. This has now been re-written (and no longer uses a timer). I am hopeful it will solve the problem, and will close this case.
