### ISSUE TITLE
IsPlayerDying ??

### ISSUE THREAD

**Issue by Zorono** [NexiusTailer/Nex-AC#137]
is `weapon-config` a requirement to use `IsPlayerDying` or you're defining it from somewhere else ??

**Comment by NexiusTailer** [comment]
IsPlayerDying is the attribute by which I indirectly determine the presence of weapon-config to make it work properly with ac.

**Comment by Zorono** [comment]
it'd be great if you added support for `weapon-config`'s `OnPlayerTake/GiveDamage`'s alternatives...
```
\nex-ac.inc(modified line number) : error 021: symbol already defined: "OnPlayerTakeDamage"
\nex-ac.inc(modified line number) : error 021: symbol already defined: "OnPlayerGiveDamage"
```

**Comment by NexiusTailer** [comment]
> it'd be great if you added support for `weapon-config`'s `OnPlayerTake/GiveDamage`'s alternatives...
> 
> ```
> \nex-ac.inc(modified line number) : error 021: symbol already defined: "OnPlayerTakeDamage"
> \nex-ac.inc(modified line number) : error 021: symbol already defined: "OnPlayerGiveDamage"
> ```

There is no need for it as everything works ok. You should just include anticheat before weapon-config.
