### ISSUE TITLE
JetPack 

### ISSUE THREAD

**Issue by ynhhoJ** [NexiusTailer/Nex-AC#14]
Вышел новый чит с **JetPack**-ом, затестил у себя на сервере, на версий античита 1.9.13, не кикает.
На этом видео всё показано: https://www.youtube.com/watch?v=jNwANBUAKNo

**Comment by NexiusTailer** [comment]
Спасибо. У меня пока нет идей как это можно полностью исправить, но в ближайшее время подумаю над этим. Это, кажется, работает как очень тихий флайхак..

**Comment by NexiusTailer** [comment]
Пока всё, что удалось выяснить:
Данное клео полностью отключает синхронизацию специального действия 2 (jetpack), будь у игрока он выданный сервером либо получен читом. Таким образом с этим клео игрока кикнет за NOP SetPlayerSpecialAction, если выдать ему jetpack.
Это никак не решение проблемы, но сам факт)

Наилучшим было бы делать проверку с использованием ColAndreas/MapAndreas, но не рентабельно встраивать в античит такие громоздкие плагины, если нужны они будут только для этого, т.к. не всем могут позволить это ресурсы сервера.

Есть ещё идея сделать по принципу анти-флайхака в машине, который есть сейчас, но тогда вполне будет шанс видеть ложные срабатывания.

**Comment by NegativeIQ** [comment]
Ideya: Proveryat na animaciyu i velocity. Yesle Z velocity pozitivniy i animka stoyachego igroka (ne beguchego ili hodyachego) togda "fly" hack.

**Comment by NexiusTailer** [comment]
@NegativeIQ Дело в том, что анимация с таким читом теоретически может быть абсолютно любой, и, как я думаю, не составит никакого труда обойти такой фикс просто изменив анимацию в чите на случайную. Таким образом это будет максимум защищать только от данного чита данной версии, а реальную проблему это не решит.

**Comment by NegativeIQ** [comment]
Da kto tam budet fixit...Eto zhe nashi delali, a im tolko dlya Diamon RP i ostolnoy huyni chtobi rabotalo...

Zaley AC na to chto seychas tam yest, a yesle pofixyat nu i chort s nim...Eto zhe obicnih dve proverki...Integer i Float...Sovsem ne dorogo dlya servera, obichniye sistemi domov i ferm zanimayut v 10x bolshe resursov. Da i ne fakt chto vse budut polzovatsa samoy novoy verziyey, tak chto lovim kogo mozhem chtobi adminam menshe raboti bilo.

**Comment by NexiusTailer** [comment]
@NegativeIQ Если тебя устраивает такой вариант - создай форк и сделай для себя. Я не вижу смысла в том, обход чего известен заранее (тем более в античите с открытым исходным кодом).

С каждым днём лично для меня лишь утверждается мысль, что самым эффективным способом было бы узнавание высот карты и проверка расстояния игрока до них + некоторые нюансы, таким образом можно было бы улучшить обнаружение сразу и флайхака, и аира, и этого чита. Жаль на данный момент ради такого нужно подключать ресурсоёмкие плагины, что устроит скорее всего далеко не каждого.

**Comment by Heyter** [comment]
Античит мусор. Игра самп - мусор.
