### ISSUE TITLE
sobeit mod of ./dcar

### ISSUE THREAD

**Issue by Chiaooo** [NexiusTailer/Nex-AC#142]
the m0d fucntion ./dcar can destroy cars,but i don't know why it happens
could u help me with it? many thanks

**Comment by NexiusTailer** [comment]
First of all I need that hack to be able to check it by myself.

**Comment by Chiaooo** [comment]
https://github.com/BlastHackNet/mod_s0beit_sa-1
the s0beit address

**Comment by NexiusTailer** [comment]
I didn't find this command there
