### ISSUE TITLE
Support for const correctness

### ISSUE THREAD

**Issue by ADRFranklin** [NexiusTailer/Nex-AC#144]
A few people are having issues with this on the latest versions of the community compiler. Due to the warnings of having const correctness. 

This shouldn't be seen as a fix for just this compiler, but should be seen as a correct way to write code. I'll leave some links here so you can check what needs to be changed to meet these requirements.

Though you have no obligation to make these changes, I hope you would to provide additional support for the people who use the modern pawn compiler.

https://github.com/pawn-lang/compiler/wiki/Const-Correctness

**Comment by javelin5150** [comment]
Yeah, thanks Michael for fixing [this](https://github.com/NexiusTailer/Nex-AC/commit/869162ce3425dca76ae7702b135c440b0e4e0d4f), but the const correctness warns are a pain in the ass. I hope you fix them.

**Comment by NexiusTailer** [comment]
I still think that the new 'community' compiler just break backward compatibility with the default samp includes and compiler, because simply adding 'const' to all the necessary variables and solving warnings on the community compiler you'll expectedly create errors on the default. If there is such a behavior that breaks the logic of previous versions, you need to disable it by default (and those who really need it will easily enable it), or at least introduce it as gradually as possible, but the developers just ignored both ways and made the most short-sighted decision of possible, making the problem out of nothing for many people.

Moreover, even after any complaints about it after release of 3.10.9, the developers ignored it, although they could correct the situation with the new version 3.10.10. It is not very appropriate to cite as an argument the desire that everyone abruptly start writing code super correctly, at the same time destroying any backward compatibility and creating a bunch of warings that make a **real** problem, solving an **imaginary** one.

The third important thing which only confirms that these people who make such weird changes to the compiler absolutely didn't care about the consequences of their actions and changes, was that no means were provided for a simple solution to this situation. For example, in the community compiler there is -z compilation flag which is aimed precisely at keeping backward compatibility in any situations and with any code. But this doesn't work with const-correctness, no one was just going to even take this into account.

I don't share the opinion that these changes should be enabled by default at all and the fact that the compiler’s developers just ignore the consequences of the problem they created makes the reason that I still haven't made support for their strange willful changes in this include. So, you can well consider this as a principal decision.

**Comment by NexiusTailer** [comment]
And just in case someone comes in here looking for a solution, I still suggest you use the following:
```
#pragma warning disable 214
#pragma warning disable 239
```

**Comment by ADRFranklin** [comment]
Const correctness is not a pawn related thing, it applies to all languages. It's actually designed for performance/safety by telling the compiler that the variable being passed to the function shouldn't be modified after that.

This should of been default behavior from the very beginning and is a fault of the original compiler, this doesn't break anything at all. This just gives you warnings and it shouldn't be ignored like you have said in your reply.

const is a proper keyword that exists for a reason, and it should be used in programming. 

@NexiusTailer Please reconsider this, you should not ignore the keyword const, it is very important in programming.

**Comment by NexiusTailer** [comment]
This would work if kalcor updated the default includes in the server’s archive on the download page, but as long as there are regular samp includes without the word “const” in the natives of its functions, the community compiler only splits this community, forcing either to make workarounds for module developers (creating additional reasons to spend their time almost in vain, because they don't get real benefits from this) or force the other scripters to choose which compiler to use. As long as samp is the base, and the community compiler is just an add-on on this base, its developers should take into account backward compatibility and not neglect it, as they do now.

**Comment by dakyskye** [comment]
\> @NexiusTailer And just in case someone comes in here looking for a solution, I still suggest using the following:
```
#pragma warning disable 214
#pragma warning disable 239
```

Well, this will apply to the whole script, which I wouldn't like just for Nex-AC unless there is `#pragma warning enable` which I didn't know before that I could do:
```c
#pragma warning disable 214
#pragma warning disable 239
#include <nexac>
#pragma warning enable 214
#pragma warning enable 239
```
however, quite unsure if that gonna work.

**Comment by dakyskye** [comment]
`const` keyword should not break the compatibility, as long as you don't really reassign a value to it :>]

**Comment by ADRFranklin** [comment]
@NexiusTailer Look at how I did it in weapon-config, you can do it the same way, and keep it working for both compilers.

https://github.com/oscar-broman/samp-weapon-config/blob/07619c72212aa5cdd32eb71967a67c3e0db230c9/weapon-config.inc#L70

**Comment by Southclaws** [comment]
Canonical libraries: https://github.com/sampctl/samp-stdlib/

**Comment by dakyskye** [comment]
@ADRFranklin is that even a thing? How is the correct code not compiled by the old compiler?

**Comment by dakyskye** [comment]
Even the first release of compiler should have the `const` keyword, so it must not be a thing.

**Comment by ADRFranklin** [comment]
@dakyskye  someone complained about something related to it, so I made a compatibility define just to be sure.

**Comment by NexiusTailer** [comment]
@ADRFranklin I saw your way of fixing this (and imo currently this is the wisest solution), but again, I don’t like the fact that the developers of the new compiler are so aggressively promoting their changes. I tend to just turn them off in such case.
@Southclaws It is not the "Canonical" libraries, as really canonical are still here: http://files.sa-mp.com/samp037_svr_R2-1-1_win32.zip

@dakyskye Then try to compile it with the new compiler and default samp includes (while anticheat will have "const" in all places needed) - you just get the error or argument mismatch as the samp natives in default includes don't have const in its params, while anticheat will try to call them with it.

**Comment by dakyskye** [comment]
@NexiusTailer oh, fair enough.

**Comment by Southclaws** [comment]
Yes, unfortunately there's nothing we can do as Kye has severed all ties.

By canonical, I meant the libs that most of the active community members who use sampctl use. Those who I am in contact with and who are in the Discord.

Aside from that, like I said, nothing we can do. I understand the divide and I understand maintaining a correct copy and an old copy is not viable. All we can do is advise disabling the flag for old libraries.

**Comment by NexiusTailer** [comment]
@Southclaws As I said before, the current developers of zeex pawn compiler could do earlier and can do even now a lot of ways to solve this:
1. Just disable this by default - those who really need it will enable it and that's it.
2. Make -z flag working for reverting const-correctness and keeping compatibility again.
3. Make some defines like SAMP_CONST_CORRECT working for compiler too: if it is not enabled, do some actions that will exclude all necessary default samp natives and callbacks with "const" from the const-correctness checks.

As for those who use it: I still see crowds of people who use a default pawn compiler and as long as there are many users of both versions, there is no point in making such radical changes working by default in the community compiler.

**Comment by javelin5150** [comment]
> @Southclaws As I said before, the current developers of zeex pawn compiler could do earlier and can do even now a lot of ways to solve this:
> 
> 1. Just disable this by default - those who really need it will enable it and that's it.
> 2. Make -z flag working for reverting const-correctness and keeping compatibility again.
> 3. Make some defines like SAMP_CONST_CORRECT working for compiler too: if it is not enabled, do some actions that will exclude all necessary default samp natives and callbacks without "const" from the const-correctness checks.
> 
> As for those who use it: I still see crowds of people who use a default pawn compiler and as long as there are many users of both versions, there is no point in making such radical changes working by default in the community compiler.

I honestly get your point. Many users don't use the community compiler. I was talking to Michael, and I suggested making a new branch, nex-as with const correctness. Maybe that could be a thing in the near future? But yeah, I'll just use pragma for now.

**Comment by NexiusTailer** [comment]
@javelin5150 Actually it is not a really big problem technically, you can see a workaround added recently to weapon-config, for example. It's all about the ridiculous decisions made in the new versions of the community compiler and the fact that I personally do not want to support them. All the reasons for this I described above in detail.

**Comment by javelin5150** [comment]
> @javelin5150 Actually it is not a really big problem technically, you can see a workaround added recently to weapon-config, for example. It's all about the ridiculous decisions made in the new versions of the community compiler and the fact that I personally do not want to support them. All the reasons for this I described above in detail.
> 
> In the other hand, nothing stops you to make a fork and do with it what you want, adding all necessary checks for it or just make it only const-compatible without compatibility with the old pawn compiler - the only thing will be the same, I will stick to the default compiler logic until the maintainers of community compiler take a proper solution of the problem on their part that they themselves created.

Do you mind sending me a link of the commit or something?

**Comment by Southclaws** [comment]
Please voice the opinions in the compiler repo, it's actively maintained!

Complaining in other channels will not lead to improvement. I encourage you to leave your feedback and suggest improvements and make pull requests here: https://github.com/pawn-lang/compiler/

**Comment by NexiusTailer** [comment]
@Southclaws there is no point in it as I've shared this opinion much earlier, but it was ignored
@javelin5150 if you are about the commit that solves it in weapon-config, [here it is](https://github.com/oscar-broman/samp-weapon-config/blob/07619c72212aa5cdd32eb71967a67c3e0db230c9/weapon-config.inc#L70).

**Comment by javelin5150** [comment]
> @Southclaws there is no point in it as I've shared this opinion much earlier there, but it was ignored
> @javelin5150 if you are about the commit that solves it in weapon-config, [here it is](https://github.com/oscar-broman/samp-weapon-config/blob/07619c72212aa5cdd32eb71967a67c3e0db230c9/weapon-config.inc#L70).

I'm sorry that happened to you and thanks for the link, appreciate it!

**Comment by spacemud** [comment]
What are your arguments **specifically against const correctness**? I am confident the decision was made with users' best interests in mind; a cursory search finds very little evidence against using it. A wiki article [was also produced describing the advantages](https://github.com/pawn-lang/compiler/wiki/Const-Correctness).

I was happy to update my scripts to comply after reading the article and doing some research of my own. I am sure the users of this library would be happy to as well. This isn't a new problem: `fixes.inc` const corrected SA-MP natives and is in widespread use.

To dismiss an decision based on the objections to how it was implemented seems a little arbitrary and at odds to the good intentions of the original decision - to create correct code. Consider the SA-MP community - quite unlike many others in that it is smaller, more niche, and without the standards committees that might be expected from other better known programming languages. Mechanisms for debating decisions like this are less clear, but I do agree with @Southclaws  in that the community compiler repo is where the debate around this should take place. There is also a Discord server with many active community members that would happily discuss questions such as these - in which you'd be very welcome.

**Comment by NexiusTailer** [comment]
> What are your arguments **specifically against const correctness**?

> If there is such a behavior that breaks the logic of previous versions, you need to disable it by default (and those who really need it will easily enable it), or at least introduce it as gradually as possible, but the developers just ignored both ways and made the most short-sighted decision of possible, making the problem out of nothing for many people.

> It is not very appropriate to cite as an argument the desire that everyone abruptly start writing code super correctly, at the same time destroying any backward compatibility and creating a bunch of warings that make a real problem, solving (mostly) an imaginary one.

> The third important thing which only confirms that these people who make such weird changes to the compiler absolutely didn't care about the consequences of their actions and changes, was that no means were provided for a simple solution to this situation. For example, in the community compiler there is -z compilation flag which is aimed precisely at keeping backward compatibility in any situations and with any code. But this doesn't work with const-correctness, it seems no one was just going to even take this into account.

> As for those who use it: I still see crowds of people who use a default pawn compiler and as long as there are many users of both versions, there is no point in making such radical changes working by default in the community compiler.
