### ISSUE TITLE
HELP! Nex-AC kicks me.

### ISSUE THREAD

**Issue by geliar737** [NexiusTailer/Nex-AC#147]
Античит кикает меня с сервера, и в логах отображается: `[Nex-AC] Срабатывание на 0 ID. Код причины: 038` или `[16:47:23] [join] Geliar_Test has joined the server (ip)
[16:47:33] [part] Geliar_Test has left the server (0:0)`
Встречал много похожих ситуаций на форумах, но они не совсем такие как у меня. Помогите, очень прошу!

**Comment by NexiusTailer** [comment]
Что пишут логи со включенным "#define DEBUG" режимом?
