### ISSUE TITLE
False detection

### ISSUE THREAD

**Issue by aKnoxxSAMP** [NexiusTailer/Nex-AC#148]
[Nex-AC debug] AC dialog: -1, dialogid: 32700, listitem: -1, playerid: 0
[Nex-AC] Suspicion on the ID 0. Reason code: 039

Whenever a player logs into the server

**Comment by NexiusTailer** [comment]
Did you include the anticheat by the instruction? If you have any filterscripts, you must have "#define FILTERSCRIPT" in it and anticheat included.

**Comment by aKnoxxSAMP** [comment]
No filterscripts, I did change a few stuff because I was getting errors in my script because the parameters were different for onvehicledamage and onplayergivedamage, but I fixed it now and re-installed the .inc completely the exact same one in this github so hopefully it fixes everything.

I've been getting a lot of false detections too, a lot of different codes not just 1 :/ hopefully using the exact same .inc here will help. But Ive been getting other false detections too that shouldnt have anything to do with onplayergivedamage and onvehicledamage... we'll see though

**Comment by aKnoxxSAMP** [comment]
Thank you a lot :D
