### ISSUE TITLE
Kicked for Fly Hacking in Car while driving through a looping

### ISSUE THREAD

**Issue by Bios-Marcel** [NexiusTailer/Nex-AC#15]
Sometiems when you drive thru a looping, you get kicked because of fly hacking, i'd consider that a bug ;D

**Comment by NexiusTailer** [comment]
Try to send, for example, warning to admins (through OnCheatDetected) instead of kick by default

**Comment by Bios-Marcel** [comment]
That's what i'd call a "workaround" :D I think the Anti-Fly should just be a little more accurate.

**Comment by NexiusTailer** [comment]
There is no perfect way of detect flyhack in cars. Even now, with the acceleration before that, you can safely fly in transport, and if I make detection even less sensitive - it is quite possible that you could successfully start flying when you just standing in one spot
