### ISSUE TITLE
Arguments of Streamer_UpdateEx Warning Error

### ISSUE THREAD

**Issue by Ranneciva** [NexiusTailer/Nex-AC#150]
Why do I get this warning? I think that the arguments seems fine by the stock above.
Line: 1107 & 1109

stock ac_Streamer_UpdateEx(playerid, Float:x, Float:y, Float:z, worldid = -1, interiorid = -1, type = -1, compensatedtime = -1, freezeplayer = 1)
	{
		if(!Streamer_UpdateEx(playerid, x, y, z, worldid, interiorid, type, compensatedtime, freezeplayer)) return 0;

**Comment by Ranneciva** [comment]
\pawno\include\nex-ac-latest.inc(1109) : warning 202: number of arguments does not match definition

**Comment by NexiusTailer** [comment]
Because you have outdated streamer plugin
