### ISSUE TITLE
sobeit mod of ./dcar is work properly

### ISSUE THREAD

**Issue by Ranneciva** [NexiusTailer/Nex-AC#151]
My friend just test /.dcar

And its from BlastHack or whereever it is. I highly recommend to updates the nex-ac to blocks all /. command.
https://github.com/BlastHackNet/mod_s0beit_sa-1

**Comment by NexiusTailer** [comment]
There is no any "/.dcar" or similar commands

**Comment by Zorono** [comment]
it's Overlight version command
https://gitlab.com/RcKoid/mod-s0beit-overlight

**Comment by NexiusTailer** [comment]
What it does then?

**Comment by Ranneciva** [comment]
> What it does then?

/.dcar (vehicle id) and boom! the vehicle has away without any explodes ( i dont know why ) :(

**Comment by NexiusTailer** [comment]
Then use this as an additional check: https://github.com/urShadow/Pawn.RakNet/wiki/AntiVehicleSpawn
