### ISSUE TITLE
Improve Weapon AntiCheat

### ISSUE THREAD

**Issue by InterSstellar** [NexiusTailer/Nex-AC#158]
Hi, My Clients Kick Too Much For Reasons Like Weapon Hack Or infinite ammo Or ammo add Or NOPs that related to weapon and ammo But they are not cheating at all.

even sometimes the player kicked because the player ammo gets minus and the AC detects ammo add !!
I know you thought to that and add a check but it's happening.
i was able to fix that using this:
```
stock FAC_GivePlayerWeapon(playerid, weaponid, ammo)
{
	new WeaponID, WeaponSlot, WeaponAmmo, AC_WeaponAmmo;
	WeaponSlot = GetWeaponSlot(weaponid);
	GetPlayerWeaponData(playerid, WeaponSlot, WeaponID, WeaponAmmo);
	AntiCheatGetWeaponData(playerid, WeaponSlot, WeaponID, AC_WeaponAmmo);
	if (AC_WeaponAmmo + ammo > 20000 || WeaponAmmo + ammo > 20000) SetPlayerAmmo(playerid, weaponid, 20000);
	else acc_GivePlayerWeapon(playerid, weaponid, ammo);
	return 1;
}
#define GivePlayerWeapon FAC_GivePlayerWeapon
```
Sometimes When they enter a vehicle after shooting or when they buy guns at shop or when i give them weapon pack or.... they kick by AC

I Added Warnings to them and set they ammo to the amount that AC thinks they have but sometimes it happens and i really don't know what to do

For Example This Is The log when i gave someone a weapon pack:
```
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 28, ammo: 9999
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 31, ammo: 9999
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 34, ammo: 9999
```
And This Is My weapon pack command:
```
SetPlayerHealth(targetid, 100.0);
SetPlayerArmour(targetid, 100.0);
GivePlayerWeapon(targetid, 9, 9999);
GivePlayerWeapon(targetid, 24, 9999);
GivePlayerWeapon(targetid, 26, 9999);
GivePlayerWeapon(targetid, 28, 9999);
GivePlayerWeapon(targetid, 31, 9999);
GivePlayerWeapon(targetid, 34, 9999);
SetVehicleWeapon(targetid);
```

and this is `SetVehicleWeapon`:
```
stock SetVehicleWeapon(playerid)
{
	new weapon, ammo;
	GetPlayerWeaponData(playerid, 4, weapon, ammo);
	SetPlayerArmedWeapon(playerid, weapon);
}
```
Or AC Detects That someone is using NOP twice after he enters his vehicle after he gets a weapon pack.
log:
```
[22/05/2020 20:25:37] [Nex-AC debug] ID 3 Az NOP SetPlayerAmmo Estefade Kard
[22/05/2020 20:25:37] [Nex-AC debug] AC ammo: 19995, ammo: 19998, weaponid: 24
[22/05/2020 20:25:37] [Nex-AC debug] AC ammo: 9996, ammo: 19995, weaponid: 24
[22/05/2020 20:25:41] [Nex-AC debug] ID 3 Az NOP SetPlayerAmmo Estefade Kard
[22/05/2020 20:25:41] [Nex-AC debug] AC ammo: 9996, ammo: 19998, weaponid: 24
```
It's Very Good To Add Warnings Weapon anticheat (Code 15)

Note: My NOP warning is 8

I'm Using Weapon-Config And I Don't Think It's Causing it.

Please Help me =((

**Comment by NexiusTailer** [comment]
> It's Very Good To Add Warnings Weapon anticheat (Code 15)

They are already done in cases when we should wait for some time for applying of something to the player.

Currently I have no idea what's the reason of each case you provided, so just clarifying question: do you use the latest version of anticheat? v1.9.52 brought some corrections for some anti-weapon hack checks.

**Comment by InterSstellar** [comment]
I'm Using The Last Version Of AC

> Currently I have no idea what's the reason of each case you provided
I'm not good enough to provided some solutions to it but i can copy past some logs and ....

for example i don't know how this thing happened:
```
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 28, ammo: 9999
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 31, ammo: 9999
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 34, ammo: 9999
```

i can remember the player has no gun and when i gave him a package of guns the AC Detects Cheat.

One of the logs says that the player has weapon id 28 but the AC think he has no gun.

So how is this possible when i called `GivePlayerWeapon` And the AC accept that player is going to have weapon id 28 in his hand?

**Comment by NexiusTailer** [comment]
> So how is this possible when i called `GivePlayerWeapon` And the AC accept that player is going to have weapon id 28 in his hand?

There are only reasons for some inattentive actions like calling GivePlayerWeapon and other functions before including the anticheat, or using these functions from filterscripts in which anticheat is not included at all, so that it doesn't see the fact of weapons issuing.

**Comment by InterSstellar** [comment]
You are 100% right but this happened when i gave my client weapon pack using a command that is inside the gamemode and if you look at the log the player ammo is the same ammo that i gave him using command.

this is the command:
```
SetPlayerHealth(targetid, 100.0);
SetPlayerArmour(targetid, 100.0);
GivePlayerWeapon(targetid, 9, 9999);
GivePlayerWeapon(targetid, 24, 9999);
GivePlayerWeapon(targetid, 26, 9999);
GivePlayerWeapon(targetid, 28, 9999);
GivePlayerWeapon(targetid, 31, 9999);
GivePlayerWeapon(targetid, 34, 9999);
SetVehicleWeapon(targetid);
```
and this is the log:
```
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 28, ammo: 9999
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 31, ammo: 9999
[22/05/2020 20:20:37] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 34, ammo: 9999
```

The player get the same amount of ammo that i gave him from gamemode but it seems like the AC resets the player weapons vars somehow i think

And if you see the AC didn't detect cheat the first 3 weapons that i gave to the player **(ID: 9, 24, 26)** but detects the last 3 weapons as weapon hack !

If there was a gamemode problem or filterscript**(I dont have any filterscript that use weapon functions)** the AC should detect the first 3 weapons as cheat not just the last 3 weapons

Note: the second code of the kick reason was 2 that means the player didn't hold the gun in his hand and the first 3 weapons (ID 9, 24, 26) have a lower slot number than the others: that means when the ac loops through slots it must detect weapon id 9 cheat first not weapon id 28

Thank you very much for your support

**Comment by NexiusTailer** [comment]
> If there was a gamemode problem or filterscript**(I dont have any filterscript that use weapon functions)** the AC should detect the first 3 weapons as cheat not just the last 3 weapons

There are no reason why the ac should detect only last 3 weapons or only first 3 weapons. Although the loops for resetting weapons go in the opposite order (from a larger slot to a smaller one due to higher performance), if you had one of the problems I listed above, you would see detects of each of the given weapons (to all slots, and not just some of them).

**Comment by InterSstellar** [comment]
I test it multiple times and i found out that this happens when the player is dying or on spawn and i think `FreezeSyncPacket` Or `SendLastSyncPacket` is causing it i'm going to modify it a little bit and see if it happens again or not

**Comment by NexiusTailer** [comment]
So if you're still got FreezeSyncPacket in the anticheat then you still didn't disabled anti-unfreeze anti-cheat code which is disabled by default.

**Comment by NexiusTailer** [comment]
Is there any relevant information at the moment?
