### ISSUE TITLE
[1.9.49 -> 1.9.52] kicked for code 002

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#159]
Hi, 
Long time no talk (Thanks for all your work),
I updated from 1.9.49 to 1.9.52 and I started having people being kicked when they were being moved.
I have 2 main issues practically occurring (logs on the original issues), but it's the same issue I think:
 - Player being kicked on login (https://github.com/rt-2/SA-ARP/issues/67);
 - Player being kicked while passing doors (https://github.com/rt-2/SA-ARP/issues/66);

In the logs, it seems the player have been teleported to the correct (intended) location but the anti-cheat picks it up as cheat.
It is not happening all the time, only 1/3 or even less of the time.

Let me know how I can improve my testing.
We are trying to find how to 'reproduce' those bugs and when we will be able I will create a testing filterscript to test.
Thank you,
rt-2

**Comment by InterSstellar** [comment]
I Had This Problem Too And i didn't find the solution.
The code2 of your problem is 2. you have to store the code2 under `OnCheatWarning` and ignore the cheat under `OnCheatDetected` like this:
```
new P_code2[MAX_PLAYERS];
public OnCheatWarning(playerid, ip_address[], type, code, code2, count)
{
    P_code2[playerid] = code2;
}
public OnCheatDetected(playerid, ip_address[], type, code, code2)
{
    if (code == 2 || code2[playerid] == 2) return 1;
}
```

**It Will Fix It Temporary.**

**Comment by NexiusTailer** [comment]
> However i dont recommend this because of changing codes is nex-ac.inc but it works for me

And I don't recommend it too, first of all, because you don't solve the problem with this code at all, just ignoring it.

As for the first message, would be cool to see some visualization of it (short video/screen from the player before he gets this), proper description of his actions before the detection and what code performs at the moment to be better understand the problem and be able to reproduce this somehow.

**Comment by rt-2** [comment]
I will see what I can do.

**Comment by NexiusTailer** [comment]
So is there any new information about it?

**Comment by rt-2** [comment]
Yes the problem is still happenning ( added informations on the original issues. I will remove the [1.9.49 -> 1.9.52] because I cannot be completly sure that the version change caused this.
I will re-open the issue here if I am able to reproduce.
