### ISSUE TITLE
Недоработки

### ISSUE THREAD

**Issue by HarrWe** [NexiusTailer/Nex-AC#16]
Античит очень слабо ловит читера при изменение гравитации, т.е читер может изменять гравитацию и прыгать высоко.
А так же не кикает если бежишь с увеличенной скоростью игры. Но если прыгнешь 1 раз то сразу кикает.

**Comment by NexiusTailer** [comment]
Спасибо за отзывы.
1. Изменение гравитации довольно сложно отследить на стороне клиента, т.к. разве что как раз по высоте прыжков... Возможно, какие-то подобные проверки будут в будущем, не обещаю.
2. Сильно увеличенная скорость игры пресекается через античит на спидхак (потому, наверное, при прыжке и ловит сразу, т.к. увеличение скорости идёт гораздо сильнее). Тем не менее, при беге на слишком быстрых скоростях всё-же ловит и без прыжков.

**Comment by HarrWe** [comment]
И еще хотел спросить, почему в античите нет проверки на обновление античита? Что бы не мониторить каждый день GitHub... Или она есть, а я её не заметил?

**Comment by NexiusTailer** [comment]
На большинстве форумов у меня в подписи есть отдельный [инклуд](https://vk.com/doc175785824_438551862), который нужно подключить после любого из моих скриптов (он и проверяет их обновления).
