### ISSUE TITLE
Pro aim (code 29) when using sniper

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#160]
One of my player is being kicked by "pro aim".
I remember it happened with another player. I think the problem was client side. The new victim has downloaded the same version as me (98% sure) and it is still happening
My original issue is here but there is no information atm: https://github.com/rt-2/SA-ARP/issues/84
I think I remember finding the solution but I don't recall, does anyone have any idea?
It happens the second time the player shoots with his sniper aimed at a NPC from our tests.

Thank you

**Comment by InterSstellar** [comment]
it happens when shooting at same body part many times i think
because it happens to me too ( I Can Record a short video )

**Comment by rt-2** [comment]
@InterSstellar I think it has something to do with a corrupt sniper animation file. if you have the time, test with a new installation with another source for GTA SA. I remember it being a corrupted animation file on 1/3-1/4 source of torrented installation of GTA SA. The corrupted animation file for 1 weapon(the sniper) would result in a 0 frame aim or smth similar. The player would skip the aim animation I think but however I might be wrong because thats all memory from long ago, but it might help you test. That eould explain why on the same server it would happen to some player but for most not.
Thank you

**Comment by NexiusTailer** [comment]
I have steam version of the game (all files except gta_sa executable) and also wasn't face this issue.
