### ISSUE TITLE
Car parked in slopes, triggers vehicle hack after some time/distance

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#161]
A vehicle in a slope will be streamed for a player. After some time the server will consider it as hack (vehicle teleport) because the server doesnt stream the vehicle downhill but the client will.
Anybody found a practical solution on their servers for this?
Thank you

**Comment by NexiusTailer** [comment]
It always detects by anti-unoccupied vehicle teleport (code 005), so you just should ignore your custom punishment like kick or admin warnings for this code in OnCheatDetected, as anticheat will teleport this car to its previous position itself. This is a fact that client streams any vehicle if he see it  but he send OnUnoccupiedVehicleUpdate only if that vehicle is in radius of 90.0 units. Thus you get such things like desync unoccupied vehicle position and false detections of related anticheats as a result. There are no proper server-side solution so just don't kick players for this.
