### ISSUE TITLE
Vehicle loosing health inexplicably

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#162]
Original issue here: https://github.com/rt-2/SA-ARP/issues/113
Basically, the vehicle would be streamed at health 300 by someone in streaming distance, can only happen if the driver is AFK in my opinion.
I need information to be able to understand how I could test this.
 - What hacks could it possibly be ? ; 
 - What part of the anticheat should stop this ? ;

Thank you

**Comment by NexiusTailer** [comment]
There are only a couple of ways how a player can interact with vehicles, changing its health for all other players:
* Being directly on the **driver’s** seat of this vehicle (OnPlayerUpdate with PLAYER_STATE_DRIVER state)
* Via OnUnoccupiedVehicleUpdate (unoccupied sync, to be more precise).

And it's also important to note that the second method is not possible if the car is occupied by the driver (so the first way excludes the second).

Since in the original issue it's reported that the player controls a truck with a trailer, it is necessary to clarify which vehicle reduces its health (an occupied truck or a trailer).

**Comment by rt-2** [comment]
> There are only a couple of ways how a player can interact with vehicles, changing its health for all other players:
> 
> * Being directly on the **driver’s** seat of this vehicle (OnPlayerUpdate with PLAYER_STATE_DRIVER state)
> * Via OnUnoccupiedVehicleUpdate (unoccupied sync to be more precise)
> 
> And it's also important to note that the second method is not possible if the car is occupied by the driver (so the first way excludes the second).
> 
> Since in the original issue it's reported that the player controls a truck with a trailer, it is necessary to clarify which vehicle reduces its health (an occupied truck or a trailer).

That would exactly explain why this SEEMS to only work when the driver is AFK. When the driver is AFK, other ppl are able to use `OnUnoccupiedVehicleUpdate`, this is a problem if someone goes AFK while driving, someone can update the vehicle, when the driver comes back, is kicked for vehicle speed or vehicle TP.

Anyway I was rusty and now I remember OnUnoccupiedVehicleUpdate. I will do all my tests there thank you.

**Comment by NexiusTailer** [comment]
> That would exactly explain why this SEEMS to only work when the driver is AFK. When the driver is AFK, other ppl are able to use OnUnoccupiedVehicleUpdate, this is a problem if someone goes AFK while driving, someone can update the vehicle, when the driver comes back, is kicked for vehicle speed or vehicle TP.

When entering afk the player still continues to be the driver of this vehicle for other players. Perhaps this would be possible for those players who joined the stream of this car already having its driver afk (so and for them he will standing on the roof of this car on foot), but these single cases need to be checked for confirmation.

**Comment by NexiusTailer** [comment]
So is there any new information about that case?

**Comment by rt-2** [comment]
Did I read that you fixed my problem already? https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.53/Changelog.txt#L7

**Comment by NexiusTailer** [comment]
> Did I read that you fixed my problem already? https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.53/Changelog.txt#L7

Hm, yeah it's likely that this could help. However I wasn't sure that this is exactly what is used on your server and this particular solution could fix your problem (I made this check quite a while ago in relation to the release day).

**Comment by rt-2** [comment]
Do you have the commit where the change were made by any chance. Just curious and would look. If you dont remember its no trouble.
Thank you

**Comment by NexiusTailer** [comment]
As you can see I only make commits with new releases where all the latest changes are included at once, so I can only indicate where this was done by line: https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.53/nex-ac.inc#L8201

**Comment by rt-2** [comment]
```ac_uData[PR_vehicleHealth] != ac_uData[PR_vehicleHealth]```(https://github.com/NexiusTailer/Nex-AC/blob/32b869af7fb35c6d500e1bf474f5ebfd5102d2d4/src/v1.9.53/nex-ac.inc#L8201)
I think you are comparing a variable with itself?

**Comment by NexiusTailer** [comment]
> https://github.com/NexiusTailer/Nex-AC/blob/32b869af7fb35c6d500e1bf474f5ebfd5102d2d4/src/v1.9.53/nex-ac.inc#L8201
> 
> 
> I think you are comparing a variable with itself?

It's a NaN checks
