### ISSUE TITLE
foreach warning

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#163]
Hi,

On my server I use Nex-AC 1.9.52 and weapon-config.

I noticed that weapon-config is now making YSI [compulsory](https://github.com/oscar-broman/samp-weapon-config/commit/15338b02868a09bd9e89ec946aaefb8ed22dac10), and wish to update the include as such.

I tried removing `#include <foreach.inc>` from my gamemode, but the only thing that seems to be preventing compilation is Nex-AC:

> \pawno\include\nex-ac.inc(1191) : error 017: undefined symbol "foreach"
> \pawno\include\nex-ac.inc(1191) : error 029: invalid expression, assumed zero
> \pawno\include\nex-ac.inc(1191) : error 017: undefined symbol "ac_i"; did you mean "acIp"?
> \pawno\include\nex-ac.inc(1191) : fatal error 107: too many error messages on one line
> 
> Compilation aborted.
> 
> Pawn compiler 3.10.10	 	 	Copyright (c) 1997-2006, ITB CompuPhase
> 
> 
> 4 Errors.

I am not sure how to proceed here as such, and was hoping for some guidance.

Thanks.

**Comment by NexiusTailer** [comment]
I just tried to compile a blank gamemode with SKY/nex-ac/weapon-config included and there is no any error occured.
