### ISSUE TITLE
Isnt Detect Player With Speedhack Activate

### ISSUE THREAD

**Issue by AthallahDzaki** [NexiusTailer/Nex-AC#165]

**Comment by rt-2** [comment]
Are you able to provide a video of that, or any other information?

**Comment by AthallahDzaki** [comment]
Im sorry i dont have the vidio but its working with android sa-mp

**Comment by rt-2** [comment]
Are you able to reproduce the bug (what hack clients were used, and other conditions that needs to be met), so that the owner can test it to fix it?

**Comment by NexiusTailer** [comment]
I assume you're talking about smooth speedhack that doesn't produce sharp speed differences both between player updates and once per second. In this case there are no reliable solutions that will work without false detections for these cases.

**Comment by AthallahDzaki** [comment]
Okay Thanks for info
