### ISSUE TITLE
Player flying under the map

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#167]
I am using Nex-AC 1.9.53 and Pawn.RakNet 1.4.1, with all possible Nex-AC cheat codes enabled.

A player was flying under the map:

https://streamable.com/5e9kg5
https://streamable.com/2qaqza
https://streamable.com/uh373o

Is there any protection that can be added in this case?

**Comment by NexiusTailer** [comment]
It looks like pretty smooth coordmaster, so if it doesn't exceed anti-teleport distance limits or speed limits for anti-speed hack/air break, then unfortunately such player will go undetected. Another thing is that this player will not move far with such speed and imo cheats like that hardly poses a serious threat.

**Comment by rt-2** [comment]
Is there anything we can do with animations/player_state. It seems like most of those hacks that we cant detect uses an animation that is supposed to be temporary for a long amount of time.

**Comment by NexiusTailer** [comment]
Nothing can prevent the cheater to send any other animations that can be valid for constantly using. The real question is in surface detection and the distance of it from player, which cannot be done without something like cimulator or ColAndreas

**Comment by rt-2** [comment]
> Nothing can prevent the cheater to send any other animation that can be valid for constantly using. The real question is in surface detection and the distance of it from player, which cannot be done without something like cimulator or ColAndreas

I though about CalAndreas, but even that can't work because people can have custom maps....
