### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by HarrWe** [NexiusTailer/Nex-AC#17]
Код 49, если в лодке быстро садиться и вставать с водительского места.

**Comment by NexiusTailer** [comment]
Спасибо, постараюсь исправить.
В качестве временной меры можно увеличить значения в анти-флуде для пабликов [OnPlayerEnterVehicle](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9/v1.9.17/r2/nex-ac.inc#L204) и [OnPlayerStateChange](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9/v1.9.17/r2/nex-ac.inc#L209) (где первое значение это минимальная задержка между вызовами, а второе - максимальное количество этих вызовов при вызове чаще, чем с минимальную задержку)
