### ISSUE TITLE
Anti public flood is maybe broken

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#170]
I'm using OnFloodWarning and when connect and TogglePlayerSpectating(playerid, true); I receive flood warning code 11(OnPlayerStateChange). If I use ShowPlayerDialog after this I receive flood warning code 0(OnDialogResponse) and if I click in a player textdraw after this I receive flood warning code 23(OnPlayerClickPlayerTextDraw).

I don't understand, everything was working fine and now I just can't log into the server.

It is the same code: https://github.com/NexiusTailer/Nex-AC/issues/169#issuecomment-663861727

**Comment by Walter-Correa** [comment]
Tried EnableAntiCheat(49, 0); and solved, but now I receive kick by code 27(fake spawn)

**Comment by NexiusTailer** [comment]
Just don't relate your punishments to OnFloodWarning as it is not for punishment purpose and it's just a debug callback like On(Cheat/NOP)Warning.

**Comment by Walter-Correa** [comment]
But this is blocking me to click on player text draw. I don't know why, only when disable anti flood I can click.

**Comment by Walter-Correa** [comment]
FIXED: change GetTickCount to tickcount.

I would be very happy if you made this change to include as well. Thanks for everything!
