### ISSUE TITLE
Hacked position becoming current position

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#171]
Hello. I am testing to reset the player's position when he uses teleport hack. It's working, but if I insist on teleporting quickly, the hacked position becomes the current position.

At the sobeit I go to Teleport and select any option, if I press enter slowly everything works normal and the player returns to the old position, but if I press enter quickly several times the hacked position becomes the current position and does not reset to the old one .

```
forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
	switch(code)
	{
		case 2:
		{
                        new Float:acpos[3];
			AntiCheatGetPos(playerid, acpos[0], acpos[1], acpos[2]);
			SetPlayerPos(playerid, acpos[0], acpos[1], acpos[2]);
			SetPlayerInterior(playerid, AntiCheatGetInterior(playerid));
			SetCameraBehindPlayer(playerid);
		}
	}
	return 1;
}
```

**Comment by NexiusTailer** [comment]
Yeah, the cheat packet don't desync when you use any preventive actions in OnCheatDetected except kicking. So when the cheater abuse it doing it very fast, new sync data sometimes can update the ac position data. I think it is better to just kick such people, at least for now.
