### ISSUE TITLE
GetTickCount Should not be used in Windows

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#172]
Should have a constant to create compatibility with windows

**Comment by NexiusTailer** [comment]
Okey, I think I should test it if several people need this. But what about trying to suggest this to more general libraries like sa-mp-fixes, YSI or YSF? Such options could fix the problem on a larger scale there. I mean, a huge amount of filterscripts/includes besides nex-ac actively uses GetTickCount and it would be more reasonably to replace this "at a lower level" for all such scripts without changing them separately.

**Comment by Walter-Correa** [comment]
On windows it has to be tickcount (), in my case I use VPS and only the host company can restart the physical server, I can only restart my VPS and this does not solve the problem.

I have no problem using crtl + h and switching to tickcount () with each update of the include, but it would be interesting to have an adaptation for both types of users.

**Comment by rt-2** [comment]
> Okey, I think I should test it if several people need this. But what about trying to suggest this to more general libraries like sa-mp-fixes, YSI or YSF? Such options could fix the problem on a larger scale there. I mean, a huge amount of filterscripts/includes besides nex-ac actively uses GetTickCount and it would be more reasonably to replace this "at a lower level" for all such scripts without changing them separately.

In this case, we might wanna ditch the compatibility and just add `fixes.inc` as a requirement?

**Comment by NexiusTailer** [comment]
Yes, we could delegate the solution of such problem (which affects other scripts as well) to something like fixes.inc. But there is no point in adding it to the required "must have" dependencies here. It can be used by those people who really need it, including those who want to solve this problem.

**Comment by rt-2** [comment]
So we should mention the issue for windows users and propose the fix

**Comment by NexiusTailer** [comment]
Ok, will wait for any solutions done in fixes or other wide-purpose libraries/plugins.

**Comment by Walter-Correa** [comment]
The solution is simple, put a warning in the installation instruction: If your server is windows change GetTickCount () to tickcount ().

**Comment by NexiusTailer** [comment]
> The solution is simple, put a warning in the installation instruction: If your server is windows change GetTickCount () to tickcount ().

It's inconvenient to do it manually and the solution should be applied automatically. This is why we discussed the appearance of such a fix in fixes.inc or similar libraries that contain similar fixes.

**Comment by rt-2** [comment]
So this should end this? https://github.com/NexiusTailer/Nex-AC/pull/177
