### ISSUE TITLE
Anti-NOP SetPlayerAmmo bug

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#174]
Look, I think SetPlayerAmmo doesn't work well, I've tried using this function and it didn't work for me. I don't know if it's a bug from 3DL or all versions. It is accusing false positive NOP SetPlayerAmmo. Perhaps you should not use this function. I will disable Anti-NOP SetPlayerAmmo to avoid problems, after all I do not use SetPlayerAmmo on my GM.

**Comment by NexiusTailer** [comment]
Check this on a blank gamemode first, all relating SetPlayerAmmo works well. Also try to test it on 0.3.7 if you doubt about DL version.
