### ISSUE TITLE
OnCheatDetected called 2 times

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#175]
Could you fix the Teleport Hack double call on OnCheatDetected?

When the player teleports the OnCheatDetected callback it is called 2 times and this bypass anti NOPs SetPlayerPos and SetVehiclePos.

Not everyone, like me, wants to kick the player instantly. 
Mainly kicking for teleport hack that occurs a lot of false positives: My friend had very bad internet and was kicked by teleport, so I try to reset the player to the old position: https://github.com/NexiusTailer/Nex-AC/issues/171

If the server is unable to reset the position it is probably using NOP. 
I activated NOP SetPlayerPos and NOP SetVehiclePos and tried to teleport, but I was not kicked by NOP, so I identified that OnCheatDetected is called 2 times and for some reason does not detect the NOP. 

So I decided to reset the player's position only on the first call of the callback and boom ... NOP detected!

If you fix that I appreciate it very much!

**Comment by NexiusTailer** [comment]
> Mainly kicking for teleport hack that occurs a lot of false positives: My friend had very bad internet and was kicked by teleport, so I try to reset the player to the old position: #171

So you need to provide specific info about it to be able to fix all these cases

About the issue itself: each teleport attempt calls one OnCheatDetected, so if you got it twice, the cheater was trying to teleport 2 times.

**Comment by Walter-Correa** [comment]
No, just teleport once.

Remember this problem with GetTickCount ()? https://github.com/NexiusTailer/Nex-AC/issues/169

So, when that happened, the callback was called 2 times too and I wasn't even using a hack, it was the first time I was testing the include. As it was a problem with GetTickCount (), after I switched to tickcount it was solved, but before that, every time I spawned the callback was called 2 times and it is so far.


I recorded a video to show: https://youtu.be/FbEY-hdxCaQ

**Comment by NexiusTailer** [comment]
Ah, if you only experience this when the GetTickCount overflows on windows server which has not been restarted even for several weeks - the solution is the same as in the previous cases: switch to linux server (if you cannot manually restart it on windows) or wait for the corresponding fixes in libraries like fixes.inc

**Comment by Walter-Correa** [comment]
Wtf? The problem is not about GetTickCount anymore, is about the callback being called 2 times in a row.

**Comment by Walter-Correa** [comment]
I just quoted GetTickCount () to say that when the problem was him, the callback was also called twice in spawn, but I switched to tickcount () and everything was resolved.  I'm trying to say and show that ONLY teleport hack is being detected 2 times in a row.

**Comment by NexiusTailer** [comment]
Okay, seems I misunderstood you. So is there any logs about the case? Provide some more detailed info to be able to reproduce it

**Comment by Walter-Correa** [comment]
So ... in the printf debug he only makes one recording, but in the callback he calls 2 times in a row when teleporting.

I tested with several different sobeits. I suggest you use the code below and test with some teleport hack to see if the callback is also called twice for you.

```
forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
    new strtmp[sizeof KICK_MSG];
    format(strtmp, sizeof strtmp, KICK_MSG, code);
    SendClientMessage(playerid, -1, strtmp);
    return 1;
}
```

**Comment by NexiusTailer** [comment]
If it ever called twice for me or someone else who could report it for all these years, that issue would have fixed already. Just provide the anticheat logs (making sure you have enabled "#define DEBUG" and disabled "NO_SUSPICION_LOGS") which is printed on any cheat detection.

**Comment by Walter-Correa** [comment]
Yes. is defined DEBUG!

When I teleport I get 1 debug record:
```
[14:16:26] [Nex-AC debug] Dist: 83.488967, dist set: 25000.000000, speed: 0, pos x, y, z: -1831.004150, 1183.712402, 32.990921, old pos x, y, z: -1748.196777, 1190.720703, 24.976562
[14:16:26] [Nex-AC] Suspeita no ID 0. Código de motivo: 002 (2)
```
But OnPlayerCheat is called 2 times.

**Comment by NexiusTailer** [comment]
Then check it on a blank gamemode. I assume you probably calls OnCheatDetected somewhere from the script manually, so it can be a problem.

**Comment by Walter-Correa** [comment]
Ok.

I downloaded the samp server and compiled nex-ac in grandlarc gm: https://prnt.sc/trf0ux

I defined:
```
forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
    new strtmp[sizeof KICK_MSG];
    format(strtmp, sizeof strtmp, KICK_MSG, code);
    SendClientMessage(playerid, -1, strtmp);
    return 1;
}
```

I teleported 3 times only. The first time generated 1 printf debug(**[17:59:34]**) and called the callback 1 time only.
The second time I teleported it generated 2 printf debug(**[17:59:46]**) and called the callback 2 times.

The last time I teleported it generated 2 printf debug(**[18:08:28]**) and called the callback 2 times again.

```
[17:59:34] [Nex-AC debug] Dist: 45.548992, dist set: 25000.000000, speed: 0, pos x, y, z: 2810.226318, -1180.913208, 25.314952, old pos x, y, z: 2855.675537, -1177.956054, 24.736507
[17:59:34] [Nex-AC] Suspeita no ID 0. Código de motivo: 002 (2)

[17:59:46] [Nex-AC debug] Dist: 211.777435, dist set: 25000.000000, speed: 0, pos x, y, z: 2858.583740, -1396.831298, 45.214588, old pos x, y, z: 2838.396972, -1187.037963, 24.503921
[17:59:46] [Nex-AC] Suspeita no ID 0. Código de motivo: 002 (2)
[17:59:46] [Nex-AC debug] Dist: 210.766387, dist set: 225.700912, acSet[7]: -1, speed: 0, old pos x, y: 2838.396240, -1187.033935
[17:59:46] [Nex-AC] Suspeita no ID 0. Código de motivo: 002 (6)

[18:08:28] [Nex-AC debug] Dist: 298.681396, dist set: 25000.000000, speed: 1, pos x, y, z: 2897.864990, -1102.826171, 11.254853, old pos x, y, z: 2861.809082, -1397.372070, 45.214588
[18:08:28] [Nex-AC] Suspeita no ID 0. Código de motivo: 002 (2)
[18:08:28] [Nex-AC debug] Dist: 296.744537, dist set: 116.506744, acSet[7]: -1, speed: 0, old pos x, y: 2861.809082, -1397.372070
[18:08:28] [Nex-AC] Suspeita no ID 0. Código de motivo: 002 (6)
```

**Comment by NexiusTailer** [comment]
As you can see, you were detected by two different subcodes (002 (2) and 002 (6)).

**Comment by Walter-Correa** [comment]
In other words, what does that mean?

**Comment by NexiusTailer** [comment]
That you don't have OnCheatDetected called twice for the same reason, it's was different checks reported by two different subcodes.

**Comment by Walter-Correa** [comment]
Okay, I understand now. I just wanted to know why the callback is called 2 times for the same reason, but since it is about 2 different detections ...

I managed to solve the problem that did not detect NOP SetPlayerPos!

**I was doing it this way:**
```
forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
    if(type) BlockIpAddress(ip_address, 0);
    else
    {
        switch(code)
        {
			case 2:
			{
			    new Float:acpos[3];
   				AntiCheatGetPos(playerid, acpos[0], acpos[1], acpos[2]);
				SetPlayerPos(playerid, acpos[0], acpos[1], acpos[2]);
				SetPlayerInterior(playerid, AntiCheatGetInterior(playerid));
				SetCameraBehindPlayer(playerid);
			}
		}
    }
    return 1;
}
```
But in this way, as the callback is called 2 times, if I used NOP SetPlayerPos was not detected.

**I'm doing it now:**
```
forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
    if(type) BlockIpAddress(ip_address, 0);
    else
    {
        switch(code)
        {
			case 2:
			{
			    new Float:acpos[3];
				AntiCheatGetPos(playerid, acpos[0], acpos[1], acpos[2]);
				if(!IsPlayerInRangeOfPoint(playerid, 30.0, acpos[0], acpos[1], acpos[2]))
				{
					SetPlayerPos(playerid, acpos[0], acpos[1], acpos[2]);
					SetPlayerInterior(playerid, AntiCheatGetInterior(playerid));
					SetCameraBehindPlayer(playerid);
				}
			}
		}
    }
    return 1;
}
```

This solved the problem and if I use NOP SetPlayerPos I will be detected.

**This also solved another problem:** https://github.com/NexiusTailer/Nex-AC/issues/171
Now, if I try to teleport several times in a row, very quickly, I keep returning to the old position!

**Thank you very much for your attention.
Sorry for the inconvenience!**
