### ISSUE TITLE
Причина кика.

### ISSUE THREAD

**Issue by lJohhnyl** [NexiusTailer/Nex-AC#18]
Как-то давно видел сообщение на форуме где ты объяснял парню как изменить причину кика, тоесть было так: **Вы были кикнуты по причине #31**, но после что-бы было так: **Вы были кикнуты по причине Fly Hack (#31)** - ну или т.п. Как-же это сделать?
Надеюсь ты понял мою мысль...

**Comment by NexiusTailer** [comment]
<pre><code>new const CheatNames[][] =
{
	"Anti-AirBreak (onfoot)",
	"Anti-AirBreak (in vehicle)",
	"Anti-teleport hack (onfoot)",
	"Anti-teleport hack (in vehicle)",
	"Anti-teleport hack (into/between vehicles)",
	"Anti-teleport hack (vehicle to player)",
	"Anti-teleport hack (pickups)",
	"Anti-FlyHack (onfoot)",
	"Anti-FlyHack (in vehicle)",
	"Anti-SpeedHack (onfoot)",
	"Anti-SpeedHack (in vehicle)",
	"Anti-Health hack (in vehicle)",
	"Anti-Health hack (onfoot)",
	"Anti-Armour hack",
	"Anti-Money hack",
	"Anti-Weapon hack",
	"Anti-Ammo hack (add)",
	"Anti-Ammo hack (infinite)",
	"Anti-Special actions hack",
	"Anti-GodMode from bullets (onfoot)",
	"Anti-GodMode from bullets (in vehicle)",
	"Anti-Invisible hack",
	"Anti-lagcomp-spoof",
	"Anti-Tuning hack",
	"Anti-Parkour mod",
	"Anti-Quick turn",
	"Anti-Rapid fire",
	"Anti-FakeSpawn",
	"Anti-FakeKill",
	"Anti-Pro Aim",
	"",
	"",
	"",
	"",
	"",
	"",
};

forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
	if(type) BlockIpAddress(ip_address, 0); //Среагировал на IP (например за попытку брута ркона) - блочим его
	else //Среагировал на ID игрока
	{
		switch(code) //Какой чит?
		{
			case 5: return 1; //Телепорт незанятых авто (античит в любом случае вернёт её на прежнее место, наказание лучше не делать)
			case 11: //Починка транспорта, лучше вернуть ему старое хп (если не применит его - сработает уже анти-ноп)
			 {
				new vehid = GetPlayerVehicleID(playerid), Float:vhealth;
				AntiCheatGetVehicleHealth(vehid, vhealth);
				SetVehicleHealth(vehid, vhealth);
				return 1;
			}
			case 14: //Деньги
			{
				//Возвращаем старую сумму
				new a = AntiCheatGetMoney(playerid);
				ResetPlayerMoney(playerid);
				GivePlayerMoney(playerid, a);
				return 1; //Иное наказание также нам не нужно
			}
			case 32: return ClearAnimations(playerid, 1); //CarJack, выкидываем игрока из авто
			case 40: SendClientMessage(playerid, -1, MAX_CONNECTS_MSG); //Песочница (вход 2-х и более человек с одного IP), прощаемся
			case 41: SendClientMessage(playerid, -1, UNKNOWN_CLIENT_MSG); //Версия клиента игрока не определена, прощаемся с ним
			case 43..47: //Крашеры
			{
				Kick(playerid); //КРАЙНЕ рекомендуется кикать без задержки, иначе ОНО успеет крашнуть игроков
				return 1;
			}
			default: //Здесь все остальные читы
			{
				new strtmp[145];
				format(strtmp, sizeof strtmp, "Вы были кикнуты по причине %s (#%d)", CheatNames[code], code);
				SendClientMessage(playerid, -1, strtmp);
				return 1;
			}
		}
		new pPing = GetPlayerPing(playerid) + 150;
		SetTimerEx("ac_KickTimer", (pPing > 500 ? 500 : pPing), false, "i", playerid); //Кик за 40 и 41 код, ac_KickTimer есть в античите и успешно сработает
	}
	return 1;
}</code></pre>

**Comment by lJohhnyl** [comment]
Нет, это не то, тогда ты посоветовал ему удалить или поставить какой-то **define**

**Comment by NexiusTailer** [comment]
Возможно изменить текст в .lang файле в соответствующем дефайне ([пример](https://github.com/NexiusTailer/Nex-AC/blob/master/lang/nex-ac_ru.lang#L22)), но это вряд ли подойдёт, если ты объявляешь OnCheatDetected у себя в скрипте или хочешь добавить само название чита в ту строку (тогда нужно будет менять ещё и её форматирование в самом античите)

**Comment by lJohhnyl** [comment]
Да, первый метод лучше, протестил всё работает.
Спасибо.
