### ISSUE TITLE
Nex AC isn't detect Flying Car Hack

### ISSUE THREAD

**Issue by AthallahDzaki** [NexiusTailer/Nex-AC#181]
I Use sobeit at my server with NEX AC and press .(dot) and , (coma) then i fly my car, anti cheat isn't detect it.

**Comment by NexiusTailer** [comment]
Anticheat detects flyhack in vehicle only in cases of vertical climb (when vehicle flies up like a helicopter). Other cases would give false detections for stunting and things like that.
