### ISSUE TITLE
False kick (code 002)

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#182]
A player of mine was killed by someone with rapidfire. They out of their vehicle, and then they got kicked:

https://streamable.com/nz8eky

03/09/2020 10:44:05 [Nex-AC debug] Veh model: 496, veh: 243, dist: 412.358398
03/09/2020 10:44:05 [Nex-AC] ID 1 appears suspicious. Reason code: 002 (4)
03/09/2020 10:44:05 OnPlayerDisconnect(1)
03/09/2020 10:44:05 [part] _MaD_DoG_ has left the server (1:2)

This was of course a false kick.

Note: You can see the player's FPS and Ping in the bottom right hand corner.

**Comment by NexiusTailer** [comment]
I noticed that when the player leaving the car, it disappeared right before the player's kick. This could be a potential cause, so it would be great to provide some code that handles this behavior of vehicles on the server to test it and reproduce the problem.

**Comment by elvianod982** [comment]
> I noticed that when the player leaving the car, it disappeared right before the player's kick

This is being caused by [SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5449)

I am considering just removing this code from weapon-config, on the basis I cannot see a need for it as just below, you'll see [TogglePlayerSpectating(playerid, true);](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5451) and [TogglePlayerSpectating(playerid, false);](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5452) which achieves the same result.

**Comment by rt-2** [comment]
> > I noticed that when the player leaving the car, it disappeared right before the player's kick
> 
> This is being caused by [SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5449)
> 
> I am considering just removing this code from weapon-config, on the basis I cannot see a need for it as just below, you'll see [TogglePlayerSpectating(playerid, true);](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5451) and [TogglePlayerSpectating(playerid, false);](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5452) which achieves the same result.

Placing the player in another world achieve another purpose than disabling its ability to move.

Another thing, I personally use Nex-Ac with weapon-config.inc and I did not have to change what you said (I had to change 1-2 other thing).
