### ISSUE TITLE
Player driving vehicles with engine off (question)

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#183]
This is something I started to see lately only.
Players move the vehicle just like it would have engine on, but it doesn't.
Maybe your anti-cheat is already checking this, if so what is the offense/suboffense.
Thank you,

**Comment by NexiusTailer** [comment]
Sorry for missclicking and closing the issue.

At the moment there is no such anticheat code that would prevent driving with the engine off. But the solution can be based on the already existing anti-carshot code from the passenger seat, where the car is checked for acceleration and increasing movement without a driver in OnUnoccupiedVehicleUpdate.

**Comment by rt-2** [comment]
> Sorry for missclicking and closing the issue.
> 
> At the moment there is no such anticheat code that would prevent driving with the engine off. But the solution can be based on the already existing anti-carshot code from the passenger seat, where the car is checked for acceleration and increasing movement without a driver in OnUnoccupiedVehicleUpdate.

Yes I think that would be perfect to check for acceleration (especially if Z is not decreasing) for drivers if the vehicle engine is off.

It may be a new hack because I have never seen that in like 10 years but recently it happens more and more.

I think it would be very beneficial to add this check because it has become very prevalent for me in the last weeks.

Thank you,

**Comment by NexiusTailer** [comment]
> It may be a new hack because I have never seen that in like 10 years but recently it happens more and more.

Honestly I knew about this even before the first releases of the ac, but I deliberately didn't include anticheats with a narrow range of suitability, i.e. those that are relevant only on specific server genres, like anti-driving with disabled engine which relevant for RP servers only, anti-cleo drift that relevant only for drift servers and so on.

**Comment by rt-2** [comment]
So I should do my own script for that or is it gonna be implemented?

Thank you

**Comment by NexiusTailer** [comment]
I'm planning to add this in the next global version 2.0 along with some other protections, but there is a completely different code base there even for now and it will not be compatible with the config files of v1.*.*, so at the moment, while updates comes to the current anticheat, new anticheat codes are unlikely to appear.

**Comment by rt-2** [comment]
Thanks
