### ISSUE TITLE
-

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#184]

**Comment by NexiusTailer** [comment]
>> I noticed that when the player leaving the car, it disappeared right before the player's kick

> This is being caused by SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);

Yeah, you've already mentioned it there

**Comment by elvianod982** [comment]
So, do you have any suggestions?

**Comment by NexiusTailer** [comment]
No as I couldn't reproduce that
