### ISSUE TITLE
so much errors

### ISSUE THREAD

**Issue by anton3312578859** [NexiusTailer/Nex-AC#187]
pawno\include\nex-ac.inc(2079) : warning 202: number of arguments does not match definition
pawno\include\nex-ac.inc(2077) : warning 203: symbol is never used: "addsiren"
pawno\include\nex-ac.inc(2206) : error 017: undefined symbol "STREAMER_PICKUP_SD"
pawno\include\nex-ac.inc(2238) : error 017: undefined symbol "STREAMER_PICKUP_SD"
pawno\include\nex-ac.inc(2877) : warning 219: local variable "doors" shadows a variable at a preceding level
pawno\include\nex-ac.inc(2877) : warning 219: local variable "lights" shadows a variable at a preceding level
pawno\include\nex-ac.inc(2879) : warning 219: local variable "doors" shadows a variable at a preceding level
pawno\include\nex-ac.inc(2879) : warning 219: local variable "lights" shadows a variable at a preceding level
pawno\include\nex-ac.inc(3873) : warning 202: number of arguments does not match definition
pawno\include\nex-ac.inc(3890) : error 025: function heading differs from prototype
pawno\include\nex-ac.inc(3969) : warning 202: number of arguments does not match definition
pawno\include\nex-ac.inc(3986) : error 025: function heading differs from prototype

**Comment by NexiusTailer** [comment]
What version of Streamer Plugin and nex-ac you use? Update both to the latest if needed. Check and update the sa-mp default includes' version as well.

As for this:
```
pawno\include\nex-ac.inc(2877) : warning 219: local variable "doors" shadows a variable at a preceding level
pawno\include\nex-ac.inc(2877) : warning 219: local variable "lights" shadows a variable at a preceding level
pawno\include\nex-ac.inc(2879) : warning 219: local variable "doors" shadows a variable at a preceding level
pawno\include\nex-ac.inc(2879) : warning 219: local variable "lights" shadows a variable at a preceding level
```
You have badly named variables somewhere in the global scope. Such global variables should not have so simple and commonplace names, otherwise they will coincide with the names of local variables as in this case.
