### ISSUE TITLE
fixed plesae

### ISSUE THREAD

**Issue by Belarus64** [NexiusTailer/Nex-AC#188]
These types of tricks work, can you fix it please?

sobeit link: https://dosya.co/ylycp3m5djoh/LiquidMod_5.0.rar.html

ss : https://hizliresim.com/gFn4CN

ss : https://hizliresim.com/ITXYqC

airbreak needs to be improved

**Comment by NexiusTailer** [comment]
As for the second screen with "Mega Jump On Foot", there were some checks in anti-speedhack onfoot which detected it before, but now the maximum onfoot speed limits have been increased for the sake of stability for fair players.
And as for the first screenshot, I need a specific description of the cheat or what is happening in the pic.

> airbreak needs to be improved

How exactly?

**Comment by Belarus64** [comment]
+
Sobeiti I gave you the controls you can provide. In addition, the anti cheat is very robust update your update needs to be increased


https://www.youtube.com/watch?v=B2HlkJ3yNvQ
So what is the thing in the video and how to block it?

**Comment by NexiusTailer** [comment]
> How to fix it with Jump nex-ac?

You can decrease the onfoot speed limit, thereby you get mega jump detection, but at the same time frequent false detections when players falling from a height with low fps or some similar things.

> Sobeiti I gave you the controls you can provide. In addition, the anti cheat is very robust update your update needs to be increased

I don't really understand what you are talking about here

> https://www.youtube.com/watch?v=B2HlkJ3yNvQ
So what is the thing in the video and how to block it?

Basically Sandboxie-like software. You can prevent this by blocking the connection of several players from one IP address.

**Comment by Belarus64** [comment]
> You can decrease the onfoot speed limit, thereby you get mega jump detection, but at the same time frequent false detections when players falling from a height with low fps or some similar things.

can you tell me how to do this

**Comment by NexiusTailer** [comment]
> > You can decrease the onfoot speed limit, thereby you get mega jump detection, but at the same time frequent false detections when players falling from a height with low fps or some similar things.
> 
> can you tell me how to do this

Change [this line]([url](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.53/nex-ac.inc#L118)) to appropriate value

**Comment by Belarus64** [comment]
i couldn't

**Comment by NexiusTailer** [comment]
> i couldn't

Why?
