### ISSUE TITLE
Random questions

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#189]
Sorry for posting this here...with Kalcor's stupid decision to close the forum I wasn't sure where else to go.

1) Do you plan to add MapFix as a repo on Github? It's a good project and now seems "lost" thanks to the forum closing.

2) With the above in mind, is there a plan to continue development of SAMP includes like Nex-AC? Can we expect a Nex-AC 1.9.54 or 2.00?

3) You may wish to remove the sa-mp.com links on this repo. At https://github.com/NexiusTailer/Nex-AC for example there is a link to the SAMP forum.

**Comment by NexiusTailer** [comment]
As for the first question, check this out: https://github.com/sampctl/mapfix
It is hosted by sampctl repo and if there is any point in adding mapfix repository under my authorship, it would rather be easier to give me an existing repository, which I'm currently updating via pull requests.

> With the above in mind, is there a plan to continue development of SAMP includes like Nex-AC? Can we expect a Nex-AC 1.9.54 or 2.00?

Yes, I'm plan to update this anticheat to 1.9.54 and then fully devote time to developing 2.0 version from scratch, which is now early WIP

> You may wish to remove the sa-mp.com links on this repo. At https://github.com/NexiusTailer/Nex-AC for example there is a link to the SAMP forum.

Thanks for suggestion, I'll can update it to the existing russian forum topics or leave without links (will be considered later)
