### ISSUE TITLE
error 025: function heading differs from prototype

### ISSUE THREAD

**Issue by anton3312578859** [NexiusTailer/Nex-AC#191]
#if defined _ALS_OnPlayerTakeDamage
	#undef OnPlayerTakeDamage
#else
	#define _ALS_OnPlayerTakeDamage
#endif
#define OnPlayerTakeDamage ac_OnPlayerTakeDamage
#if defined ac_OnPlayerTakeDamage
	#if defined OnPlayerWeaponShot
		forward ac_OnPlayerTakeDamage(playerid, issuerid, Float:amount, weaponid, bodypart); // 3890
	#else
		forward ac_OnPlayerTakeDamage(playerid, issuerid, Float:amount, weaponid);
	#endif
#endif

**Comment by NexiusTailer** [comment]
Update your default samp includes and check if OnPlayerTakeDamage in **your** gamemode doesn't have all the necessary parameters.
