### ISSUE TITLE
CarFuncs script

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#194]
https://www.blast.hk/threads/23452/

/cf.fire works. I don't know the values, can you fix it?

**Comment by nex693** [comment]
works when not in the vehicle

**Comment by NexiusTailer** [comment]
First of all ensure you have the latest anticheat version and [Pawn.RakNet](https://github.com/katursis/Pawn.RakNet) plugin included to be able to have additional checks for the ac based on it. The second you check wether it is visible only for your game client or it is also visible for other player too. I can guess it can work just for you only as a visual effect.

**Comment by nex693** [comment]
anyone can see it. I am using the latest version of Pawn.Raknet fully active latest version of nex-ac but the trick works

Can you fix this?

I love you OstGot

**Comment by nex693** [comment]
detects that you are away. But besides this he doesn't understand when

**Comment by NexiusTailer** [comment]
I don't fully understand what you're trying to say in the last message, but if the cheat works only from a short distance and starts detecting when the cheater is further from vehicle (probably by anti-teleport into/between vehicles?), then this is the protection. The cheater cannot do this too quickly (since he must also wait for a while after sending the enter into a car for each teleporting).

**Comment by nex693** [comment]
The cheat works when you are near and not in the vehicle, can we fix it ?

**Comment by nex693** [comment]
cf.lag

**Comment by nex693** [comment]
unimpeded tricks

cf.lag
cf.fire
can you avoid these cheats

**Comment by NexiusTailer** [comment]
Can you first give an intelligible answer to this?

> but if the cheat works only from a short distance and starts detecting when the cheater is further from vehicle (probably by anti-teleport into/between vehicles?), then this is the protection. The cheater cannot do this too quickly, since he must also wait for a while after sending enter into a car for each teleporting.

In particular: are the players detected for these hacks when they are a little further from the vehicle, what codes are they detecting?

And if that code which they are detected for is 004 (anti-teleport into/between vehicles), then there is no better option in the ac for now than the one available, which does not allow cheats to work at least from that distance, on which the player is from the car when it starting to detect him.

**Comment by nex693** [comment]
We did not test it while in the car, but try it when not in the car and close to the car. Yes, it detects code 004 when you are away from the car, it just needs to be improved. Can you download and test the cheat?

and there is another non-fixi command in the trick. /cf.lag does not detect anti-cheating and cars appear in everyone.
I think it should be reviewed.

Thank You.

**Comment by NexiusTailer** [comment]
Okay, I will check each of the noticed commands from this lua script, but I'm pretty sure that the current fix for the distance is all that can save you from this and we can hardly do anything else with it.

**Comment by nex693** [comment]
I am confident in your experience. But I ask you to fix it quickly, they use it on my server every day.

you are a very good person and cod. Thanks, you are loved <3

**Comment by nex693** [comment]
ostgot hi again, I am afraid to consult you on cheating, but I have to.

You know I am using the fully active and updated version of Nex-ac.

The trick is: a different car crashes into my car very slowly, but my car is flying and I'm not kicking me in "Speed ​​Hack". What kind of trick is this cheat? @

**Comment by NexiusTailer** [comment]
> The trick is this: a different car crashes into my car very slowly, but my car flies and I get kicked out of the speed trick. What kind of trick is this cheat

Probably some kind of rvanka or "Car Hit"/"Sync hit"/"Whatever anything else" (can be called differently).

**Comment by nex693** [comment]
Can you fix this with the next update? Respects ...

**Comment by NexiusTailer** [comment]
Hardly. The main check to prevent this is anti-speedhack check, which should be triggered both when vehicle's speed sharp increases and/or when the general speed limits are exceeded. If the cheater increases it so smoothly and doesn't exceed the max limits, then you can try perhaps to lower the [max speed limits](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.54/nex-ac.inc#L5185) for anti-speedhack in vehicle, but this can lead to false detections.

**Comment by nex693** [comment]
hm, will you bring an update on this in the new update?
Because I do not understand.

**Comment by NexiusTailer** [comment]
Probably no because of the reasons described above.

**Comment by rt-2** [comment]
> for anti-speedhack in vehicle, but this can lead to false detections, so

Does the speed limit depend on vehicle models?

**Comment by NexiusTailer** [comment]
> > for anti-speedhack in vehicle, but this can lead to false detections, so
> 
> Does the speed limit depend on vehicle models?

Yes, but it makes little sense to set the maximum limits for each vehicle model, since the real speed limit was measured in the ac on x/y/z axes when the car is in free fall. Basically, such limits are identical for all models, as far as it has been tested.

**Comment by rt-2** [comment]
But when the vehicle Z is not decreasing, would it make sense to fall back to vehicle specific limits?

**Comment by NexiusTailer** [comment]
I don't think so, because all actual sobeits/other kinds of speedhacks have their own built-in max speed checks for the required veh model so they don't exceed it.

**Comment by nex693** [comment]
Have you tested the .lua cheat I threw and when will the new update arrive?

**Comment by NexiusTailer** [comment]
Yes, just tested it. As for "/cf.lag" - it doesn't work and easily detected by anti-teleport in vehicle. As for "/cf.fire" it can be prevented by the same anti-teleport in vehicle as I said before, but will only working from a very short distances.

**Comment by nex693** [comment]
/cf.fire works at close range, will you prevent it from working at close range?

From what code is /Cf.lag detected?


I have a question, how can I enter a code so that Pickup is not kicked(PICKUP TELEPORT)

**Comment by NexiusTailer** [comment]
> /cf.fire works at close range, will you prevent it from working at close range?

No, as the only mechanism to prevent this is anti-teleport into vehicle, which starts blocking a player only when a certain distance to the car is exceeded.

> From what code is /Cf.lag detected?

>> probably by anti-teleport into/between vehicles
>> and easily detected by anti-teleport into/between vehicles
>> it can be prevented by the same anti-teleport into vehicle

Anti-teleport into/between vehicles is code 004.

> I have a question, how can I enter a code so that Pickup is not kicked(PICKUP TELEPORT)

I don't understand the question.

**Comment by nex693** [comment]
Anti-teleport (pickups)

Pickups ID
Pickups How do I prevent ID from being thrown away

**Comment by NexiusTailer** [comment]
"Pickups How do I prevent ID from being thrown away" and "Anti-teleport (pickups)" - how that's related to each other?

**Comment by nex693** [comment]
If there is Discord, I can explain it

**Comment by NexiusTailer** [comment]
I don't use it unfortunately.

**Comment by nex693** [comment]
No kick how can i assure
![Uploading 20210111_005137.jpg…]()

**Comment by nex693** [comment]
ID 1273 Pickups No kick Rule how can i assure

**Comment by NexiusTailer** [comment]
> No kick how can i assure

Don't see any picture here.

**Comment by nex693** [comment]
https://hizliresim.com/s0POHf

No kick rule please

**Comment by nex693** [comment]
![20210111_005137](https://user-images.githubusercontent.com/76966752/104137129-b2403f00-53ab-11eb-9408-4a557400f3ec.jpg)




No kick rule please

**Comment by NexiusTailer** [comment]
What is "kick rule"? And what this picture should tell me? How its related to the question?

**Comment by nex693** [comment]
It is not translating the translation. Is it too hard to understand

1273 ID Pickups I don't want it to kick

**Comment by NexiusTailer** [comment]
What way does the "kick" happen? Whom does it "kick"? What does this "kick" produce? I cannot read your mind and now it looks like something incoherent and strange. Just give as detailed information as possible.

**Comment by nex693** [comment]
У меня бандитская система. Античит выбивает меня из игры, когда я получаю 1273 Pickups в системе банды, как мне предотвратить это

1273 Pickups ID

**Comment by nex693** [comment]
Я сейчас напишу на своем родном языке

**Comment by NexiusTailer** [comment]
Okay, anticheat kicks you for anti-pickup teleport when you enter a pickup. Can you provide any log message with the code (subcode)? Also it would be great to know whether it is a streamer pickup or not.

**Comment by nex693** [comment]
правда, но что это за субкод?

**Comment by NexiusTailer** [comment]
The lines you see in server_log when anticheat kicks you

**Comment by nex693** [comment]
Да, могу дать завтра. Мы можем понять, когда говорим на моем родном языке. :)

**Comment by nex693** [comment]
It's hard for me to translate into English because I'm Russian, sorry

**Comment by NexiusTailer** [comment]
А, окей. Я думал ты с турецкого или какого-то подобного переводишь. Но если так проще, то без проблем.

**Comment by nex693** [comment]
Как заблокировать cf.fire действительно стало проблемой

**Comment by NexiusTailer** [comment]
Я уже ответил, что его ловит анти-тп в тачку. Если игрок слишком близко - увы, пока никак.

**Comment by nex693** [comment]
ты русский

**Comment by NexiusTailer** [comment]
Вопрос немного не по теме, но на русском (если тебе удобнее) могу отвечать.

**Comment by nex693** [comment]
У вас есть залог в Аризоне?

**Comment by NexiusTailer** [comment]
Какой залог? Если ты всё таки через что-то переводишь, то давай не отходить от изначального вопроса, который ты сам же и хотел решить.

**Comment by nex693** [comment]
название сервера

**Comment by nex693** [comment]
Когда обновляется античит?

Я хочу дружить с тобой

**Comment by NexiusTailer** [comment]
Обновится тогда, когда на это накопится достаточно изменений и будет время.

Что касается обсуждаемого вопроса, всё ещё жду логи сервера, которые античит показывает при кике. Также информацию о том, является ли пикап стримерским или обычным (с которым происходят проблемы).

**Comment by nex693** [comment]
насколько я знаю, многие большие серверы используют nex-ac
