### ISSUE TITLE
Some weapons that are RapidFiring doesn't get detected

### ISSUE THREAD

**Issue by Jprimero15** [NexiusTailer/Nex-AC#195]
I didn't know if this is known issue but recently i tried a rapidfire with sniper and m4 and nex ac seems like doesn't detect it at all..

**Comment by NexiusTailer** [comment]
He should detect this after a longer time of continuous shooting. Try to shoot continuously a little longer.

**Comment by Jprimero15** [comment]
Should i include callbacks.inc before or after nex-ac.inc ?

**Comment by NexiusTailer** [comment]
Although I don't know what is the include you mentioned, any dependencies except these:
```
If you use Streamer Plugin by Incognito, Pawn.RakNet, foreach, sscanf, YSF or SKY, include it before nex-ac
```
must be connected after the anticheat.
