### ISSUE TITLE
warning 235

### ISSUE THREAD

**Issue by Makan13** [NexiusTailer/Nex-AC#198]
Hello,

When i use `public OnCheatDetected(playerid, ip_address[], type, code)`. but when i try to compile it this warning appears:

> warning 235: public function lacks forward declaration (symbol "OnCheatDetected")

This is the code i am using: `public OnCheatDetected(playerid, ip_address[], type, code)
{
    SendClientMessageToAll(red, ("%s has been kicked for being suspected of cheats.", GetName(playerid)));
	if(Info[playerid][Jailed] == 1)
	{
        EnableAntiCheatForPlayer(playerid, 2, 0);
	}
	else if(Info[playerid][Jailed] == 0)
	{
        EnableAntiCheatForPlayer(playerid, 2, 1);
	}
}`

**Comment by NexiusTailer** [comment]
Just forward this callback function adding this:
```
forward OnCheatDetected(playerid, ip_address[], type, code);
```
before this line:
```
public OnCheatDetected(playerid, ip_address[], type, code)
```
