### ISSUE TITLE
Anti Weapon hack kicks wrongfully

### ISSUE THREAD

**Issue by Makan13** [NexiusTailer/Nex-AC#199]
Hello,
i have another important problem that the anti cheat kicks people wrongfully for weapons hack, (code 15, 16 and 17).
This is the code which players get kicked for (it is in the gamemode):
`public OnWeaponLoad(playerid)
{
    new weaponid, ammo;   
    for(new i, j = cache_get_row_count(mysql); i < j; i++)
    {
        weaponid    = cache_get_row_int(i, 0, mysql);
        ammo        = cache_get_row_int(i, 1, mysql);       
        if(!(0 <= weaponid <= 46)) continue;       
        GivePlayerWeapon(playerid, weaponid, ammo);
    }
    new query[65];
    mysql_format(mysql, query, sizeof(query), "DELETE FROM `Weapons` WHERE `ID` = %d", Info[playerid][ID]);
    mysql_tquery(mysql, query);
    return;
}`

I hope you help me because i really need to use the weapon hack of nex-ac!

**Comment by NexiusTailer** [comment]
Can you give some short video when exactly it kicks players? And how often that occurs?

**Comment by Makan13** [comment]
https://youtu.be/v7csj_o-SqM

Here is the video, I hope it's visible enough to watch properly

**Comment by NexiusTailer** [comment]
And what about server logs?

**Comment by Makan13** [comment]
```
 mysql_format(mysql, query, sizeof(query), "SELECT `Weapon`, `Ammo` FROM `Weapons` WHERE `ID` = %d", Info[playerid][ID]);
    mysql_tquery(mysql, query, "OnWeaponLoad", "i", playerid);
```
```
forward OnWeaponLoad(playerid);
public OnWeaponLoad(playerid)
{
    new weaponid, ammo;
    
    for(new i, j = cache_get_row_count(mysql); i < j; i++)
    {
        weaponid    = cache_get_row_int(i, 0, mysql);
        ammo        = cache_get_row_int(i, 1, mysql);
        
        if(!(0 <= weaponid <= 46)) continue;
        
        GivePlayerWeaponEx(playerid, weaponid, ammo);
    }

    new query[65];
    mysql_format(mysql, query, sizeof(query), "DELETE FROM `Weapons` WHERE `ID` = %d", Info[playerid][ID]);
    mysql_tquery(mysql, query);
    return;
}
```
```
stock SpawnPlayerEx(playerid)
{
    SetPlayerPos(playerid, LastPosX[playerid], LastPosY[playerid], LastPosZ[playerid]);
    SetPlayerInterior(playerid, LastInterior[playerid]);
    SetPlayerHealthEx(playerid, LastHealth[playerid]);
    SetPlayerArmourEx(playerid, LastArmour[playerid]);
    SetPlayerSkin(playerid, OldSkin[playerid]);
    InJob[playerid] = NOJOB;

    new query[100];
    mysql_format(mysql, query, sizeof(query), "SELECT `Weapon`, `Ammo` FROM `Weapons` WHERE `ID` = %d", Info[playerid][ID]);
    mysql_tquery(mysql, query, "OnWeaponLoad", "i", playerid);
    return 1;
}
```

And `SpawnPlayerEx(playerid)` is almost called everywhere

**Comment by NexiusTailer** [comment]
When SpawnPlayerEx is called? I think that native SpawnPlayer somehow is called after the weapon has been issued or OnWeaponLoad is triggered between the PLAYER_STATE_SPAWNED and PLAYER_STATE_ONFOOT states.

**Comment by Makan13** [comment]
Oh hey, i was inactive in gta due to some problems, the only thing that i needed to do was making a timer for onweaponload.
Thanks for your response!

**Comment by NexiusTailer** [comment]
> I think that basic native SpawnPlayer somehow is called after the weapon has been issued or OnWeaponLoad is triggered between the PLAYER_STATE_SPAWNED and PLAYER_STATE_ONFOOT states.

So the problem was with something like this?

**Comment by Makan13** [comment]
Yes exactly, it was triggered between the PLAYER_STATE_SPAWNED and PLAYER_STATE_ONFOOT states. making a delay fixes it
