### ISSUE TITLE
script

### ISSUE THREAD

**Issue by Belarus64** [NexiusTailer/Nex-AC#200]

**Comment by Belarus64** [comment]
fixed please

**Comment by Belarus64** [comment]
/cslap (id) fix please
https://www.mediafire.com/file/rm809fw4kd8yrgs/arz_carslap.luac/file

**Comment by Belarus64** [comment]
https://www.blast.hk/threads/29921/
Buddha works
/gg (id 
total 3 cheats
/gg (id)
/cslap(id)
/cra (id)

**Comment by NexiusTailer** [comment]
> fixed please

Fixed what?

> Buddha works

How does the Buddha related with this anticheat? What nonsense is it?


> /cslap (id) fix please
https://www.mediafire.com/file/rm809fw4kd8yrgs/arz_carslap.luac/file

>https://www.blast.hk/threads/29921/
/gg (id)
https://www.mediafire.com/file/rm809fw4kd8yrgs/arz_carslap.luac/file
/cslap(id)
https://www.blast.hk/threads/59474/
/cra (id)

As for all these cheats, it should be detected by anti-speedhack (in vehicle) or anti-teleport hack, or both. Otherwise you use them from too close a distance.

**Comment by Belarus64** [comment]
no, he doesn't perceive it at all 

far or near

look try

**Comment by Belarus64** [comment]
You don't need to be angry, test it as it doesn't detect any of them from afar or up close

**Comment by NexiusTailer** [comment]
I'm not angry, I just make it clear that all those cheats detected for a long time (maybe even since their release). If it was not detected while you tested it - you tested it from too little distance between the players. And nothing can be done with that.

**Comment by Belarus64** [comment]
Remotely checked it doesn't detect any of them You should really test

**Comment by NexiusTailer** [comment]
I probably test it for a year(s) ago and fixed everything that could be fixed. For the rest, I can only repeat everything said above

**Comment by Belarus64** [comment]
Tried to throw the man from afar, can you try them all please cheats work

**Comment by Belarus64** [comment]
I tested it 5 times

**Comment by Belarus64** [comment]
I'm not giving you false information, it works, these cheats are being tested
It works remotely. Please accept

**Comment by NexiusTailer** [comment]
Let me ask the question directly: why are you so annoying? I check new cheats within a few days after their release, including on the portal mentioned above, and certainly if I say something specific and definite about these cheats, then they have already been checked and all the necessary fixes have been made **which it were possible**. So, I see no reason to repeat the same things until you yourself get tired of having this conversation.

**Comment by Belarus64** [comment]
You have to admit that these cheats worked and you didn't fix them

**Comment by Belarus64** [comment]
get in the car do / cslap (id) to someone in the car and see

**Comment by NexiusTailer** [comment]
They can only work if there is no possible fix without many false detections or other similar problems.

**Comment by Belarus64** [comment]
anti cheating is not very good. These cheats work and should be improved
I guess you should fix these cheats

**Comment by NexiusTailer** [comment]
I guess I answered the question and now you just repeat the same thing in very poorly connected phrases.

**Comment by Belarus64** [comment]
OKAY. But you're doing it wrong TEST it and see it works

**Comment by NexiusTailer** [comment]
Check [this](https://github.com/NexiusTailer/Nex-AC/issues/200#issuecomment-770282667)

**Comment by Belarus64** [comment]
so why is it running on my server

**Comment by NexiusTailer** [comment]
Running what?

**Comment by Belarus64** [comment]
okay but can you try man, see it working

**Comment by NexiusTailer** [comment]
Tried for a long time ago, just read the messages above.
