### ISSUE TITLE
Здравствуй

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#201]
привет в чем разница между красавцем nex-ac_rakcheat и nex-ac

**Comment by NexiusTailer** [comment]
Что ты имеешь в виду под "красавцем"?

**Comment by nex693** [comment]
ты думаешь, я должен использовать ?

**Comment by NexiusTailer** [comment]
Что использовать?

И что насчёт этого?
> Что ты имеешь в виду под "красавцем"?

**Comment by Heyter** [comment]
> ты думаешь, я должен использовать ?

Не используй ничего, все эти античиты лишь вредят твоему серверу, вирусы нагрузят и будешь потом сидеть весь в майнерах.
