### ISSUE TITLE
Casino errors

### ISSUE THREAD

**Issue by wearLyS** [NexiusTailer/Nex-AC#202]
Hello Nexius, at the casino, if the player has no money he can bet and be negative, I have no idea how to solve this, and I would also like to know if I can disable the bets over $ 10,000

**Comment by NexiusTailer** [comment]
Is there a problem with some kicks gor negative amounts of money or it's just a problem of singleplayer casino logic? The second cannot be solved serverside and casino should be just re-created by the server.

**Comment by wearLyS** [comment]
By the Nex-AC system which releases casinos, there you are allowed to bet without money, leaving the player's money negative, but there are no kicks.

**Comment by NexiusTailer** [comment]
This is a feature of the game system in the singleplayer, so the anticheat can hardly do anything about it. I think it would really better to re-create the casino system (remove default tables/roulette objects and create your own based on server-side algorithms).
