### ISSUE TITLE
Speedhack on foot 

### ISSUE THREAD

**Issue by sir2931** [NexiusTailer/Nex-AC#204]
Hey,

Nex-AC can't detect this cheat, do you have any idea to fix this?
https://www.dropbox.com/s/sgbby9qdgfamw2h/FastWalk.cs?dl=0
changes the speed of the ped - b+1 normal B=2 faster B=3 even faster b+4 even faster b+5 very fast b+6

"B=2" and "B=3" not detect by nex-ac

**Comment by NexiusTailer** [comment]
Because these are still slow enough speeds for anti-speedhack (onfoot) to start detecting them. Nothing can be done about it, unfortunately.
