### ISSUE TITLE
AC_USE_NPC

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#205]
I've a question about the post at https://pawn-wiki.ru/index.php?/topic/27641-nex-ac/page__view__findpost__p__248003

Currently I have `#define AC_USE_NPC	true`

My server doesn't have any NPCs.

What will setting this to false do exactly? I.e. what kind of extra protection can I expect?

**Comment by NexiusTailer** [comment]
1. Any NPC connections will be rejected so you can be fully protected from raksamp and other hackers which uses npc:join to bypass anti-cheat checks
2. All IsPlayerNPC exception checks inside every callback will be disabled so npc won't be ignored for any anti-cheat check
