### ISSUE TITLE
Anti-money hack problem

### ISSUE THREAD

**Issue by wearLyS** [NexiusTailer/Nex-AC#206]
When a player is stunting and using a money hack, he is able to circumvent the anti-cheater.

I believe that this also happens when playing at the casino, among other ways.

**Comment by NexiusTailer** [comment]
Yes it is. If you don't want to see this on your server, disable stunt bonuses and casinos (and if you still need them, recreate it server sided). This cannot be controlled in any way when it happens on the player's side. Currently anticheat can control only ammu-nation and tuning garage component buyings (and kick players if they don't lose their money for that buying).
