### ISSUE TITLE
Ammo hack problem

### ISSUE THREAD

**Issue by sir2931** [NexiusTailer/Nex-AC#207]
Hey,
I have a problem with ammo hack when the player in-vehicle use the cmd like that :
`	GivePlayerWeapon(playerid,WEAPON_SAWEDOFF,9999);
	GivePlayerWeapon(playerid,WEAPON_UZI,9999);
	GivePlayerWeapon(playerid,WEAPON_CHAINSAW,9999);
	GivePlayerWeapon(playerid,WEAPON_DEAGLE,9999);
	GivePlayerWeapon(playerid,WEAPON_M4,9999);
	GivePlayerWeapon(playerid,WEAPON_SNIPER, 9999);`
got been kicked after 2 second.
[27/02/2021 15:33:44] [Nex-AC debug] AC ammo: 9999, ammo: 10028, weaponid: 31
[27/02/2021 15:33:44] [Nex-AC] Suspicion on the ID 23. Reason code: 016 (3)
Even With EnableAntiCheatForPlayer(playerid, 16) before and after not working.
Thanks

**Comment by rt-2** [comment]
Check out https://github.com/NexiusTailer/Nex-AC#enableanticheatforplayerplayerid-code-enable

You have a mistake in `EnableAntiCheatForPlayer(playerid, 16)`, it should be `EnableAntiCheatForPlayer(playerid, 16, 0)`

**Comment by sir2931** [comment]
> Check out https://github.com/NexiusTailer/Nex-AC#enableanticheatforplayerplayerid-code-enable
> 
> You have a mistake in `EnableAntiCheatForPlayer(playerid, 16)`, it should be `EnableAntiCheatForPlayer(playerid, 16, 0)`

Yes, I exactly do that.
`
EnableAntiCheatForPlayer(playerid, 16, 0);
	EnableAntiCheatForPlayer(playerid, 15, 0);
	GivePlayerWeapon(playerid,WEAPON_SAWEDOFF,9999);
	GivePlayerWeapon(playerid,WEAPON_UZI,9999);
	GivePlayerWeapon(playerid,WEAPON_CHAINSAW,9999);
	GivePlayerWeapon(playerid,WEAPON_DEAGLE,9999);
	GivePlayerWeapon(playerid,WEAPON_M4,9999);
	GivePlayerWeapon(playerid,WEAPON_SNIPER, 9999);
	EnableAntiCheatForPlayer(playerid, 15, 1);
	EnableAntiCheatForPlayer(playerid, 16, 1);
`

**Comment by NexiusTailer** [comment]
Just tried that on a test, cannot reproduce any such behaviour.

**Comment by sir2931** [comment]
Sometimes increase in gun ammo or reset weapons or give weapon nex-ac kick the player with reason 15 or 16.
ResetPlayerWeapons(playerid):
[04/03/2021 11:45:50] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 30, ammo: 26
[04/03/2021 11:45:50] [Nex-AC] Suspicion on the ID 38. Reason code: 015 (2)
What can I do for it ?
Thank you for your time and effort

**Comment by NexiusTailer** [comment]
Again, I haven't face such problem, so more information/an exact way to reproduce this is needed.
