### ISSUE TITLE
Optional Anti Cheats

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#208]
Just recently I set AC_USE_NPC to false to improve protection on my server.

I wondered, are there any other optional settings that one can tweak to enable additional anti-cheat?

**Comment by NexiusTailer** [comment]
All such optional settings can be configured via defines which can be found at the beginning of the anticheat and which start with "AC_USE_" prefix.

**Comment by elvianod982** [comment]
AC_USE_AMMUNATIONS true
AC_USE_PICKUP_WEAPONS true
AC_USE_RESTAURANTS true
AC_USE_CASINOS true

On my server, I have all of these features disabled (ammunations, restaruants and casinos are closed, weapon drops are disabled. So am I right in saying that I would be best to set these values to false in order to unlock additional protection?

**Comment by NexiusTailer** [comment]
Yes, it is. Having those defines enabled and not using the features you just make anticheat ignore unnecessary situations that could never happen to normal players, but which could be used by cheaters as a workaround.
