### ISSUE TITLE
Errors and Warnings

### ISSUE THREAD

**Issue by babab4757** [NexiusTailer/Nex-AC#209]
When I compile with the include I get this errors and warnings:

C:\pawno\include\nex-ac.inc(7902) : warning 202: number of arguments does not match definition
C:\pawno\include\nex-ac.inc(7902) : warning 202: number of arguments does not match definition
C:\pawno\include\nex-ac.inc(7902) : warning 202: number of arguments does not match definition
C:\pawno\include\nex-ac.inc(7960) : error 025: function heading differs from prototype
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

What can I do?

**Comment by NexiusTailer** [comment]
See what callback are on the lines and update their parameters in **your** gamemode according to the lastest a_samp.inc declarations.
