### ISSUE TITLE
AC kicks players when call SetPlayerPos in hook OnPlayerSpawn (It only occurs with DisableInteriorEnterExits enabled)

### ISSUE THREAD

**Issue by 81Vm3** [NexiusTailer/Nex-AC#212]
Nex-AC version 1.9.55
YSI version 5.03.0689

Using y_hooks.inc to hook OnPlayerSpawn, Nex-AC kicks player whenever SetPlayerPos is called inside the callback, this only happens if DisableInteriorEnterExits has ever been called.
If I however unhook the callback to original OnPlayerSpawn, the AC does not kick players anymore.

Info when the AC kick an innocent player:
`[Nex-AC] Suspicion on the ID 0. Reason code: 002 (2)`

**Comment by NexiusTailer** [comment]
This occurs because YSI hooks are executed before the usual ALS hooks (that anticheat has, too). Try to use ALS hooks for OnPlayerSpawn in your script so that it's called right after all includes' ALS hook chain.

**Comment by 81Vm3** [comment]
> This occurs because YSI hooks are executed before the usual ALS hooks (which used in anticheat too). Try to use ALS hooks for OnPlayerSpawn in your script so that it's called right after all includes' ALS hook chain.

That works indeed, thanks for correcting me. :D
