### ISSUE TITLE
anti teleport

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#213]
анти-телепорт активен, но есть те, кто может использовать номер телепорта, вы можете его вылечить

AC полностью активен

**Comment by NexiusTailer** [comment]
Нужна более подробная информация нормально сформулированными предложениями.

**Comment by nex693** [comment]
anti teleport should be developed
Player teleported to another player and did not detect nex-ac
There was quite a difference from distance to distance was supposed to perceive (SF.LV

Note: Nex-AC Full active and up to date

**Comment by NexiusTailer** [comment]
> anti teleport should be developed

It's already developed O_o

> Player teleported to another player and did not detect nex-ac

Then you need to share a specific cheat so that I can test it

**Comment by nex693** [comment]
no tricks :(

But I saw her teleport to the actress
