### ISSUE TITLE
Anti weapon hack rule cod help

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#214]
/ gun (player ID) (weapon ID), when I give a gun to my player the player gets kicked

Kick code : 15

**Comment by NexiusTailer** [comment]
This information is not detailed enough to reproduce and solve the problem

**Comment by nex693** [comment]
Let me explain as follows; The player gets kicked when the manager gives a gun

OstGot Gives a Gun to the Player, and the person with a gun is kicked.

Code: 15 (Weapon hack)

**Comment by NexiusTailer** [comment]
There is still no debug ac info from the server log. Also, I need the sample code to be able to reproduce this on a blank gamemode.

**Comment by nex693** [comment]
here you are:

[10/04/2021 20:43:33] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 15, ammo: 100
[10/04/2021 20:43:33] [Nex-AC] Suspicious player ID : 15.  code: 015 (2)

**Comment by NexiusTailer** [comment]
What about minimum working code example?

**Comment by nex693** [comment]
What is the rule code I will enter there at that moment when a player is making a transaction?

EnableAntiCheatForPlayer(playerid, 15 ,0); fix in this code is closing

**Comment by NexiusTailer** [comment]
https://en.wikipedia.org/wiki/Minimal_working_example

**Comment by nex693** [comment]
I do not understand, I will tell you about such a problem. When the player shows up, does the code kick from 52?

**Comment by NexiusTailer** [comment]
Just provide the code which causes that problem, but it would be great to see it without any dependencies or your project's variables so I could be able to reproduce this on a blank gamemode.

> When the player shows up, does the code kick from 52?

Don't understand the question

**Comment by nex693** [comment]
I showed this as an example, when real error pops up it says gun number

When you are born you get kicked by anti-weapon cheating this is real mistake

public OnPlayerSpawn(playerid)
{
EnableAntiCheatForPlayer(playerid, 15, 0);

I'm doing it this time, fix turn off, they turn up the number

**Comment by nex693** [comment]
should not be thrown during ovulation you need a rule code for this

that's the translation sorry from arabic to english :(

**Comment by nex693** [comment]
If you don't have prejudice against Arabs, you can help me.

**Comment by nex693** [comment]
error example

cmd:spawn(playerid, params[])
{
	new ID;
	SpawnPlayer(ID);
}

player spawn anti cheat kick error code 15

**Comment by NexiusTailer** [comment]
Can't reproduce that

**Comment by nex693** [comment]
stock weapons(playerid, weaponid, ammo)
{
    EnableAntiCheatForPlayer(playerid, 15, 0);
	if (weapons < 0 || weapons> 46) return 0;
	Weapons[playerid][ww[weaponid] = weaponid;
	ammo[playerid][ww][weaponid]] = ammo;
	return GivePlayerWeapon(playerid, silahid, ammo);
}
can you fix this code

**Comment by nex693** [comment]
Anti-cheat system detects gun fraud when golf cart explodes

**Comment by NexiusTailer** [comment]
> stock weapons(playerid, weaponid, ammo)
> {
> EnableAntiCheatForPlayer(playerid, 15, 0);
> if (weapons < 0 || weapons> 46) return 0;
> Weapons[playerid][ww[weaponid] = weaponid;
> ammo[playerid][ww][weaponid]] = ammo;
> return GivePlayerWeapon(playerid, silahid, ammo);
> }
> can you fix this code

This will not work on a blank gm

> Anti-cheat system detects gun fraud when golf cart explodes

Is this another different issue or it is still about the first problem?

**Comment by nex693** [comment]
a different problem

**Comment by nex693** [comment]
When the golf cart explodes, I kick when I get off, can you figure it out?

**Comment by NexiusTailer** [comment]
So what about the logs?

**Comment by nex693** [comment]
[11/04/2021 20:21:01] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 2, ammo: 1
[11/04/2021 20:21:01] [Nex-AC]  ID : 9.  code: 015 (1)

**Comment by nex693** [comment]
How can I keep me from kicking when I get a gun from my gun stock?

stock weapons(playerid, weaponid, ammo)
{
EnableAntiCheatForPlayer(playerid, 15, 0);
if (weapons < 0 || weapons> 46) return 0;
Weapons[playerid][ww[weaponid] = weaponid;
ammo[playerid][ww][weaponid]] = ammo;
return GivePlayerWeapon(playerid, silahid, ammo);
}

**Comment by nex693** [comment]
I gotta get into a rule that won't kick me right now

**Comment by nex693** [comment]
I want that rule code

**Comment by nex693** [comment]
new logs

[11/04/2021 21:10:11] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 2, ammo: 1
[11/04/2021 21:10:11] [Nex-AC] ID : 8. code 015 (1)

**Comment by NexiusTailer** [comment]
> [11/04/2021 20:21:01] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 2, ammo: 1
> [11/04/2021 20:21:01] [Nex-AC] ID : 9. code: 015 (1)

If your ped is automatically given a golf club when exiting the car, then remove sobeit and all other cheating mods. Specifically, d3d9.dll is responsible for issuing weapons when player exiting golf car.

**Comment by nex693** [comment]
This happens with the players, I have no complaints.
Give me a rule code so I don't kick it right now, all I want is

**Comment by NexiusTailer** [comment]
So then these players should remove sobeit and other cheating mods

**Comment by nex693** [comment]
we checked clean. 

I will talk about one more problem, when it occurs, the code is throwing because of 52.

(Spawn bug code 52 kick bug)

**Comment by nex693** [comment]
I just want the rule code so that the player is not kicked at the moment.
please give this

**Comment by nex693** [comment]
I'll enter a rule not to be kicked out but what's the code

**Comment by NexiusTailer** [comment]
> we checked clean.

Those players obviously have modified files as original game nor samp client ain't giving any weapons when you golf car.

**Comment by nex693** [comment]
I just want the rule code so that the player is not kicked at the moment.
please give this

I'll enter a rule not to be kicked out but what's the code
Will you give this code or not?

**Comment by NexiusTailer** [comment]
I don't understand what "rule code" you need. The solution of your current problem is to remove shitty mods like sobeit and/or everything else which adds d3d9.dll file.

**Comment by nex693** [comment]
Ok, I am waiting for you with major updates.

**Comment by nex693** [comment]
IsAntiNOPEnabled what does this code do

**Comment by nex693** [comment]
I will talk about a problem
When someone cuts his throat with a knife

Someone hurt you in the back with the Knife 

RESULT :
[12/04/2021 17:39:00] [Nex-AC debug] Dist: 677.064880, dist set: 25000.000000, speed: 0, pos x, y, z: -2707.343505, 375.201782, 4.968762, old pos x, y, z: -2203.724853, -76.311096, 35.320301
[12/04/2021 17:39:00] [Nex-AC] ID : 6. Code: 002 (2)
[12/04/2021 17:39:00] [part] fCarl has left the server (6:2)

**Comment by nex693** [comment]
and this doesn't always happen

**Comment by NexiusTailer** [comment]
> I will talk about a problem
> When someone cuts his throat with a knife
> 
> Someone hurt you in the back with the Knife
> 
> RESULT :
> [12/04/2021 17:39:00] [Nex-AC debug] Dist: 677.064880, dist set: 25000.000000, speed: 0, pos x, y, z: -2707.343505, 375.201782, 4.968762, old pos x, y, z: -2203.724853, -76.311096, 35.320301
> [12/04/2021 17:39:00] [Nex-AC] ID : 6. Code: 002 (2)
> [12/04/2021 17:39:00] [part] fCarl has left the server (6:2)

Need the minimal working example to be able to reproduce it on a blank gm

**Comment by nex693** [comment]
Try this with any player to be kicked out
I wanted to show if there is a server thread

**Comment by NexiusTailer** [comment]
If this worked on a blank gamemode, this issue would have been fixed long ago. So, waiting for minimal working code example.

**Comment by NexiusTailer** [comment]
So you should provide the code on which it is starting to occurs. Otherwise, the issue has no any specific information to reproduce that and can be closed.

**Comment by nex693** [comment]
They run it on the server. Can you give me a solution?
