### ISSUE TITLE
which one is more correct

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#215]
Do we need a kick condition for Code 52?

SAMPLE : case 52: return Kick(playerid);

SAMPLE 2 : case 52: return 1;

which one is more correct

**Comment by NexiusTailer** [comment]
It depends of what you need.

Default example of using OnCheatDetected callback can be found here:
https://github.com/NexiusTailer/Nex-AC/blob/master/CHANGELOG.md

**Comment by nex693** [comment]
My player is thrown by code 52 when it appears for any reason
What does code 52 do?

**Comment by NexiusTailer** [comment]
This is protection from NOPs

**Comment by nex693** [comment]
How nops damage the server ? like what

**Comment by NexiusTailer** [comment]
Well they just ignore certain functions that server sends them for applying. That way, the player who use NOP SetPlayerHealth can ignore any commands of setting his health from the server.

**Comment by nex693** [comment]
sometimes unnecessary kicks Code 52


 in the spawning area

**Comment by nex693** [comment]
If I don't kick the anti-mode thing, will people see if I can change the car?

**Comment by NexiusTailer** [comment]
> If I don't kick the anti-mode thing, will people see if I can change the car?

If you disable any of the codes, then I'll allow the cheaters to use it. This is never a solution

> sometimes unnecessary kicks Code 52
in the spawning area

As always: I need anticheat logs and minimum working code example to be able to reproduce it on a blank gm.

**Comment by nex693** [comment]
you won't get errors in an empty gm
The important thing is that there are no errors in full mode.

**Comment by NexiusTailer** [comment]
Then you have to find out (by analysis and various tests) that specific part of the code with which this (and any other problem you have before) begins with.

None of the problems you have listed will be resolved without your participation in providing specific information.

**Comment by nex693** [comment]
Okay, I know you're interested in /pizda and /cslap cheats 
you are really experienced
good luck god bless you

**Comment by NexiusTailer** [comment]
> Okay, I know you're interested in /pizda and /cslap cheats

As for these cheats, according to what I've said [here](https://github.com/f0Re3t/nex-ac_rakcheat/issues/13#issuecomment-817948157), they hardly can be fixed.

**Comment by nex693** [comment]
I believe someone said this but I don't believe you
There's nothing you can't do in pawn coding

**Comment by NexiusTailer** [comment]
It's just a fact that remains so regardless of your belief in it

**Comment by NexiusTailer** [comment]
Btw, if you still cannot provide more specific information on your problems listed above, I'll close the issue soon.

**Comment by nex693** [comment]
tamam tamam teşekkürler
