### ISSUE TITLE
What

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#218]
![fghfgh](https://user-images.githubusercontent.com/76966752/115443483-ff8a4300-a21b-11eb-8813-0708563ed821.PNG)

Has a crashing problem for 3 days
Code 44 detects but server shuts down

Can you help me with this? We didn't cheat, we can't find the person who did it.

**Comment by NexiusTailer** [comment]
"Server Exit..." is not an original message from samp-server executable when it shuts down. Most probably the problem is in your gamemode script if you didn't change this string manually.

**Comment by nex693** [comment]
I wrote it for you to understand

The trick is this: all tools on the server are reversed and fall into these logs and the server shuts down.

![](https://user-images.githubusercontent.com/76966752/115443483-ff8a4300-a21b-11eb-8813-0708563ed821.PNG)

Code 44: how do I refine?

**Comment by NexiusTailer** [comment]
Leave the original logs "to understand". The thing you have done is only confusing and does not provide any specific information.

**Comment by nex693** [comment]
![20210421_005738](https://user-images.githubusercontent.com/76966752/115469068-a5e64080-a23c-11eb-90dd-e0f7e90ada6d.jpg)

Down vehicle crasher :(

**Comment by nex693** [comment]
I left the diaries

**Comment by nex693** [comment]
server shuts down
about the tools but i couldn't figure it out

**Comment by nex693** [comment]
I use pawn.raknet, crashdetect, nativecher plugins

All up to date

**Comment by nex693** [comment]
Nexius, this problem is very serious, this is the first time I'm facing such a situation, please help me.
nex ac is up to date and fully active

**Comment by nex693** [comment]
![20210421_012510](https://user-images.githubusercontent.com/76966752/115471385-8ea95200-a240-11eb-84e2-628ec80d8a3c.jpg)
crasher attack again

**Comment by nex693** [comment]
![Uploading 20210421_020633.jpg…]()
crashinfo debug

**Comment by NexiusTailer** [comment]
Then use [crashdetect](https://github.com/Zeex/samp-plugin-crashdetect) plugin to be able to see additional debug info in the server log. Also don't forget to put "pawn.cfg" file with "-d3" string in your compiler folder and recompiler your scripts.

**Comment by nex693** [comment]
no problem in the mode
it's a trick and we need to fix it
OnPlayerEnterVehicle related

**Comment by NexiusTailer** [comment]
Too vague as usual. Provide logs with the crashdetect plugin that will point to a specific piece of code.

**Comment by nex693** [comment]
The crashdetect server did not drop anything in the log

**Comment by nex693** [comment]
Something about vehicles sends a request to get on vehicles
I entered a little rule on the player tool, I'll understand the logic from there

**Comment by NexiusTailer** [comment]
> The crashdetect server did not drop anything in the log

If you get crashlog.txt and it's a real server crash and not just shutdown by your gamemode, crashdetect *must* print something (at least basic info) in the main log file. Re-check and make sure that you really added it in server.cfg ('plugins' line) and the plugin successful starts with the server.

**Comment by nex693** [comment]
> ![20210421_020633](https://user-images.githubusercontent.com/76966752/115474625-82c08e80-a246-11eb-9970-1b708a274e81.jpg)
> 
> crashinfo debug

This is

**Comment by NexiusTailer** [comment]
I'm about crash log from crashdetect

> in the main log file

**Comment by nex693** [comment]
I solved the problem by disabling the code 44.
code 44 fix problem
SobFoX does this

**Comment by nex693** [comment]
![20210421_202229](https://user-images.githubusercontent.com/76966752/115595304-6e7ca000-a2df-11eb-8926-c782aa8943d2.jpg)

What does it mean?

**Comment by NexiusTailer** [comment]
Disabling a code is not a solution, so I still wait for crashdetect logs

**Comment by nex693** [comment]
I found the number. We gathered the tools together on the server and dropped the fps and the server shuts down.

**Comment by NexiusTailer** [comment]
What number? Just add crashdetect and share its logs when the server crashes...

**Comment by nex693** [comment]
okay I'll share it ... I found the logic of the trick: the tools are gathering together, the server shuts down, it did it in front of my eyes

fps  : 0

**Comment by NexiusTailer** [comment]
Which tools?

**Comment by nex693** [comment]
![Uploading vicecity.PNG…]()

**Comment by nex693** [comment]
![sa-mp-021](https://user-images.githubusercontent.com/76966752/115611267-86a9ea80-a2f2-11eb-9800-c83bfedd99da.png)

**Comment by nex693** [comment]
![vicecity](https://user-images.githubusercontent.com/76966752/115611336-9d504180-a2f2-11eb-86cf-16b39dda0754.PNG)

**Comment by nex693** [comment]
kicks everyone out of the game anti cheat
What is this

**Comment by NexiusTailer** [comment]
Need more information.

And what about crashdetect logs?

**Comment by nex693** [comment]
does not exist

Can I talk to you something special from a private place 
I'll be open there

**Comment by NexiusTailer** [comment]
> does not exist

->
> crashdetect must print something (at least basic info) in the main log file. Re-check and make sure that you really added it in server.cfg ('plugins' line) and the plugin successful starts with the server.

**Comment by nex693** [comment]
No sinker, misunderstanding

Crasher no
it was a problem with the mod

The problem is there is the cheat that puts the tools together and kicks the players by anti-cheat.

She says she did this using the pawn.raknet vulnerability.

**Comment by nex693** [comment]
:

**Comment by NexiusTailer** [comment]
Which tools it puts together? What the "tools"? "Kicks the players by anti-cheat" - which reasons? What pawn.raknet vulnerability? Who is "she" that says? More information, as usual.

**Comment by nex693** [comment]
How do I prevent the player from closing data?

I've been friends with the scammer. He told me he spawned vehicles by turning off player data

**Comment by nex693** [comment]
I'll talk to Katursiz on Discord

I want you to know that too. How do they turn off Player Data?

**Comment by NexiusTailer** [comment]
> I've been friends with the scammer. He told me he spawned vehicles by turning off player data

If you NOP outgoing client sync, I'll be the only one who will see that he is doing. It's just desynchronization which makes no sense as it doesn't harm others.

**Comment by nex693** [comment]
> > I've been friends with the scammer. He told me he spawned vehicles by turning off player data
> 
> If someone NOP outgoing client sync, that player will be the only one who will see that he is doing. It's just desynchronization which makes no sense as it doesn't harm others.
> 
> > For a specific reason I cannot post logs here. If there is a place we can talk privately, I can throw it away.
> > Special logs
> 
> You can share it via pastebin.

No, everybody's game is getting worse. everybody's FPS , 7 ,8 is happening


There is currently no log I can share.

**Comment by NexiusTailer** [comment]
> No, everybody's game is getting worse. everybody's FPS , 7 ,8 is happening

Then it's something else, not related to what you described

> There is currently no log I can share.

So do you have any logs or not? Decide at last

**Comment by NexiusTailer** [comment]
If you just want to chat and waste my time like in several previous issues, don't wait and tell me about it now so I'll be able to close this as usual.

**Comment by nex693** [comment]
Closed. but you need to fix it in 1.9.56.

**Comment by NexiusTailer** [comment]
I don't know the problem which I should "fix"

**Comment by nex693** [comment]
Because I'm not Russian or English
i'm arab and i'm translating

The only thing I know about cheating is this 

brings together tools.
This is all I know
Translation is translating incorrectly

**Comment by nex693** [comment]
هل تعرف اللغة العربية ؟

**Comment by NexiusTailer** [comment]
Then you could already rephrase the sentence, describing your problem as concretely as possible. I don't understand what "tools" you are talking about.

**Comment by nex693** [comment]
There's a hack that spawns vehicles together 

seems to everyone

**Comment by nex693** [comment]
I wasn't the one who made cheats

I just took a photo

**Comment by nex693** [comment]
![115611336-9d504180-a2f2-11eb-86cf-16b39dda0754](https://user-images.githubusercontent.com/76966752/115865316-d26aaa00-a440-11eb-9985-1de6145857f7.PNG)

Photo

**Comment by NexiusTailer** [comment]
Should be detected either by 003, 004 or 005 anticheat codes. Check whether it all turned on.

**Comment by nex693** [comment]
when this cheat is used

everybody's FPS 7 is happening

**Comment by nex693** [comment]
case 3: Kick (playerid);
case 4: Kick (playerid);
case 5: return 1;
case 6: return 1;

server cfg full anti cheat active

**Comment by nex693** [comment]
says she did this with the pawn.raknet vulnerability cheater

**Comment by NexiusTailer** [comment]
There are no [known vulnerabilities](https://github.com/katursis/Pawn.RakNet/issues) in the latest version.

**Comment by nex693** [comment]
then how can they do that?

**Comment by nex693** [comment]
Is there rpc spam protection in Nex-ac

when cheating is used. 

Pawn.Raknet by They get kicked unnecessarily

**Comment by nex693** [comment]
This means that pawn.raknet's vulnerability

**Comment by NexiusTailer** [comment]
> then how can they do that?

If you are using an outdated version of the plugin (not the latest), then there may have been some problems with them earlier and you are faced with such already fixed vulnerabilities.

**Comment by nex693** [comment]
everything is up to date.

About the cheat I'm talking about Will you bring an update?

**Comment by NexiusTailer** [comment]
"Will I'm bring an update" on what? Fixing what? There are no things to update in this case if you can't provide enough information about the problem. But if you mean regular updates that are already planned - yes, they will be.

**Comment by nex693** [comment]
There's a hack that spawns vehicles together

seems to everyone
I wasn't the one who made cheats

I just took a photo

-----
I don't know anything about cheating either
it just makes the game worse


a hack that brings together tools
This is all I know

![Uploading 115611336-9d504180-a2f2-11eb-86cf-16b39dda0754.PNG…]()

**Comment by nex693** [comment]
there is nothing to do
a hope...

**Comment by NexiusTailer** [comment]
If this is a basic vehicle teleport, then, as I wrote above, this is detected by code 005 (less often by 003 or 004, if the cheater teleports himself to each car)

**Comment by nex693** [comment]
all ON

**Comment by NexiusTailer** [comment]
Then you should provide the cheat itself or specific information how it works.

**Comment by nex693** [comment]
Can't do without getting into the vehicle(Onfoot it's not happening)
after getting in the vehicle 

VE
![115611336-9d504180-a2f2-11eb-86cf-16b39dda0754](https://user-images.githubusercontent.com/76966752/115889548-b5dc6b00-a45c-11eb-86a8-466fa9338101.PNG)

**Comment by nex693** [comment]
This is all I know

can only do it while in the vehicle

**Comment by NexiusTailer** [comment]
This information is not enough
