### ISSUE TITLE
Invisible Mode Hack 

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#223]
https://www.youtube.com/watch?v=oRhFRVCNPCQ

I am using the latest release of Nex-AC but apparently this (shown above) is an on-going issue.

Any options to help tackle this?

**Comment by NexiusTailer** [comment]
Tested it just now on the current release and it just doesn't work: "invisible mode" activated with the corresponding notification like in the video, but no other effects or changes. Using of any cheat (including airbreak onfoot) still detected like before.

**Comment by elvianod982** [comment]
I've seen plenty of people still using this cheat, even with the latest version of Nex-AC.

I recorded it: https://streamable.com/cn5gqw

They're always inside this same strange interior and kill players, as you can see from the killboard. 

I tried installing the cheat that I linked to in that youtube video, but I was unable to get it to install properly. Perhaps you can test it on my server if I provide the IP?

**Comment by rt-2** [comment]
@elvianod982 Is the problem also happening on a blank gamemode?

**Comment by elvianod982** [comment]
@rt-2 - I don't know because I can't get the cheat working on my local PC in order to test it.

**Comment by NexiusTailer** [comment]
> I've seen plenty of people still using this cheat, even with the latest version of Nex-AC.
> 
> I recorded it: https://streamable.com/cn5gqw

Judging by the video, the player definitely isn't in spectator mode and remains visible for others, as you can still spectate him. This says little, but anyway considered it important to note it.

As for cheat testing, try to find someone on your server who have definitely working cheat with his game and ask him to go to blank gm server to re-check it there. As I already said, when I was testing this cheat, it just didn't work (has no any effect despite the fact it reported a successful load) and the anticheat detected any hacks with it as before.

**Comment by elvianod982** [comment]
What the heck...

I just tested it on a blank gamemode (grandlarc) and indeed, it had no effect. It said invisible mode activated, but the player was still visible. On my own gamemode, the player becomes invisible.

Clearly this is not related to Nex-AC, but do you have any ideas what might cause that behaviour?

**Comment by rt-2** [comment]
This is gonna need some trial and error.
Try to remove any includes and gamemode and run your gamemode as bare as possible and if luckily the problem is fixed, then add everything back one by one. If not then you're gonna have to research some keywords or callbacks in your script. Maybe @NexiusTailer would know a little more what could interfere.
Good luck.

**Comment by elvianod982** [comment]
I found the cause, but I don't think it would be particularly wise to disclose it in public as I know this will impact a lot of servers. I can now reproduce it on a bare gamemode with ease.

@NexiusTailer - can I contact you in private somehow?

**Comment by NexiusTailer** [comment]
@elvianod982 sure, could go to discord
Nexius#1337

**Comment by rt-2** [comment]
Wow you really have the discord id 1337? Im extremely jealous now...

**Comment by NexiusTailer** [comment]
> Wow you really have the discord id 1337? Im extremely jealous now...

It's just one of discord nitro classic features, changed my ID there recently

Btw, you have long been in my contacts there :)
![image](https://user-images.githubusercontent.com/13169094/133149739-d43e62c2-6b0f-4a14-acc7-32858de2e960.png)

**Comment by rt-2** [comment]
> > Wow you really have the discord id 1337? Im extremely jealous now...
> 
> It's just one of discord nitro classic features, changed my ID recently

Ho I see lol

> 
> Btw, seems you have long been in my contacts there :)
> ![image](https://user-images.githubusercontent.com/13169094/133149739-d43e62c2-6b0f-4a14-acc7-32858de2e960.png)

Yes well we had to test together to finally find the bug behind #20 a long time ago. Its very nice that you took the time for multiple test sessions.
Thanks for all the hard work through the years btw man!
rt-2
