### ISSUE TITLE
Teleport-Error

### ISSUE THREAD

**Issue by babab4757** [NexiusTailer/Nex-AC#227]
Hi, when players are spawning in they get kicked out. 
Reason: You have been kicked on suspicion of using cheat programs (#002)
This is wrong as it kicks players when they spawn in. What can I do to fix this error?

**Comment by babab4757** [comment]
Link so you can see for yourself:

https://youtu.be/mKiZpMXWjHY

**Comment by NexiusTailer** [comment]
Show your code where you spawn players, which also causes the problem in a blank gamemode.

**Comment by babab4757** [comment]
public OnPlayerSpawn(playerid) {

	//melodie
	StopAudioStreamForPlayer( playerid ); // Oprim muzica pe care am pus-o la OnPlayerConnect.
	//________

	new string[150];
	if(SpawnedCarYT[playerid] == 1) { DestroyDynamicObject(nameobject[YouTuberCar[playerid]]), DestroyVehicle(YouTuberCar[playerid]), SpawnedCarYT[playerid] = 0; }
	if(PlayerInfo[playerid][pShowBanca] == 1) {
		format(string, sizeof(string), "$%s", GetBankMoney(playerid));
		PlayerTextDrawSetString(playerid, BancaTD, string);
		PlayerTextDrawShow(playerid, BancaTD);
	}
	if(PlayerInfo[playerid][pSecuroServ] != 0) {
		Update3DTextLabelText(securolable[playerid], 0x00C3FFFF, "{FF0000}Securo{1BAB00}Serv");
		Attach3DTextLabelToPlayer(securolable[playerid], playerid, 0.0, 0.0, 0.7);
	}
	if(PlayerInfo[playerid][pYouTuber] != 0) {
		Update3DTextLabelText(ytlable[playerid], 0x00C3FFFF, "{FFFFFF}You{FF0000}Tuber");
		Attach3DTextLabelToPlayer(ytlable[playerid], playerid, 0.0, 0.0, 0.5);
	}
	if(PlayerInfo[playerid][pReborn] != 0) {
		Update3DTextLabelText(RebornLabel[playerid], 0x00C3FFFF, "REBORN");
		Attach3DTextLabelToPlayer(RebornLabel[playerid], playerid, 0.0, 0.0, 0.9);
	}
   	Update3DTextLabelText(vipLabel[playerid], -1, "");
   	Update3DTextLabelText(RebornLabel[playerid], -1, "");
   	Update3DTextLabelText(securolable[playerid], -1, "");
   	if(PlayerInfo[playerid][pVip] != 0) {
	   	switch(PlayerInfo[playerid][pVip]) {
	   		case 1: Update3DTextLabelText(vipLabel[playerid], 0x7DE41BFF, "VIP USER");
	   		case 2: Update3DTextLabelText(vipLabel[playerid], 0xF28036FF, "VIP USER");
	   		case 3: Update3DTextLabelText(vipLabel[playerid], 0xDF2626FF, "VIP USER");
	   	}
	    Attach3DTextLabelToPlayer(vipLabel[playerid], playerid, 0.0, 0.0, 0.4);
	}
	TextDrawShowForPlayer(playerid, DataT[0]);
	TextDrawShowForPlayer(playerid, DataT[1]);
	TextDrawShowForPlayer(playerid, DataT[2]);
	if(Escape[playerid] == 1) FailEscape(playerid);
	playerKills[playerid] = 0;
	for(new i = 0; i < 3; i++) PlayerTextDrawHide(playerid, SpeedometerPTD[i]);
	Update3DTextLabelText(deathLabel[playerid], -1, "");
	SetPlayerWeather(playerid, 0);
	Undita[playerid] = 0;
	Momeala[playerid] = 0;
	ResetWeapons(playerid);
	SetPlayerWorldBounds(playerid, 20000.0000, -20000.0000, 20000.0000, -20000.0000);
	StopAudioStreamForPlayer(playerid);
	SetPlayerHealthEx(playerid, 99);
    SetPlayerArmourEx(playerid, 0);
    SetPlayerWantedLevel(playerid, PlayerInfo[playerid][pWantedLevel]);
    SetPlayerScore(playerid, PlayerInfo[playerid][pLevel]);
	SetPlayerToTeamColor(playerid);
	SetPlayerTeam(playerid,4);
	InTraining[playerid] = 0;
	SetPVarInt(playerid,"KilledFlood",0);
	Armour[playerid] = 0;
	SetPVarInt(playerid, "Armour", 0);
	DisableRemoteVehicleCollisions(playerid, 0);
	TurfTime[playerid] = 0;
    HaveBag[playerid] = 0;
    Freezed[playerid] = 0;
	PlayRadio[playerid] = 0;
	InEvent[playerid] = 0;
	playerDeath[playerid] = -1;
	//AntiDeAMX();
	if(InExamen[playerid] == 1) FailExamen(playerid);
	if(PlayerInfo[playerid][pPetStatus] == 1) {
		SetPlayerAttachedObject(playerid, 6, 19078, 17, 0.021065, -0.100726, 0.143000, 357.120239, 1.712298, 349.232513, 1.000000, 1.000000, 1.120420);
        if(petstatusv[playerid] == 0) {
			format(string, sizeof(string), "{F08A23}Pet level.{EA2323}%d - %s",PlayerInfo[playerid][pPetLevel], PlayerInfo[playerid][pPetName]);
			Pet[playerid] = CreateDynamic3DTextLabel(string, 0xFFFFFF00, 357.120239, 1.712298, 349.232513, 20, playerid);
			petstatusv[playerid] ++;
		}
	}
	if(FreezeTime[playerid] != 0) TogglePlayerControllable(playerid, 0);
	if(GetPVarInt(playerid, "InLesson") != -1) {
		new id = GetPVarInt(playerid, "InLesson");
		format(string, sizeof(string), "Lectia a fost anulata deoarece %s a murit.", GetName(playerid));
		SCM(id, COLOR_LIGHTBLUE,string);
		SCM(playerid, COLOR_LIGHTBLUE, "Lectie anulata!");
		SetPVarInt(id, "InLesson", -1);
		SetPVarInt(playerid, "InLesson", -1);
	}
    foreach(Player, i) {
		if(Spectate[i] == playerid) {
			TogglePlayerSpectating(i, 1);
			SetPlayerInterior(i, GetPlayerInterior(playerid));
			SetPlayerVirtualWorld(i, GetPlayerVirtualWorld(playerid));
			PlayerSpectatePlayer(i, playerid);
		}
	}
	if(gDice[playerid] == 1) SCM(playerid, -1, "Ai pierdut zarurile."), gDice[playerid] = 0;
	if(PlayerInfo[playerid][pGlasses] > 0 && PlayerInfo[playerid][pShowGlasses] == 1) {
		new skin = PlayerInfo[playerid][pChar];
		if(skin < 300) SetPlayerHoldingObject(playerid, PlayerInfo[playerid][pGlasses], 2, SkinOffSet[skin][0], SkinOffSet[skin][1], SkinOffSet[skin][2], SkinOffSet[skin][3], SkinOffSet[skin][4], SkinOffSet[skin][5]);
	}
	if(InRob[playerid] == 1) FailRob(playerid, "Ai fost omorat");
	if(JobWorking[playerid] == 1) {
		JobWorking[playerid] = 0;
		PlayerTextDrawHide(playerid, JobTD);
		if(JobVehicle[playerid] != 0) { DestroyVehicle(JobVehicle[playerid]); JobVehicle[playerid] = 0; }
		if(Trailer[playerid] != 0) { DestroyVehicle(Trailer[playerid]); Trailer[playerid] = 0; }
		PlayerTextDrawHide(playerid, InfosTD);
		DisablePlayerCheckpointEx(playerid);
		CP[playerid] = 0;
		JobVehicle[playerid] = 0;
		DisablePlayerRaceCheckpointEx(playerid);
		RemovePlayerAttachedObject(playerid, 2);
	}
	if(CP[playerid] == 51) {
		SCM(playerid, -1, "Ai pierdut sacul cu faina.");
		CP[playerid] = 0;
		KG[playerid] = 0;
		DisablePlayerCheckpointEx(playerid);
		if(PlayerInfo[playerid][pJob] == 1) PlayerInfo[playerid][pShowJob] = 0;
	}
	if(HaveFish[0][playerid] != 0) {
	    SCM(playerid, -1, "Ai pierdut pestele!");
		HaveFish[0][playerid] = 0;
		HaveFish[1][playerid] = 0;
		DisablePlayerCheckpointEx(playerid);
	}
	if(PlayerInfo[playerid][pShowHud] == 0) {
		show_logo(playerid);
	}

	if(UsedFly[playerid] == 1) {
		StopFly(playerid);
		UsedFly[playerid] = 0;
	}
	if(InShop[playerid] == 1) {
	    new carid = pCarID[playerid];
    	SetCameraBehindPlayer(playerid), SetPlayerInterior(playerid, pInteriorID[playerid]), SetVehiclePosEx(playerid, carid, pPos[playerid][0], pPos[playerid][1], pPos[playerid][2]);
		SetPlayerVirtualWorld(playerid, 0);
		SetVehicleVirtualWorld(carid, 0);
		TextDrawHideForPlayer(playerid, HiddTD[0]);
		TextDrawHideForPlayer(playerid, HiddTD[1]);
		TextDrawHideForPlayer(playerid, HiddTD[2]);
		TextDrawHideForPlayer(playerid, HiddTD[3]);
		TextDrawHideForPlayer(playerid, HiddTD[4]);
		PlayerTextDrawHide(playerid, HiddTDs[0]);
		PlayerTextDrawHide(playerid, HiddTDs[1]);
		PlayerTextDrawHide(playerid, HiddTDs[2]);
		CancelSelectTextDraw(playerid);
		InShop[playerid] = 0;
	}
	if(InDealer[playerid] >= 1) {
		stop CancelTestDrive(playerid);
		CancelDriveTest(playerid);
	}
	if(StartedSpray[playerid] == 1 || ClanDuty[playerid] == 1) {
		SCM(playerid, COLOR_ERROR, "Eroare: {FFFFFF}Nu mai esti la datoria clanului!");
		GraffitiInfo[StartedSpray2[playerid]][gfAttacked] = 0;
		StartedSpray[playerid] = 0;
		StartedSpray2[playerid] = 0;
		StartedSprayOn[playerid] = 0;
		ClanProces[playerid] = 0;
		ClanDuty[playerid] = 0;
		GraffitiInfo[StartedSprayOn[playerid]][gfAttacked] = 0;
	}
	if(!gPlayerAnimLibsPreloaded[playerid]) {
   		PreloadAnimLib(playerid,"BOMBER");
   		PreloadAnimLib(playerid,"RAPPING");
    	PreloadAnimLib(playerid,"SHOP");
   		PreloadAnimLib(playerid,"BEACH");
   		PreloadAnimLib(playerid,"SMOKING");
    	PreloadAnimLib(playerid,"FOOD");
    	PreloadAnimLib(playerid,"ON_LOOKERS");
    	PreloadAnimLib(playerid,"DEALER");
    	PreloadAnimLib(playerid,"MISC");
    	PreloadAnimLib(playerid,"SWEET");
    	PreloadAnimLib(playerid,"RIOT");
    	PreloadAnimLib(playerid,"PED");
    	PreloadAnimLib(playerid,"POLICE");
		PreloadAnimLib(playerid,"CRACK");
		PreloadAnimLib(playerid,"CARRY");
		PreloadAnimLib(playerid,"COP_AMBIENT");
		PreloadAnimLib(playerid,"PARK");
		PreloadAnimLib(playerid,"INT_HOUSE");
		PreloadAnimLib(playerid,"FOOD");
		gPlayerAnimLibsPreloaded[playerid] = 1;
	}
	gTeam[playerid] = PlayerInfo[playerid][pTeam];
	if(gTeam[playerid] == 4) gTeam[playerid] = 4;
	if(PlayerInfo[playerid][pMember] == 1 || PlayerInfo[playerid][pLeader] == 1 || PlayerInfo[playerid][pMember] == 2 || PlayerInfo[playerid][pLeader] == 2 || PlayerInfo[playerid][pMember] == 3 || PlayerInfo[playerid][pLeader] == 3) {
		gTeam[playerid] = 2;
		PlayerInfo[playerid][pTeam] = 2;
	}
	if(IsPlayerLogged[playerid] == 0) {
    	SCM(playerid, COLOR_WARNING, "* Ai primit kick deoarece nu te-ai logat.");
    	KickEx(playerid);
		return true;
 	}
	if(PaintType[playerid] != 0) return PaintSpawn(playerid);
	if(OnDuty[playerid] == 1 && IsACop(playerid)) {
		ServerWeapon(playerid, 24, 500);
		ServerWeapon(playerid, 3, 0);
		ServerWeapon(playerid, 41, 500);
		ServerWeapon(playerid, 29, 1000);
		ServerWeapon(playerid, 31, 1000);
		SetPlayerArmourEx(playerid, 99);
		SetPlayerHealthEx(playerid, 99);
	}
	if(PlayerInfo[playerid][pBackpack] == 2) SetPlayerAttachedObject(playerid, 8, 3026, 1, -0.172813, -0.112569, -0.022387, 0.000000, 0.000000, 3.390071, 1.000000, 1.000000, 1.130721);
	SetPlayerSpawn(playerid);
	if(GetPVarInt(playerid, "Cover") == 1) {
		SetPlayerColor(playerid, -1);
		SetPlayerColor(playerid, COLOR_WHITE);
		SetPlayerScore(playerid, 1+random(2));
		SetPlayerSkinEx(playerid, 1+random(100));
		SCM(playerid, COLOR_YELLOW, "Esti sub acoperire!");
	}
	return true;
}

**Comment by babab4757** [comment]
it's a quite long code

**Comment by babab4757** [comment]
> Show your code where you spawn players, which also causes the problem in a blank gamemode so I could test & debug it too.

public OnPlayerSpawn(playerid) {

//melodie
StopAudioStreamForPlayer( playerid ); // Oprim muzica pe care am pus-o la OnPlayerConnect.
//________

new string[150];
if(SpawnedCarYT[playerid] == 1) { DestroyDynamicObject(nameobject[YouTuberCar[playerid]]), DestroyVehicle(YouTuberCar[playerid]), SpawnedCarYT[playerid] = 0; }
if(PlayerInfo[playerid][pShowBanca] == 1) {
	format(string, sizeof(string), "$%s", GetBankMoney(playerid));
	PlayerTextDrawSetString(playerid, BancaTD, string);
	PlayerTextDrawShow(playerid, BancaTD);
}
if(PlayerInfo[playerid][pSecuroServ] != 0) {
	Update3DTextLabelText(securolable[playerid], 0x00C3FFFF, "{FF0000}Securo{1BAB00}Serv");
	Attach3DTextLabelToPlayer(securolable[playerid], playerid, 0.0, 0.0, 0.7);
}
if(PlayerInfo[playerid][pYouTuber] != 0) {
	Update3DTextLabelText(ytlable[playerid], 0x00C3FFFF, "{FFFFFF}You{FF0000}Tuber");
	Attach3DTextLabelToPlayer(ytlable[playerid], playerid, 0.0, 0.0, 0.5);
}
if(PlayerInfo[playerid][pReborn] != 0) {
	Update3DTextLabelText(RebornLabel[playerid], 0x00C3FFFF, "REBORN");
	Attach3DTextLabelToPlayer(RebornLabel[playerid], playerid, 0.0, 0.0, 0.9);
}
Update3DTextLabelText(vipLabel[playerid], -1, "");
Update3DTextLabelText(RebornLabel[playerid], -1, "");
Update3DTextLabelText(securolable[playerid], -1, "");
if(PlayerInfo[playerid][pVip] != 0) {
   	switch(PlayerInfo[playerid][pVip]) {
   		case 1: Update3DTextLabelText(vipLabel[playerid], 0x7DE41BFF, "VIP USER");
   		case 2: Update3DTextLabelText(vipLabel[playerid], 0xF28036FF, "VIP USER");
   		case 3: Update3DTextLabelText(vipLabel[playerid], 0xDF2626FF, "VIP USER");
   	}
    Attach3DTextLabelToPlayer(vipLabel[playerid], playerid, 0.0, 0.0, 0.4);
}
TextDrawShowForPlayer(playerid, DataT[0]);
TextDrawShowForPlayer(playerid, DataT[1]);
TextDrawShowForPlayer(playerid, DataT[2]);
if(Escape[playerid] == 1) FailEscape(playerid);
playerKills[playerid] = 0;
for(new i = 0; i < 3; i++) PlayerTextDrawHide(playerid, SpeedometerPTD[i]);
Update3DTextLabelText(deathLabel[playerid], -1, "");
SetPlayerWeather(playerid, 0);
Undita[playerid] = 0;
Momeala[playerid] = 0;
ResetWeapons(playerid);
SetPlayerWorldBounds(playerid, 20000.0000, -20000.0000, 20000.0000, -20000.0000);
StopAudioStreamForPlayer(playerid);
SetPlayerHealthEx(playerid, 99);
SetPlayerArmourEx(playerid, 0);
SetPlayerWantedLevel(playerid, PlayerInfo[playerid][pWantedLevel]);
SetPlayerScore(playerid, PlayerInfo[playerid][pLevel]);
SetPlayerToTeamColor(playerid);
SetPlayerTeam(playerid,4);
InTraining[playerid] = 0;
SetPVarInt(playerid,"KilledFlood",0);
Armour[playerid] = 0;
SetPVarInt(playerid, "Armour", 0);
DisableRemoteVehicleCollisions(playerid, 0);
TurfTime[playerid] = 0;
HaveBag[playerid] = 0;
Freezed[playerid] = 0;
PlayRadio[playerid] = 0;
InEvent[playerid] = 0;
playerDeath[playerid] = -1;
//AntiDeAMX();
if(InExamen[playerid] == 1) FailExamen(playerid);
if(PlayerInfo[playerid][pPetStatus] == 1) {
	SetPlayerAttachedObject(playerid, 6, 19078, 17, 0.021065, -0.100726, 0.143000, 357.120239, 1.712298, 349.232513, 1.000000, 1.000000, 1.120420);
    if(petstatusv[playerid] == 0) {
		format(string, sizeof(string), "{F08A23}Pet level.{EA2323}%d - %s",PlayerInfo[playerid][pPetLevel], PlayerInfo[playerid][pPetName]);
		Pet[playerid] = CreateDynamic3DTextLabel(string, 0xFFFFFF00, 357.120239, 1.712298, 349.232513, 20, playerid);
		petstatusv[playerid] ++;
	}
}
if(FreezeTime[playerid] != 0) TogglePlayerControllable(playerid, 0);
if(GetPVarInt(playerid, "InLesson") != -1) {
	new id = GetPVarInt(playerid, "InLesson");
	format(string, sizeof(string), "Lectia a fost anulata deoarece %s a murit.", GetName(playerid));
	SCM(id, COLOR_LIGHTBLUE,string);
	SCM(playerid, COLOR_LIGHTBLUE, "Lectie anulata!");
	SetPVarInt(id, "InLesson", -1);
	SetPVarInt(playerid, "InLesson", -1);
}
foreach(Player, i) {
	if(Spectate[i] == playerid) {
		TogglePlayerSpectating(i, 1);
		SetPlayerInterior(i, GetPlayerInterior(playerid));
		SetPlayerVirtualWorld(i, GetPlayerVirtualWorld(playerid));
		PlayerSpectatePlayer(i, playerid);
	}
}
if(gDice[playerid] == 1) SCM(playerid, -1, "Ai pierdut zarurile."), gDice[playerid] = 0;
if(PlayerInfo[playerid][pGlasses] > 0 && PlayerInfo[playerid][pShowGlasses] == 1) {
	new skin = PlayerInfo[playerid][pChar];
	if(skin < 300) SetPlayerHoldingObject(playerid, PlayerInfo[playerid][pGlasses], 2, SkinOffSet[skin][0], SkinOffSet[skin][1], SkinOffSet[skin][2], SkinOffSet[skin][3], SkinOffSet[skin][4], SkinOffSet[skin][5]);
}
if(InRob[playerid] == 1) FailRob(playerid, "Ai fost omorat");
if(JobWorking[playerid] == 1) {
	JobWorking[playerid] = 0;
	PlayerTextDrawHide(playerid, JobTD);
	if(JobVehicle[playerid] != 0) { DestroyVehicle(JobVehicle[playerid]); JobVehicle[playerid] = 0; }
	if(Trailer[playerid] != 0) { DestroyVehicle(Trailer[playerid]); Trailer[playerid] = 0; }
	PlayerTextDrawHide(playerid, InfosTD);
	DisablePlayerCheckpointEx(playerid);
	CP[playerid] = 0;
	JobVehicle[playerid] = 0;
	DisablePlayerRaceCheckpointEx(playerid);
	RemovePlayerAttachedObject(playerid, 2);
}
if(CP[playerid] == 51) {
	SCM(playerid, -1, "Ai pierdut sacul cu faina.");
	CP[playerid] = 0;
	KG[playerid] = 0;
	DisablePlayerCheckpointEx(playerid);
	if(PlayerInfo[playerid][pJob] == 1) PlayerInfo[playerid][pShowJob] = 0;
}
if(HaveFish[0][playerid] != 0) {
    SCM(playerid, -1, "Ai pierdut pestele!");
	HaveFish[0][playerid] = 0;
	HaveFish[1][playerid] = 0;
	DisablePlayerCheckpointEx(playerid);
}
if(PlayerInfo[playerid][pShowHud] == 0) {
	show_logo(playerid);
}

if(UsedFly[playerid] == 1) {
	StopFly(playerid);
	UsedFly[playerid] = 0;
}
if(InShop[playerid] == 1) {
    new carid = pCarID[playerid];
	SetCameraBehindPlayer(playerid), SetPlayerInterior(playerid, pInteriorID[playerid]), SetVehiclePosEx(playerid, carid, pPos[playerid][0], pPos[playerid][1], pPos[playerid][2]);
	SetPlayerVirtualWorld(playerid, 0);
	SetVehicleVirtualWorld(carid, 0);
	TextDrawHideForPlayer(playerid, HiddTD[0]);
	TextDrawHideForPlayer(playerid, HiddTD[1]);
	TextDrawHideForPlayer(playerid, HiddTD[2]);
	TextDrawHideForPlayer(playerid, HiddTD[3]);
	TextDrawHideForPlayer(playerid, HiddTD[4]);
	PlayerTextDrawHide(playerid, HiddTDs[0]);
	PlayerTextDrawHide(playerid, HiddTDs[1]);
	PlayerTextDrawHide(playerid, HiddTDs[2]);
	CancelSelectTextDraw(playerid);
	InShop[playerid] = 0;
}
if(InDealer[playerid] >= 1) {
	stop CancelTestDrive(playerid);
	CancelDriveTest(playerid);
}
if(StartedSpray[playerid] == 1 || ClanDuty[playerid] == 1) {
	SCM(playerid, COLOR_ERROR, "Eroare: {FFFFFF}Nu mai esti la datoria clanului!");
	GraffitiInfo[StartedSpray2[playerid]][gfAttacked] = 0;
	StartedSpray[playerid] = 0;
	StartedSpray2[playerid] = 0;
	StartedSprayOn[playerid] = 0;
	ClanProces[playerid] = 0;
	ClanDuty[playerid] = 0;
	GraffitiInfo[StartedSprayOn[playerid]][gfAttacked] = 0;
}
if(!gPlayerAnimLibsPreloaded[playerid]) {
	PreloadAnimLib(playerid,"BOMBER");
	PreloadAnimLib(playerid,"RAPPING");
	PreloadAnimLib(playerid,"SHOP");
	PreloadAnimLib(playerid,"BEACH");
	PreloadAnimLib(playerid,"SMOKING");
	PreloadAnimLib(playerid,"FOOD");
	PreloadAnimLib(playerid,"ON_LOOKERS");
	PreloadAnimLib(playerid,"DEALER");
	PreloadAnimLib(playerid,"MISC");
	PreloadAnimLib(playerid,"SWEET");
	PreloadAnimLib(playerid,"RIOT");
	PreloadAnimLib(playerid,"PED");
	PreloadAnimLib(playerid,"POLICE");
	PreloadAnimLib(playerid,"CRACK");
	PreloadAnimLib(playerid,"CARRY");
	PreloadAnimLib(playerid,"COP_AMBIENT");
	PreloadAnimLib(playerid,"PARK");
	PreloadAnimLib(playerid,"INT_HOUSE");
	PreloadAnimLib(playerid,"FOOD");
	gPlayerAnimLibsPreloaded[playerid] = 1;
}
gTeam[playerid] = PlayerInfo[playerid][pTeam];
if(gTeam[playerid] == 4) gTeam[playerid] = 4;
if(PlayerInfo[playerid][pMember] == 1 || PlayerInfo[playerid][pLeader] == 1 || PlayerInfo[playerid][pMember] == 2 || PlayerInfo[playerid][pLeader] == 2 || PlayerInfo[playerid][pMember] == 3 || PlayerInfo[playerid][pLeader] == 3) {
	gTeam[playerid] = 2;
	PlayerInfo[playerid][pTeam] = 2;
}
if(IsPlayerLogged[playerid] == 0) {
	SCM(playerid, COLOR_WARNING, "* Ai primit kick deoarece nu te-ai logat.");
	KickEx(playerid);
	return true;
}
if(PaintType[playerid] != 0) return PaintSpawn(playerid);
if(OnDuty[playerid] == 1 && IsACop(playerid)) {
	ServerWeapon(playerid, 24, 500);
	ServerWeapon(playerid, 3, 0);
	ServerWeapon(playerid, 41, 500);
	ServerWeapon(playerid, 29, 1000);
	ServerWeapon(playerid, 31, 1000);
	SetPlayerArmourEx(playerid, 99);
	SetPlayerHealthEx(playerid, 99);
}
if(PlayerInfo[playerid][pBackpack] == 2) SetPlayerAttachedObject(playerid, 8, 3026, 1, -0.172813, -0.112569, -0.022387, 0.000000, 0.000000, 3.390071, 1.000000, 1.000000, 1.130721);
SetPlayerSpawn(playerid);
if(GetPVarInt(playerid, "Cover") == 1) {
	SetPlayerColor(playerid, -1);
	SetPlayerColor(playerid, COLOR_WHITE);
	SetPlayerScore(playerid, 1+random(2));
	SetPlayerSkinEx(playerid, 1+random(100));
	SCM(playerid, COLOR_YELLOW, "Esti sub acoperire!");
}
return true;
}

**Comment by NexiusTailer** [comment]
Can't reproduce anything similar

**Comment by babab4757** [comment]
> Can't reproduce anything similar

i deleted the teleport anticheat. but now im removing the speedhack and surfly hack because admins also get kicked

**Comment by babab4757** [comment]
> Can't reproduce anything similar

but it's also difficult because i dont know how you labled them

**Comment by NexiusTailer** [comment]
> > Can't reproduce anything similar
> 
> i deleted the teleport anticheat. but now im removing the speedhack and surfly hack because admins also get kicked

This is not the solution

**Comment by babab4757** [comment]
> > > Can't reproduce anything similar
> > 
> > 
> > i deleted the teleport anticheat. but now im removing the speedhack and surfly hack because admins also get kicked
> 
> This is not the solution

whatelse can i do if even you (the creator) can not reproduce anything similar

**Comment by NexiusTailer** [comment]
Well you can at least make sure that you provide me a minimal **working** code (i.e. with which the problem is reproducible) on a blank test mode from your side, and not just cut out the entire public with a bunch of custom functions that you have not attached.
