### ISSUE TITLE
support

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#229]
I activate anti dialog hack

I get kicked in every dialog due to dialog hack

unnecessary throwing in dialogs How can I fix

Kick case cod : 39(anti dialog hack)

**Comment by NexiusTailer** [comment]
> How can I fix
[RTFM](https://github.com/NexiusTailer/Nex-AC/blob/master/README.md) and make sure you included the anticheat in each filterscript (with "#define FILTERSCRIPT" before that of course) in case you have any FSes. Also make sure you don't have redefines for ShowPlayerDialog function. If you have such code, change these redefines into ALS Hook Method 7 so it would be able to process the whole hook-chain.

**Comment by nex693** [comment]
Okay, thank.

pawn.raknet security error Is there an update about.

**Comment by NexiusTailer** [comment]
There no any known security errors

**Comment by nex693** [comment]
https://github.com/f0Re3t/nex-ac_rakcheat/issues/14

**Comment by NexiusTailer** [comment]
> [f0Re3t/nex-ac_rakcheat#14](https://github.com/f0Re3t/nex-ac_rakcheat/issues/14)

There are no any specific information about it so this statement quite useless at the moment

**Comment by nex693** [comment]
Security bug  : everyone weapon back expelled due to

**Comment by nex693** [comment]
Security error made with s0b

 Everyone fps 6

**Comment by NexiusTailer** [comment]
Can only say the same:
https://github.com/NexiusTailer/Nex-AC/issues/229#issuecomment-877709966

**Comment by nex693** [comment]
Security errors I will gather information about

Thank You NexiuS

**Comment by nex693** [comment]
I will ask one last thing, do I need to use Pawn.raknet?
what's wrong with nex-ac
Isn't it enough on its own?

**Comment by NexiusTailer** [comment]
Pawn.RakNet-dependent code in the anticheat have access to some extended sync data which cannot be obtained via default SA-MP natives and callbacks, unfortunately.
