### ISSUE TITLE
[bugfix]: OnPlayerTakeDamage should return 0 by default

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#23]
In  ``Nex-AC/src/v1.9/v1.9.22/r2/nex-ac.inc`` ,
Starting at line 3059
```
	if(ACInfo[playerid][acKicked]) return 0;
	ACInfo[playerid][acDeathRes] = true;
	#if !defined _inc_y_hooks && !defined _INC_y_hooks\
		&& defined ac_OnPlayerTakeDamage
		return ac_OnPlayerTakeDamage(playerid, issuerid, amount, weaponid, bodypart);
	#else
		return 1;
	#endif
```
Should be :
```
	if(ACInfo[playerid][acKicked]) return 1;
	ACInfo[playerid][acDeathRes] = true;
	#if !defined _inc_y_hooks && !defined _INC_y_hooks\
		&& defined ac_OnPlayerTakeDamage
		return ac_OnPlayerTakeDamage(playerid, issuerid, amount, weaponid, bodypart);
	#else
		return 0;
	#endif
```

Default value for function OnPlayerTakeDamage is 0 not 1.

Thank you,
rt-2

**Comment by NexiusTailer** [comment]
Ok I checked it again and even with the return value '1' from filterscript, it was called from gamemode after that. And since anticheat uses this public only when it's included in gamemode and OnPlayerTakeDamage is called the last from gamemode too, there should not be any problems.

**Comment by rt-2** [comment]
Honestly from all of those, the first problem came from OnDialogResponse, and I just went and fixed all that were not conventional, I think you should keep them conventional to avoid any possible bug.
rt-2

**Comment by NexiusTailer** [comment]
Can you describe your problem in more detail (when was "return 1;")? Because when I try to check returns in this public, everything is fine, like:
> [First] Call OnDialogResponse from FS with "return 1;"
> [Second] Call OnDialogResponse from GM with "return 1;" [Success! Even though I paste "return 1;" in FS that called first]

So it seems to me that the documentation for these public is not very accurate

**Comment by rt-2** [comment]
Honestly this language is not even stable in my opinion, buy one of my filter script did not receive any call to OnDialogResponse with the old method, so my inventory just didn't work.
I simply applied the modifications here: https://github.com/NexiusTailer/Nex-AC/issues/24
And it worked just like before.
