### ISSUE TITLE
AC kick

### ISSUE THREAD

**Issue by maradona4** [NexiusTailer/Nex-AC#231]
How to disable anti cheat by unkicked RCON admin?

**Comment by rt-2** [comment]
You need to use `EnableAntiCheat(code, toggle)`
https://github.com/NexiusTailer/Nex-AC#enableanticheatcode-enable

**Comment by maradona4** [comment]
How using? 

CMD:disac(playerid, params[])
{
	LevelAdmin(playerid, 2);
	EnableAntiCheat[playerid] = 0;
	return 1;
}

i thnk my error compiler

**Comment by rt-2** [comment]
It needs to be in the root of your gamemode, after including nex-ac.

This is the syntax you need (for Anti-Rcon hack):
```
#include <nex-ac>

EnableAntiCheat(42, 0); //42 Anti-Rcon hack

CMD:disac(playerid, params[])
{
  LevelAdmin(playerid, 2);
  return 1;
}
```

**Comment by rt-2** [comment]
If you only want to do it for 1 player, you need this syntax and don't forget to reactivate when players login like so:
```
#include <nex-ac>

public OnPlayerConnect(playerid)
{
  EnableAntiCheatForPlayer(playerid, 42, 1); //42 Anti-Rcon hack
  return 1;
}

CMD:disac(playerid, params[])
{
  EnableAntiCheatForPlayer(playerid, 42, 0); //42 Anti-Rcon hack
  LevelAdmin(playerid, 2);
  return 1;
}
```

**Comment by maradona4** [comment]
Ok Thank
