### ISSUE TITLE
Console Debug SPAM

### ISSUE THREAD

**Issue by maradona4** [NexiusTailer/Nex-AC#232]
![image](https://user-images.githubusercontent.com/44541791/127563236-c6fadfda-ac3f-4185-84f6-e07ea4cfc2e7.png)

me using /rcon login 123
Me ADMIN

Anti cheat no kick "ok"

because debug spam anti cheat? ;-; how disable debug for adm

**Comment by NexiusTailer** [comment]
Well, there are a few things you can do in your case:
1. You can just disable all needed anticheats for admins, so it will not check the administration, and as a result, there will be no detections on them at all (use [EnableAntiCheatForPlayer](https://github.com/NexiusTailer/Nex-AC#enableanticheatforplayerplayerid-code-enable) in all places when player gets admin rights)
2. You can disable only [Nex-AC debug] logging, so all anticheats will remain enabled and continue to work, but there will be no detailed information about this in the logs (comment "#define DEBUG" line in the anticheat)

**Comment by maradona4** [comment]
ok, thank
