### ISSUE TITLE
Packet was modified, sent by id:

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#233]
Hello Nexius,

Packet was modified, sent by id: 8, ip: 213.230.102.216:34015
Packet was modified, sent by id: 15, ip: 31.40.27.214:58825
Packet was modified, sent by id: 40, ip: 213.230.95.146:62509
Packet was modified, sent by id: 8, ip: 213.230.102.216:34015
Packet was modified, sent by id: 15, ip: 31.40.27.214:58825
Packet was modified, sent by id: 40, ip: 213.230.95.146:62509

what is this?

**Comment by elvianod982** [comment]
That has nothing to do with Nex-AC. 

```
'Packet was modified'
The error commonly shown as:
[hh:mm:ss] Packet was modified, sent by id: <id>, ip: <ip>:<port>
happens when a player times out or is currently having connection issues.
```
https://team.sa-mp.com/wiki/Common_Problems.html#.27Packet_was_modified.27

**Comment by nex693** [comment]
I don't know how to solve

**Comment by elvianod982** [comment]
There is nothing you can do to solve clients that are having connection issues. That's on the player to fix - not the server operator.

**Comment by NexiusTailer** [comment]
AFAIK, the cause of the problem can be expressed in an incorrectly configured firewall too, which filters out part of the game traffic (and this can be either a firewall problem of a specific player, or a problem in the firewall of the system on which the server is running - in that case I should have got many "packet was modified" messages for **different** players at the same time).

**Comment by NexiusTailer** [comment]
But it's still most likely that the player just has a bad network connection.
