### ISSUE TITLE
On-foot speed hacks

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#235]
I noticed that on-foot speed hacks are sometimes not detected.

In this video, we see a player at high speed (64 MPH) for 14 seconds without detection: https://www.youtube.com/watch?v=1lnHlxyiRfY

Is there anything that can be done to improve the anti-cheat for such cases?

**Comment by NexiusTailer** [comment]
Which velocity he sends? MPH can be calculated by different formulas with different multipliers and your values may differ from the same in anticheat. One thing is for sure, the cheater throughout the entire video doesn't exceed the maximum onfoot speed limits (even calculating only from x/y axis)

**Comment by elvianod982** [comment]
> Which velocity he sends?

How would I retrieve this information?

**Comment by NexiusTailer** [comment]
> > Which velocity he sends?
> 
> How would I retrieve this information?

Try to log it (by some admin command, for example) when you know that a cheaters just started his actions and you're sure this is exactly that cheat.
