### ISSUE TITLE
Fly/airbrake hacks

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#236]
Not sure if this is a fly hack or airbrake... at times it's a cross between the two.

https://www.youtube.com/watch?v=GLT5aMgZ7Fw

Nex-AC wasn't able to detect it (with nothing logged to the server_log.txt either).

**Comment by NexiusTailer** [comment]
Looks like flyhack which works like some slow coordmasters (sends some minimal velocity not to be detected by anti-airbreak or anti-teleport).

**Comment by nex693** [comment]
Anti Fly,Airbreak should be developed...

**Comment by NexiusTailer** [comment]
> Anti Fly,Airbreak should be developed...

It's already developed...

**Comment by elvianod982** [comment]
> Looks like flyhack which works like some slow coordmasters (sends some minimal velocity not to be detected by anti-airbreak or anti-teleport).

So, can something be done about it?

**Comment by NexiusTailer** [comment]
If it sends pretty short distance and pretty high speed, there are no reliable ways to constantly detect it (as it can make its dist lower and lower, and its speed higher and higher in the same time in future iterations). But for now, we can get that dist & velocity values to be able to set more hard restrictions.
