### ISSUE TITLE
Vehicle fly hacks

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#237]
This fly car cheat went undetected for at least 19 seconds: https://www.youtube.com/watch?v=B1e150iJRbg

Can anything be done to combat this?

**Comment by NexiusTailer** [comment]
Anticheat detects flyhack in vehicle only in cases of vertical climb (when vehicle flies up like a helicopter). Other cases would give false detections for stunting and things like that. Unfortunately.
