### ISSUE TITLE
OnFloodWarning

### ISSUE THREAD

**Issue by kolor4do** [NexiusTailer/Nex-AC#241]
This callback is called many times, do I need to worry about that?

I noticed that it is called in `OnPlayerRequestClass` and sometimes in `OnDialogResponse`

![image](https://user-images.githubusercontent.com/61595463/133932320-f5473553-8472-4ba0-a5fe-7b12bf91177f.png)

**Comment by NexiusTailer** [comment]
If you don't declare this callback in your scripts, it's not used at all:
![image](https://user-images.githubusercontent.com/13169094/133933536-5f585229-b22e-45c8-8ed1-c5973f2aefeb.png)
(just like OnCheatWarning and OnNOPWarning, by the way)

So if you really need it for some testing purposes, but don't need it on your main server, you can use OnCheatDetected only.

**Comment by kolor4do** [comment]
ok, thanks
