### ISSUE TITLE
[Resolved] Tag mismatch warnings (expected tag "bool", but found none)

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#243]
Hi,
When I use `AddStaticVehicleEx` it gives me this warning:
```
C:\Users\rt-2\Desktop\SAARP\SAMP\pawno\include\nex-ac.inc(2080) : warning 213: tag mismatch: expected tag "bool", but found none ("_")
```

this is the code that triggers the warning, if I remove this particular function from that line, the warning disappear:
```
new vehicleid = AddStaticVehicleEx(strval(vehid), floatstr(pos_x), floatstr(pos_y), floatstr(pos_z), floatstr(pos_angle), strval(color1), strval(color2), -1, addsiren);
```

* `addsiren` is an int.
* AC version is v1.9.56

Thank you,
rt-2

EDIT: Solution is to ignore the warning, this is still stable because bitwise, bool will act the same as int.

**Comment by NexiusTailer** [comment]
'addsiren' is an int in default sa-mp includes too, but if you use latest YSI (or any other libraries, idk exactly what else behaves the same for now) - you'll see such warnings. Regarding the problem itself, most likely such scripts also hooks some natives and modify their arguments in accordance with how it is possible now declared in the modified samp includes, thereby creating these compilation problems.

So, there is nothing I could do about it if we say in the context of the fact that anticheat still primarily supports standard (canonical) samp includes, and not modified ones. I think this is a problem with YSI and all similar scripts, which are increasingly starting to have problems with the default compiler/includes over time, although they fully supported them before.

**Comment by NexiusTailer** [comment]
UPD: Current y_iterate have exactly what I've mentioned, [here](https://github.com/pawn-lang/YSI-Includes/blob/4d12c33f36c7c0ff74b291f5ffe04f2c9e8e0c51/YSI_Data/y_foreach/y_foreach_iterators.inc#L765). Probably you use that?

**Comment by rt-2** [comment]
> UPD: Current y_iterate have exactly what I've mentioned, [here](https://github.com/pawn-lang/YSI-Includes/blob/4d12c33f36c7c0ff74b291f5ffe04f2c9e8e0c51/YSI_Data/y_foreach/y_foreach_iterators.inc#L765). Probably you use that?

So basically I should set `addsiren` to a bool instead of int simply?

**Comment by rt-2** [comment]
Should we go around the problem and detect when YSI is included for kind of a solution even if not perfect?

**Comment by rt-2** [comment]
Anyway Im guessing for int and bool, true and false will just be the same bit-wise than the int 1/0 so we can ignore this and assume everything is stable?
Thank you

**Comment by rt-2** [comment]
Ok thank you.
