### ISSUE TITLE
Disable autokick and Sendclientmessage to admin

### ISSUE THREAD

**Issue by syahrialdi1** [NexiusTailer/Nex-AC#247]
How to disable auto kick and send notification to admin or rcon admin if someone uses cheat? and can i disable AC for RCON admin?

**Comment by NexiusTailer** [comment]
Use OnCheatDetected callback in your gamemode and make there your own actions when any detection occurs. See the [example](https://github.com/NexiusTailer/Nex-AC/blob/master/CHANGELOG.md) here.

> and can i disable AC for RCON admin?

You can disable any anticheat code using [EnableAntiCheatForPlayer](https://github.com/NexiusTailer/Nex-AC/blob/master/README.md#enableanticheatforplayerplayerid-code-enable)
