### ISSUE TITLE
partially off-topic: silly git errors when i was trying to update my local cloned git repo...

### ISSUE THREAD

**Issue by Zorono** [NexiusTailer/Nex-AC#248]
```
error: failed to encode 'lang/nex-ac_bs.lang by NemanjaMAX/nex-ac_bs.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_cz.lang by SooBad/nex-ac_cz.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_de.lang by Carper/nex-ac_de.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_ee.lang by OldPawn/nex-ac_ee.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_es.lang by JustBored/nex-ac_es.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_fr.lang by j3rry/nex-ac_fr.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_fr.lang by vic1997/nex-ac_fr.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_hu.lang by Pedro/nex-ac_hu.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_it.lang by J4Rr3x/nex-ac_it.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_it.lang by Sasino97/nex-ac_it.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_lt.lang by zaibaslr2/nex-ac_lt.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_lv.lang by Rengar/nex-ac_lv.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_pl.lang by wampiros6/nex-ac_pl.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_pt_br.lang by NicK_/nex-ac_pt_br.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_sk.lang by Sanady/nex-ac_sk.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_th.lang by aktah/nex-ac_th.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_tm.lang by Negativ_Tm/nex-ac_tm.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_tr.lang by Jensenn/nex-ac_tr.lang' from UTF-8 to Windows-1251
error: failed to encode 'lang/nex-ac_ua.lang by Valera_Kovshikov/nex-ac_ua.lang' from UTF-8 to Windows-1251
error: failed to encode 'src/v1.9.55/nex-ac_by.lang' from UTF-8 to Windows-1251
error: failed to encode 'src/v1.9.55/nex-ac_ru.lang' from UTF-8 to Windows-1251
```

please what do you suggest... (i tried searching about this many times and tried a lot of methods which didn't work)

**Comment by NexiusTailer** [comment]
Please try the same action now, I've made a little corrections in .gitattributes, but it should be tested.

**Comment by Zorono** [comment]
> Please try the same action now, I've made a little corrections in .gitattributes, but it should be tested.

unfortunately that didn't work too

**Comment by Zorono** [comment]
I guess i have nothing to do except re-cloning it

**Comment by NexiusTailer** [comment]
Yeah, try this

**Comment by NexiusTailer** [comment]
So, did it help?

**Comment by Zorono** [comment]
> So, did it help?

yea thanks dude,
re-cloning seemed to be the only available fix for this :(

**Comment by NexiusTailer** [comment]
Thats interesting because I still don't understand whether my last commit solved that or the previous .gitattribues was also correct and you had problems because of older repo settings.

**Comment by Zorono** [comment]
> That's interesting because I still don't understand whether my last commit solved that or the previous .gitattributes was also correct and you had problems because of older repo settings.

>  I still don't understand whether my last commit solved that or the previous .gitattributes was also correct and you had problems because of older repo settings.
in fact, the problem doesn't relate to file attributes but I still don't understand what is causing it or how to fix it without re-cloning... but it could be my Operating System's locale's fault... which is by the way a very low probability since updating my local repo was as easy as expected last time...

**Comment by NexiusTailer** [comment]
I changed .gitattributes in this specific case to correct repo encoding in which there is a problem. Now there is no forcing to use cp1251 for the whole repo so now it seems it's not more needed to convert those .lang files which wasn't in utf-8 by default.
