### ISSUE TITLE
non-const parameter

### ISSUE THREAD

**Issue by punkochel** [NexiusTailer/Nex-AC#249]
parameter ip_address[] declared as non-const:
https://github.com/NexiusTailer/Nex-AC/blob/57232694facd674076fd682eb26ef678b1e4585f/src/v1.9.57/nex-ac.inc#L9435

**Comment by NexiusTailer** [comment]
Yes, because it's passed to BlockIpAddress native inside this function, which is also don't have const for its parameter in default samp includes.
