### ISSUE TITLE
warning 201: redefinition of constant/macro

### ISSUE THREAD

**Issue by rendiichtiar30** [NexiusTailer/Nex-AC#250]
D:\CTRP\gamemodes\new.pwn(636) : warning 201: redefinition of constant/macro (symbol "CreateVehicle(0%)")
D:\CTRP\gamemodes\new.pwn(637) : warning 201: redefinition of constant/macro (symbol "AddStaticVehicle(0%)")
D:\CTRP\gamemodes\new.pwn(638) : warning 201: redefinition of constant/macro (symbol "DestroyVehicle(0%)")
D:\CTRP\gamemodes\new.pwn(639) : warning 201: redefinition of constant/macro (symbol "AddStaticVehicleEx(0%)")

Please help me, I've done all the ways to get rid of this problem.

**Comment by NexiusTailer** [comment]
Show the lines 636-639 in your script (gamemodes/new.pwn)
