### ISSUE TITLE
how find anti cheat id ?

### ISSUE THREAD

**Issue by phantomboy121** [NexiusTailer/Nex-AC#253]
how find anti cheat id ?
i want disable destroy the vehicle spawned from menu

**Comment by NexiusTailer** [comment]
There is no any "anti-vehicle spawned", but I think you mean "anti-unoccupied vehicle teleport", so it's 005 code.
You can find all IDs [here](https://github.com/NexiusTailer/Nex-AC/blob/31e005b9c314561c418ebf90e9bb684d9f7a0653/src/v1.9.58/nex-ac.inc#L241-L298).
