### ISSUE TITLE
False triggering of the anti-cheat. (19 code)

### ISSUE THREAD

**Issue by hertanion** [NexiusTailer/Nex-AC#256]
Если поставить некорректные координаты камеры в пакете ID_AIM_SYNC и выстрелить в какого-нибудь игрока, его кикнет с кодом 19 (GM от пуль).
![image](https://user-images.githubusercontent.com/90708207/152414211-be17b0ca-0179-41c1-a0f4-c7f939ebb804.png)
![image](https://user-images.githubusercontent.com/90708207/152414313-192cfdff-72a0-46e4-a020-0630a31eb3b6.png)

[lua_code.zip](https://github.com/NexiusTailer/Nex-AC/files/7997529/lua_code.zip)

**Comment by NexiusTailer** [comment]
С анти-гмом пешком есть и многие другие способы сделать урон невалидным для клиентской физики жертвы, чтобы она его отклонила, хотя для сервера он оставался бы валидным. Если используешь серверную дамаг систему, то могу просто посоветовать отключить анти-гм (как минимум пешком) и прочие античиты, например на хп. Если же принципиально использование клиентской (та что по дефолту) системы урона, то тут уже вариант просто поставить её на варнинг администраторам, т.к. корректно свалидировать на сервере все подобные возможные случаи довольно проблематично.
