### ISSUE TITLE
False kick for code 15

### ISSUE THREAD

**Issue by IndianMan1** [NexiusTailer/Nex-AC#258]
Hello, in my server when players quit while having weapons and rejoin they are always kicked for weapon hacks i.e code 15, It happens everytime and with every weapon even if it is 1 ammo 
Looking forward for a help regarding this, thank you!

**Comment by NexiusTailer** [comment]
Should be more information: anticheat server logs (at the time of the kick), screenshot or a detailed description of at what specific point in time and after what actions the kick occurs, etc.

**Comment by IndianMan1** [comment]
Thanks for replying as I told you that the kick occurs when any player already has any kind of weapon and after disconnecting, when he rejoins anticheat kicks the player for code 15
Anticheat logs are below:
[12:54:14] [join] IndianMan_ has joined the server 
[12:54:23] Data Loaded - Player IndianMan_
[12:54:25] [Nex-AC debug] AC weaponid: 0, AC ammo: 0, weaponid: 38, ammo: 20
[12:54:25] [Nex-AC] Suspicion on the ID 0. Reason code: 015 (1)
[12:54:26] [part] IndianMan_ has left the server (0:2)

**Comment by NexiusTailer** [comment]
So it happens only if a player reconnected to the server without restarting the game? Which way you give them any weapon at spawn? If you do it in AddPlayerClass/SetSpawnInfo, the problem is in your samp client which is not sending its weapon data picked from player class info after reconnect.

**Comment by IndianMan1** [comment]
Thank you for your help, I'll let you know if the issue still persists by tomorrow.
