### ISSUE TITLE
AntiCheat on LagShot 

### ISSUE THREAD

**Issue by HartyChock** [NexiusTailer/Nex-AC#261]
Hello and thanks for your time!

Will this anticheat work on godmode's and health hack's nex-ac codes correctly on LagShot SA:MP server? (lagcompmode 0)

Thank You.

**Comment by NexiusTailer** [comment]
The only API difference for disabled lagcompmode is not calling OnPlayerWeaponShot callback, so, the following anticheats which works in it will be somehow changed in its behaviour:
- Anti-Ammo hack (check for infinite ammo will be disabled)
- Anti-GodMode (onfoot & in vehicle will be disabled)
- Anti-Rapid fire / Anti-Pro Aim / Anti-AFK Ghost (will be disabled)

It should be noticed that most of such anticheats anyway designed to work with bullet weapons only, and don't work with any others ever if lagcomp is enabled (except anti-ammo hack which has different checks for adding ammo by cheats and keeping it infinite, so the first type of checks works for any weapon with ammo and will continue to work on lagcomp disabled).
