### ISSUE TITLE
Reason code: 007

### ISSUE THREAD

**Issue by blaablaaaa** [NexiusTailer/Nex-AC#266]
Hello everyone, I updated my nex-ac to the latest version. And now when I log in from the server, I get this reason code. Can anyone help me how to solve this?

[Nex-AC debug] Anim: 978, old anim: 978, weaponid: 0, spec act: 0, vel x, y: 0.000000, vel z: 0.161460
[19:10:45] [Nex-AC] Suspicion on the ID 0. Reason code: 007 (1)

**Comment by NexiusTailer** [comment]
What do you do at this moment? Any detailed information?

**Comment by blaablaaaa** [comment]
I'm actually flying with the command /fly which is included in the mod, on earlier versions this didn't happen to me that I get this suspicion

**Comment by NexiusTailer** [comment]
So, share the code so I can reproduce that.

**Comment by NexiusTailer** [comment]
Thank you for providing this example, will check it today.
Btw what version of anticheat did you update to the latest?

**Comment by NexiusTailer** [comment]
Well, it actually kicks on v1.9.52 too. Anyway, I'll try to fix this in next release.

**Comment by NexiusTailer** [comment]
Thank you again, fixed (will appear in next release).
