### ISSUE TITLE
AJUDA SOBRE O ANTI-CHEAT

### ISSUE THREAD

**Issue by isaqueL** [NexiusTailer/Nex-AC#267]
Я хочу создать диалог, когда игрока выгоняют с моего сервера при использовании читера, этот диалог появляется у него на экране, но я не могу его создать, вы можете мне помочь?

«Вас исключили из-за подозрений во взломе. Во избежание подобных ситуаций в будущем. Пожалуйста, удалите все нелегальные моды».

 чуть ниже сообщения появляется античит-код о том, что он был кикнут.

пример: код: #4

Я хочу сделать такой диалог

**Comment by NexiusTailer** [comment]
Сам текст диалога сформируйте через [format](https://team.sa-mp.com/wiki/Format) (выводя в строку код античита). Для показа окна диалога воспользуйтесь функцией [ShowPlayerDialog](https://team.sa-mp.com/wiki/ShowPlayerDialog), указав в качестве параметра `info` вашу строку с основным текстом диалога.
