### ISSUE TITLE
FALSE ANTI TELEPORT DETECTION CODE 4

### ISSUE THREAD

**Issue by isaqueL** [NexiusTailer/Nex-AC#268]
multiple players on mobile are being kicked when entering 2-door and 4-door vehicles in seat 2 for a certain time

video link to better analyze what may be happening and how I can solve it.

MORE DETAILED LINK 1: https://youtu.be/XTiS3CY0Gn0

LINK 2: https://youtu.be/iUhjsjVq2nM

photo of the two-seat vehicle: https://prnt.sc/lOzfsCioVcfZ
photo of the four-seat vehicle: https://prnt.sc/JwL9qbzecxzm

two seat vehicle code kick: 
[Nex-AC debug] Entered veh: 0, veh: 5, entered seat: -1, seat: 1, veh model: 411, enter time: 2707
 [Nex-AC] Suspeita no ID 0. Código de motivo: 004 (1)
 
four seat vehicle code kick:

[Nex-AC debug] Entered veh: 0, veh: 6, entered seat: -1, seat: 1, veh model: 560, enter time: 4179
[01:54:42] [Nex-AC] Suspeita no ID 0. Código de motivo: 004 (1)

**Comment by NexiusTailer** [comment]
Your mobile clients don't send OnPlayerEnterVehicle to the server or send it with corrupted vehicleid/other parameters so the server doesn't know which vehicle was entered to keep it until player becomes in vehicle and comparing entered vehicle ID with that a player actually in. Report this bug to a client developer.

**Comment by isaqueL** [comment]
I did the test on the official samp launcher of the play store downloading all the pattern without mods modifications, and the bug continues, is there no way to solve this? my server is made up of several mobile players, and the bug is only in seat 2, this will disturb many players.

**Comment by NexiusTailer** [comment]
SAMP launcher from the play store is not 'official', it's just one of many which probably has also such bugs. All of the above is valid: report these bugs to their developers, as these are their problems. Anti-cheat only points you to them but the cause in in these client(s).
