### ISSUE TITLE
Health Hack Flood Public

### ISSUE THREAD

**Issue by zXLiMiT-ToTAL** [NexiusTailer/Nex-AC#269]
**Problem:**

When the player damages the vehicle, the nex-ac triggers false health-hack detection.
When in a short time the vehicle is damaged, another problem pops, flood public 24 kicking the player off the server.

**Test code:**

//Script used to perform tests
#include <a_samp>
#include <timerfix> //Even correcting the timers stuck, the problem remains
#include <nex-ac>
#include <Pawn.CMD>

#pragma warning disable 214
#pragma warning disable 239

new vid[MAX_PLAYERS];
new vt[MAX_PLAYERS];

main()
{
}

public OnPlayerConnect(playerid)
{
    vid[playerid] = -1;
	vt[playerid] = 0;
	return 1;
}

public OnPlayerSpawn(playerid)
{
	SetPlayerPos(playerid, 2171.1213, 1411.7948, 11.0625);
	return 1;
}

public OnPlayerStateChange(playerid, newstate, oldstate)
{
    if(newstate == PLAYER_STATE_DRIVER)
	{
	    //The longer the timer interval, the faster it generates false detections
	    
		//vt[playerid] = SetTimerEx("timerveh", 250, true, "i", playerid);
		//vt[playerid] = SetTimerEx("timerveh", 500, true, "i", playerid);
		vt[playerid] = SetTimerEx("timerveh", 1000, true, "i", playerid);
	}
	return 1;
}

CMD:veh(playerid)
{
    new Float:x, Float:y, Float:z;
    new Float:angle;
	GetPlayerPos(playerid, x, y, z);
	GetPlayerFacingAngle(playerid, angle);

	vid[playerid] = CreateVehicle(411, x, y, z, angle, -1, -1, -1);
	SetVehicleVirtualWorld(vid[playerid], GetPlayerVirtualWorld(playerid));
	LinkVehicleToInterior(vid[playerid], GetPlayerInterior(playerid));
	PutPlayerInVehicle(playerid, vid[playerid], 0);
	return 1;
}

forward timerveh(playerid);
public timerveh(playerid)
{
	SetVehicleHealth(GetPlayerVehicleID(playerid), 1000.0);
	RepairVehicle(GetPlayerVehicleID(playerid));
	return 1;
}

public OnGameModeInit()
{
	return 1;
}

public OnGameModeExit()
{
	return 1;
}

**debug nex-ac**
[Nex-AC debug] AC veh health: 877.820251, veh health: 942.829101, veh: 1, playerid: 0
[Nex-AC debug] AC veh health: 852.740905, veh health: 1000.000000, veh: 1, playerid: 0
[Nex-AC debug] AC veh health: 950.526062, veh health: 1000.000000, veh: 1, playerid: 0
[Nex-AC debug] ID 0 exceeded 9 flood attempts. Public ID: 24

Ping: ~180

**Comment by zXLiMiT-ToTAL** [comment]
```#include <a_samp>
#include <timerfix> //Even correcting the timers stuck, the problem remains.
#include <nex-ac>
#include <Pawn.CMD>```

**Comment by NexiusTailer** [comment]
After some testing with 1000 and 250 ms timer I cannot reproduce any reported issues on both of them with this shared code example.
