### ISSUE TITLE
[bugfix]: Anti high ping sometime kicks player on connection.

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#27]
In  ``Nex-AC/src/v1.9/v1.9.22/r2/nex-ac.inc`` ,
The line 6424
```
		if(ac_gpp > AC_MAX_PING)
```
Should be :
```
		if(ac_gpp > AC_MAX_PING && ac_gpp != 65535)
```

Sometime on connection, the ping of a player may be 65535, so to avoid a false flag I added this condition.
This is documented on this page http://wiki.sa-mp.com/wiki/GetPlayerPing.

Thank you,
rt-2

**Comment by NexiusTailer** [comment]
Did you really have this happen, or rely only on a note from the wiki?
If the second, then after the ping check there is a [special check](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9/v1.9.22/r2/nex-ac.inc#L6426) which works **only** when a certain number of warnings is reached (3). Those only if the player ping more than the maximum of more than three seconds after the connection, it is clearly not within the normal state.

**Comment by rt-2** [comment]
Yes it did happen on my server, someone got kicked on connection, and in the server_log.txt, the debug said ping 65535.
rt-2

**Comment by rt-2** [comment]
In my opinion, this value is there before any ping has been done probably, just my guess.
