### ISSUE TITLE
maybe compatible with open.mp?

### ISSUE THREAD

**Issue by Li-ght** [NexiusTailer/Nex-AC#273]
`ac_RconEnable = (GetConsoleVarAsBool("rcon.enable") != 0);`
`ac_LagCompMode = (GetConsoleVarAsBool("game.use_lag_compensation") != 0);`

`#define AC_SERVER_OMP_VERSION			"open.mp 0.0.8.1988"`

`static ac_strtmp[10];`
`	#if defined GetConsoleVarAsString`
`		GetConsoleVarAsString("version", ac_strtmp, sizeof ac_strtmp);`
`	#else`
`		GetServerVarAsString("version", ac_strtmp, sizeof ac_strtmp);`
`	#endif`
`	if(strfind(ac_strtmp, AC_SERVER_VERSION) == -1 && strfind(ac_strtmp, AC_SERVER_DL_VERSION) == -1 && strfind(ac_strtmp, AC_SERVER_OMP_VERSION) == -1 ) print(VERSION_WARNING);`

or something else.
sorry for my english.

**Comment by NexiusTailer** [comment]
This will be done after the release, because now it's still in beta.
Moreover it's already compatible, the warnings you get it's just for informative purpose.
