### ISSUE TITLE
symbol already defined: "ac_OnPlayerClickMap"

### ISSUE THREAD

**Issue by flamesidgs** [NexiusTailer/Nex-AC#279]
When I use **OnPlayerClickMap** and a problem is found in the **ac_OnPlayerClickMap** section, there is a callback that already uses **OnPlayerClickMap**

![image](https://user-images.githubusercontent.com/87573334/204134040-034f533f-0cac-4d8a-b53f-12e1cd0540d9.png)

![image](https://user-images.githubusercontent.com/87573334/204134025-1786900f-dccf-4f4e-8f53-18d2c6f3f5ea.png)

**Comment by NexiusTailer** [comment]
The problem is in one of your hooks, probably after including the anticheat.
