### ISSUE TITLE
Many false positives

### ISSUE THREAD

**Issue by kotbrain** [NexiusTailer/Nex-AC#28]
Hi. I use Nex-AС on my Stage RolePlay server with an online 200-300. Maybe I incorrectly connected something, but when I first started on the main server, I got a lot of false positives. I configured and made changes the anti-cheat to bring it to a more or less stable state. But until now some false positives are still available and the setting here will not help. I do not want to change the source code much, because it will cause problems with the update.

I can constantly provide detailed logs for false positives to help with the correction. It seems to me that the developer of this anticheat is Russian and that's why I propose to contact me on ВКонтакте (vk.com/kot_brain).

If not, I can create themes here, but it's not very convenient for me.

**Comment by NexiusTailer** [comment]
No problem. Let's contact in vk, for me it will also be easier
