### ISSUE TITLE
So many warning with Open.MP strong tag

### ISSUE THREAD

**Issue by AthallahDzaki** [NexiusTailer/Nex-AC#281]
nex-ac.inc:9079 (warning) tag mismatch: expected tag "t_PLAYER_STATE", but found none ("_")

**Comment by NexiusTailer** [comment]
This isn't a error but only warning which you posted. Anyway, omp states it's backward-compatible with samp now, so there should be any critical stuff with it. Probably will add some additional adaptations later, but it's not in a high priority at the moment.
