### ISSUE TITLE
Pickups broke down

### ISSUE THREAD

**Issue by SantiagoBoss1** [NexiusTailer/Nex-AC#283]
Greetings, pickups in fashion do not work for me, and I write an error that the matter is in nex-ac and in Onplayerpickup which is in fashion Error:

AMX backtrace:
[debug] #0 001b3dc0 in public ac_OnPlayerPickUpDynamicPickup (playerid=0, pickupid=76) at D:\DIAMOND RP\27.10.2019\gamemodes\normative.pwn:19288
[debug] #1 00031108 in public OnPlayerPickUpDynamicPickup (playerid=0, pickupid=76) at D:\DIAMOND RP\27.10.2019\compiler\include\nex-ac.inc:6211

**Comment by NexiusTailer** [comment]
So, fix it in your gamemode

```
[debug] #0 001b3dc0 in public ac_OnPlayerPickUpDynamicPickup (playerid=0, pickupid=76) at D:\DIAMOND RP\27.10.2019\gamemodes\normative.pwn:19288
```

**Comment by SantiagoBoss1** [comment]
There is an error in the cycle, in order to fix it, you need to delete the cycle when the player steps on the pickup truck at home.

cycle: 

for(new h = 1; h != TOTAL_HOUSE + 1; h ++) {
		if(!IsPlayerInRangeOfPoint(playerid, 2.0, HouseInfo[h][hEnter][0], HouseInfo[h][hEnter][1], HouseInfo[h][hEnter][2])) continue;  // there is an error in this line (there is an error in this line, but if you delete it, then all the pickups that the player steps on will work by buying a house, and if the cycle is deleted, then everything will work)
		string = !"";
		if(HouseInfo[h][hOwned]) format(string, 222, ""WHITE"Номер дома: "SERVER"%d"WHITE"\n\nВладелец дома: "SERVER"%s "WHITE"\nКласс дома: "SERVER"%s"WHITE"\nЦена дома: "SERVER"%d$",h,HouseInfo[h][hOwner],classhome_names[HouseInfo[h][hKlass]],HouseInfo[h][hValue]);
		else format(string, 222, ""WHITE"Номер дома: "SERVER"%d\n\n"WHITE"Класс дома: "SERVER"%s\n"WHITE"Цена дома: "SERVER"%d$",h, classhome_names[HouseInfo[h][hKlass]], HouseInfo[h][hValue]);
		return SPD(playerid, (HouseInfo[h][hOwned] ? (10075) : (10026)), DIALOG_STYLE_MSGBOX, !"{ffdd73}Дом",string,(HouseInfo[h][hOwned] ? (!"Войти") : (!"Купить")), !"Закрыть");
	}

**Comment by NexiusTailer** [comment]
You need to just fix the error on line 19288 n your normative.pwn

**Comment by SantiagoBoss1** [comment]
Found the problem, Thank you
