### ISSUE TITLE
Not Detected in nex-ac

### ISSUE THREAD

**Issue by KirovYuri** [NexiusTailer/Nex-AC#288]
Not detected in nex-ac
https://github.com/NexiusTailer/Nex-AC/assets/109130619/1b2d2af2-6820-4064-a927-770e56c68485

**Comment by NexiusTailer** [comment]
What exactly should be detected here?

**Comment by KirovYuri** [comment]
anti invincible hack i think

**Comment by NexiusTailer** [comment]
Is there any details about how it works?

**Comment by KirovYuri** [comment]
> Are there any details about how it works?

not working
