### ISSUE TITLE
Античит не видит чит

### ISSUE THREAD

**Issue by Farmom** [NexiusTailer/Nex-AC#292]
Чит https://www.blast.hk/threads/106155/
Можешь защиту сделать? Он там ваще работает так что со стороны персонажа колбасит люто но чит то работает(

**Comment by Farmom** [comment]
а да слушай можешь метлу пофиксить? вот код с паблика if(!IsPlayerInAnyVehicle(playerid))
{
    new animlib[30], animname[30];//переменные
    GetAnimationName(GetPlayerAnimationIndex(playerid), animlib, sizeof(animlib), animname, sizeof(animname));//проверка на анимацию
    new Float:posx, Float:posy, Float:posz;//переменные
    GetPlayerPos(playerid, posx, posy, posz);//проверка на координаты
    if(posz >= 2)//Если posz равен либо больше 2 метров, то....
    {
            if(strcmp(animlib, "SWIM", true) == 0 && strcmp(animname, "SWIM_crawl", true) == 0)//проверяем на анимацию, если все верно то....
            {
                    new plname[MAX_PLAYER_NAME];//переменная
                    new string[256];//string
                    GetPlayerName(playerid, plname, sizeof(plname));//узнаем имя игрока
                    format(string,sizeof(string),"%s был кикнут. Причина: Fly Hack",plname);//имя мы бьем через format
                    SendClientMessageToAll(0xFFFFFFFF, string);//показываем всем игрокам
                    Kick(playerid);//кикаем игрока
            }
    }
}
ваще заебись ловит метлу с mopfix v4 за 1 секунду только 2 нужно поменять на 4 ибо в воде ложные кики будут

**Comment by NexiusTailer** [comment]
> а да слушай можешь метлу пофиксить? вот код с паблика if(!IsPlayerInAnyVehicle(playerid)) { new animlib[30], animname[30];//переменные GetAnimationName(GetPlayerAnimationIndex(playerid), animlib, sizeof(animlib), animname, sizeof(animname));//проверка на анимацию new Float:posx, Float:posy, Float:posz;//переменные GetPlayerPos(playerid, posx, posy, posz);//проверка на координаты if(posz >= 2)//Если posz равен либо больше 2 метров, то.... { if(strcmp(animlib, "SWIM", true) == 0 && strcmp(animname, "SWIM_crawl", true) == 0)//проверяем на анимацию, если все верно то.... { new plname[MAX_PLAYER_NAME];//переменная new string[256];//string GetPlayerName(playerid, plname, sizeof(plname));//узнаем имя игрока format(string,sizeof(string),"%s был кикнут. Причина: Fly Hack",plname);//имя мы бьем через format SendClientMessageToAll(0xFFFFFFFF, string);//показываем всем игрокам Kick(playerid);//кикаем игрока } } } ваще заебись ловит метлу с mopfix v4 за 1 секунду только 2 нужно поменять на 4 ибо в воде ложные кики будут

У метлы нет никакой анимации, так что этот код не словит (тем более такая же реализация, но лучше и эффективнее, уже давно есть в самом ач от обычного флайхака).

**Comment by Farmom** [comment]
братан ты на приколе? https://www.blast.hk/threads/20214/ вот MopFix v4 его твой античит не ловит) я на аризоне и эвольв рп летаю на максимальной скорости + мне даже медленно поэтому через собейт ускоряю скорость игры
Вот этот недоантичит что я тебе скинул код ловит метлу за 1 сек, попробуй его вшить в мод.

И по поводу кордмастера я знаю просто назвал его телепортом ну а че его не исправишь то? по такой логике же можно и античит не делать а писать отмазки) попробуй усилить античит на аирбрейк может тогда словит?

**Comment by NexiusTailer** [comment]
> братан ты на приколе? https://www.blast.hk/threads/20214/ вот MopFix v4 его твой античит не ловит) я на аризоне и эвольв рп летаю на максимальной скорости + мне даже медленно поэтому через собейт ускоряю скорость игры Вот этот недоантичит что я тебе скинул код ловит метлу за 1 сек, попробуй его вшить в мод.

Это, паходу, ты на приколе. Посмотри как работает **актуальный** mopfix (которому,  к слову, уже несколько лет с релиза как) - никак анимацию он давно не шлёт, иначе бы его ловил обычный анти-флай, который присутствует в ач с 2015 года, т.е. с самой первой версии.

> ну а че его не исправишь то?

Потому что будут ложные?

> по такой логике же можно и античит не делать а писать отмазки)

Можно, но как видишь, я пишу именно античит

> попробуй усилить античит на аирбрейк может тогда словит?

Каким именно образом усились и почему именно античит на аирбрейк? Там поведение никак не связанное с аиром и все значения шлются в пределах нормы (но то он и медленный, на то он и рабочий).

**Comment by Farmom** [comment]
Ну так я тебе дал код который фиксит mopfix LOL почему этот код не засунешь в nex ac?

Так вот ложные будут так ты же разработчик так исправь тебе баблище платит эвольв и аризона

Ну я не знаю почему на аирбрейк может на спидхак пешком ну ведь там есть исходный код LUA почему не посмотришь исходник и не придумаешь как ловить чит? Самп рп к примеру сделали антирассинхронизацию так там хер какой телепорт работает оно всё палит хотя они не могут клео рванку 2015 пофиксить 3 года)))

**Comment by NexiusTailer** [comment]
> Ну так я тебе дал код который фиксит mopfix LOL почему этот код не засунешь в nex ac?

Потому что он (в третий раз, LOL) не фиксит mopfix, который НЕ посылает никакой анимации, тем более такой банальной, как анимации плавания. Анимация плавания это флайхак из собейта 2012 года, который прекрасно ловится проверкой, которая стоит в античите сейчас (и она гораздо лучше предложенной).

> Так вот ложные будут так ты же разработчик так исправь тебе баблище платит эвольв и аризона

Самый лучший знаток на поле - фанат, который орёт с трибуны, как надо играть футболистам?

А по теме: дай конкретные технические рекомендации по фиксу, а потом и по купированию последствий от такого фикса (если он несёт ещё больше издержек, чем пользы), тогда и разговор будет по-существу. А так, да, аризона и эволв платят именно за фикс читов **на должном уровне** (грамотно, без ещё большего кол-ва проблем от фикса чита, чем без этого фикса), что я и делаю.

> Ну я не знаю почему на аирбрейк может на спидхак пешком ну ведь там есть исходный код LUA почему не посмотришь исходник и не придумаешь как ловить чит? Самп рп к примеру сделали антирассинхронизацию так там хер какой телепорт работает оно всё палит хотя они не могут клео рванку 2015 пофиксить 3 года)))

А почему ты решил, что я его не смотрел?

**Comment by Farmom** [comment]
так тебе платят, исправь значит чит или же я не знаю сделай как на самп рп антирассинхронизацию чтоли)
Я не имею таких навыков в разработке античитов чтобы что то предложить, увы.
Я думаю если бы ты сделал антирассинхронизацию как на самп рп то метла и другие телепорты бы стали невозможны
Ну метла не посылает анимацию точнее мопфикс ее убирает для сервера но тот код что я тебе давал может и хуйня но зато он моментально ловит чит, почему не попробуешь его вшить мод так то если оно работает

**Comment by NexiusTailer** [comment]
> так тебе платят, исправь значит чит или же я не знаю сделай как на самп рп антирассинхронизацию чтоли)

Внимательно перечитываем:
>> А так, да, аризона и эволв платят именно за фикс читов **на должном уровне** (грамотно, без ещё большего кол-ва проблем от фикса чита, чем без этого фикса), что я и делаю.

> Я не имею таких навыков в разработке античитов чтобы что то предложить, увы.

Так ты, очевидно, и в разработке читов не имеешь, ибо просишь технически затруднительные реализации защит от того, что даже сам и не понимаешь, как именно оно работает)

> Я думаю если бы ты сделал антирассинхронизацию как на самп рп то метла и другие телепорты бы стали невозможны 

Что из себя представляет эта антирассинхронизация и как именно она блокирует их работу? Никакой конкретики ты пока не предоставил, о чём я просил ещё из предыдущего своего сообщения.

> Ну метла не посылает анимацию точнее мопфикс ее убирает для сервера но тот код что я тебе давал может и хуйня но зато он моментально ловит чит, почему не попробуешь его вшить мод так то если оно работает

Как оно может ловить чит, или оно то и делает, что проверяет по анимке? Где логика? Почему ты не попробуешь напрячь извилины, если оно не может работать даже в теории, о чём тебе пишут уже четвёртый раз подряд. Если у тебя оно что-то ловит, то это что-то - это совсем неактуальная реализация того чита (или не тот чит вообще).

**Comment by Farmom** [comment]
так если попробуешь сделать то может и получится я не знаю
Антирассинхронизация фиксит телепортацию и некоторые проблемы самп по заявлению разработчика сам-рп она кароче работает так что если ловит телепорт то игрока телепортирует обратно откуда он начинал телепортироватся и nop setplayerpos не поможет обойти античит. думаю было бы неплохо такую систему реализовать в nex ac


Так как оно работать не может если я врубаю метлу с фиксом и моментально кикает? (х5) тебе видео демонстрации скинуть?

**Comment by NexiusTailer** [comment]
> так если попробуешь сделать то может и получится я не знаю

Так если мы по-существу говорим, а не трындим по-приколу, то наверное мой ответ это уже компетентное заключение по этому вопросу, не? Или по-существу только я из нас двоих говорю?

> Антирассинхронизация фиксит телепортацию и некоторые проблемы самп по заявлению разработчика сам-рп она кароче работает так что если ловит телепорт то игрока телепортирует обратно откуда он начинал телепортироватся и nop setplayerpos не поможет обойти античит. думаю было бы неплохо такую систему реализовать в nex ac

На аризоне и эволве это уже есть давно и так. В паблик версию такую систему планирую во второй ветке доделать, но это в любом случае не отменяет того, что метлу оно на малых скоростях и без отправки анимки не пофиксит.

> Так как оно работать не может если я врубаю метлу с фиксом и моментально кикает? (х5) тебе видео демонстрации скинуть?

Так ты лучше сразу найди ту метлу, на которой этот код уже кикать не будет (т.е. самую актуальную метлу, которая анимку плавания не шлёт), как я и написал выше.

Для самых маленьких подытоживаю односложными предложениями:

Метла = анимки нет, скорость в пределах нормы = не ловится сервером

Метла, которая ловится сервером = неактуальная и/или вообще не метла, потому что она анимку шлёт = сервер по ней и ловит твоим скинутым кодом = сервер по ней в таком случае будет ловить и тем кодом, который есть в ач сейчас, потому что тот код тоже ловит флайхаки по анимке.

**Comment by NexiusTailer** [comment]
> Так ты лучше сразу найди ту метлу, на которой этот код уже кикать не будет (т.е. самую актуальную метлу, которая анимку плавания не шлёт), как я и написал выше. так у меня такая и есть - вот if data.animationId == 1058 then data.animationId = 0 как видишь анимки нет

А в твоём вышескинутом анти-флайхаке (который уже есть в ач), видим следующее:
```pawn
if(strcmp(animlib, "SWIM", true) == 0 && strcmp(animname, "SWIM_crawl", true) == 0)//проверяем на анимацию, если все верно то....
```
Как видишь, чекает именно анимку (упс, так её ж нет)

> и да я говорю не по приколу я не понимаю как тебе разрабы дают ТЗ у тебя там 100500 отмазок на каждый чит чтоли?)))))

Не, отмазок вообще ни одной. Только вот разве что иногда не шарящим за техническую часть (и реже - ещё и упёртым, как в данном случае) приходится на пальцах объяснять по кругу одно и то же разными словами. Типо, "авось дойдёт наконец".

> а когда 2 ветка nex ac с антирассинхроном выйдет?

Пока точных сроков нет, в активной фазе разработки.

**Comment by Farmom** [comment]
ПОХУЙ что оно чекает главное РАБОТАЕТ

**Comment by NexiusTailer** [comment]
> Чет у тебя слабый антирассинхрон получился на эвольв и арз раз спокойно чит работает

Да не, вполне нормальный, Это до тебя просто чёт слабо довольно простым языком сказанные вещи доходят, а так в остальном проблем нет.

> на самп-рп как то по другому работает антирассинхрон что хрен этот античит будет работать (ну тот коордмастер) и за него кстати кикает буквально через секунд 5 гдето

Никакой конкретики, увы

**Comment by Farmom** [comment]
так как он вполне нормальный если читы пропускает? ведь самп рп же как то сделали что все читы на тп отрубает их античит

**Comment by NexiusTailer** [comment]
> ПОХУЙ что оно чекает главное РАБОТАЕТ

Не, это говорит лишь о том, что ты с чем-то накосячил и тестишь с неактуальным читом. Тебе говорят уже [сбился со счёту сколько] раз, что на актуальной версии метлы эти проверки её не ловят.

**Comment by Farmom** [comment]
Так го поспорим на то что мой найденый античит словит самую последнюю метлу?

**Comment by NexiusTailer** [comment]
> посмотрим

Тебе 10? Не трать моё и своё время, ей богу.

Твердолобостью ты стене хуже не сделаешь, а только себе. Тебе уже сказано:
> Актуальная метла = анимки нет, скорость в пределах нормы = не ловится сервером

> Метла, которая ловится сервером = неактуальная и/или вообще не метла, потому что она анимку шлёт = сервер по ней и ловит твоим скинутым кодом = сервер по ней будет ловить и тем кодом, который есть в ач сейчас, потому что тот код тоже ловит флайхаки по анимке.

Предлагаю во все последующие разы, когда появится желание снова написать про одно и то же, ровно на что уже и имеется ответ в обсуждении, каждый раз немного листать страницу вверх и перечитывать этот самый ответ. Экономия сил, времени, а также ресурса клавиатуры.

**Comment by Farmom** [comment]
Актуальная метла = анимки нет, скорость в пределах нормы = не ловится сервером - но античит с паблика бородатых лет его изи ловит


В общем общение с тобой я не выношу просто. Не пойму как с тобой Arizona \ Evolve работают если ты нихуя не делаешь когда я далбаеб особо не шарящий могу отрыть античит и пофиксить а ты со своими норм навыками вон античит захуярил на 9к строк но метлу пофиксить не можешь хотя я тебе еще в 1 сообщении фикс предоставил который можно ахуенно допилить и будет заебись работать

**Comment by NexiusTailer** [comment]
В общем, общение с рандом ребёнком, не шарящем по сути задаваемого им же вопроса, обернулось психами для самого рандом ребёнка (ничего личного). В следующий раз предлагаю внимательнее читать о том, что тебе пишут и не выпячивать свою некомпетентность и упёртость, а просто проанализировать (тобою же) предлагаемое решение/предложение, поискать актуальные версии читов, на которые делаешь репорт и меньше сраться в штаны на людях своими формулировками.

**Comment by MuthaX** [comment]
> Так го поспорим на то что мой найденый античит словит самую последнюю метлу?

Чел, я не знаю кто ты вообще такой и почему тут что-то заявляешь с профиля созданного на днях и без открытых репозиториев, но, если ты сюда по делу пришёл, то я что-то не вижу у тебя:

1. 2х форков античита: с твоим фиксом и без.
2. Приложенные бинарники чита
3. Видео пруфов
4. Пулл реквеста с грамотно оформленным изменением.

И вообще, если ты такой умный, то почему ты не пошёл напрямую к разработчикам упомянутых тобою серверов и не предложил свои разработки?

**Comment by Farmom** [comment]
нахуй мнне сервера если у меня свой проект

**Comment by Farmom** [comment]
и мне похуй на дату регистрации так то

**Comment by NexiusTailer** [comment]
> нахуй мнне сервера если у меня свой проект

Так а смысл тогда было вести диалог о левых серверах, если у тебя свой проект?
Типо, это такая была попытка высосать аргумент, или что?

В любом случае, ответ ты уже получил, так что увы, ничего из вышеперечисленного беспроблемно не фиксится.
