### ISSUE TITLE
tag mismatch; function heading differs from prototype

### ISSUE THREAD

**Issue by nazpol9** [NexiusTailer/Nex-AC#296]
Привет.

Спасибо тебе за разработку и поддержку реально качественного продукта. 
Использовал его на самп сервере 0.3.7, все работало отлично.

Сейчас переключился на разработку под open.mp и столкнулся со следующим:

**warning 213: tag mismatch**
Ниже один из примеров.
В твоем инклуде:
![image](https://github.com/NexiusTailer/Nex-AC/assets/61046385/be716e24-a72f-4a56-a924-36d630f2b331)

В инклуде omp_player.inc:
![image](https://github.com/NexiusTailer/Nex-AC/assets/61046385/b42ba811-ed9c-4f8f-8586-8a627c1fe60b)

Таких варнингов многовато. 

**error 025: function heading differs from prototype**
Ниже один из примеров.
В твоем инклуде:
![image](https://github.com/NexiusTailer/Nex-AC/assets/61046385/46b4e100-a62b-441b-8a3e-e31645a15462)

В инклуде omp_object.inc:
![image](https://github.com/NexiusTailer/Nex-AC/assets/61046385/4d80894f-c893-473f-b542-94ebc61180c8)

Использую один из крайних nightly билдов open.mp сервера вместе с nex-ac крайней версии (1.9.62).

В архив сюда закину все инклуды omp, что я использую.
[include.zip](https://github.com/NexiusTailer/Nex-AC/files/12861744/include.zip)

Буду благодарен за любое содействие.

**Comment by NexiusTailer** [comment]
Привет, сам инклуд написан под самп, а омп заявляет "полную обратную совместимость", так что любые проблемы на их стороне (а именно, на стороне их инклудов из-за этих критичных и обратно несовместимых изменений).

**Comment by NexiusTailer** [comment]
А, забыл само решение отписать (можно считать как временное, но скорее всего останется именно таким и далее): компилить скрипт самповскими инклудами, запускать на омп сервере уже .amx, в таком случае он переваривает его без проблем и нареканий, разве что есть некоторые варнинги на устаревшие (deprecated) для него самого нативы, которые тем не менее полностью работают и по факту всё нормально.
