### ISSUE TITLE
On-foot speed hack (code #9) triggers when jumping over walls

### ISSUE THREAD

**Issue by pnshr** [NexiusTailer/Nex-AC#300]
Every now and then when you jump over a fence/wall or jump onto a ledge the anti-cheat would think you're speed hacking.
This is with FPS locked to 98. Doesn't work every time, but quite often. Tried using a function called "IsPlayerJumping" and that doesn't fix it.

The reason behind this is the player speed when jumping walls sometimes rapidly increases from about 50 to 500+.
Thank you.

**Comment by NexiusTailer** [comment]
Hi, enable frame limiter in game settings, this is the only proper fix for that problem.
The whole bug is when your fps unlocked (by the game), gta sa engine sometimes behaves weird and jumping on some obstacles may produce sharply speed changes and death of the character. Any effect is obviously unplayable (even if you somehow passed anti-speedhack check and wasn't kicked, your ped dies anyway).
