### ISSUE TITLE
Nex-ac错误

### ISSUE THREAD

**Issue by xiaoainiwms** [NexiusTailer/Nex-AC#301]
C:\Users\XiaoSir\Desktop\TRJ\include\nex-ac.inc(6376) : error 004: function "ac_OnPlayerPickUpDynamicPickup" is not implemented
C:\Users\XiaoSir\Desktop\TRJ\include\nex-ac.inc(7978) : error 004: function "ac_OnPlayerSelectDynamicObject" is not implemented
C:\Users\XiaoSir\Desktop\TRJ\include\nex-ac.inc(8530) : error 004: function "ac_OnPlayerEnterDynamicArea" is not implemented
C:\Users\XiaoSir\Desktop\TRJ\include\nex-ac.inc(8560) : error 004: function "ac_OnPlayerLeaveDynamicArea" is not implemented

**Comment by NexiusTailer** [comment]
Streamer Plugin must be included before the anticheat, please read the README.md file.
