### ISSUE TITLE
nex-ac error

### ISSUE THREAD

**Issue by xiaoainiwms** [NexiusTailer/Nex-AC#302]
nex-ac.inc(2322) : error 017: undefined symbol "STREAMER_PICKUP_SD"

**Comment by xiaoainiwms** [comment]
If the "streamer" plugin is updated, there will be a void in the game

**Comment by xiaoainiwms** [comment]
If the "streamer" plugin is updated, it will crash in the game

**Comment by NexiusTailer** [comment]
> nex-ac.inc(2322) : error 017: undefined symbol "STREAMER_PICKUP_SD"

Nex-AC only supports actual streamer plugins versions (at least 2.8.2, but preferably 2.9.6 as it's latest)

**Comment by NexiusTailer** [comment]
> If the "streamer" plugin is updated, it will crash in the game

How exactly and what exactly it will crash?

**Comment by xiaoainiwms** [comment]
> > NEX-AC.INC（2322）：错误 017：未定义的符号“STREAMER_PICKUP_SD”
> 
> Nex-AC 仅支持实际的流媒体插件版本（至少 2.8.2，但最好是 2.9.6，因为它是最新的）

更新了最新版,打开服务端就错误....

**Comment by NexiusTailer** [comment]
I don't understand
