### ISSUE TITLE
error qawno build

### ISSUE THREAD

**Issue by Wisnoe26** [NexiusTailer/Nex-AC#305]
I experienced compile problems in my open.mp gamemode project when installing include next-ac. the compiler I use is v3.10.11

![Screenshot (5)](https://github.com/NexiusTailer/Nex-AC/assets/140087177/dd674abc-f511-45c1-8034-7362b9f45738)

**Comment by NexiusTailer** [comment]
All these problems are from compiler's and omp includes side:
1. Zeex compiler, starting from 3.10.9, added breakable changes enabling warnings 214 and 239 by default (they are absent in original pawn compiler);
2. omp includes has incompatible modifications of some native parameters, including wrong tags and const for string parameters which didn't have it in original samp includes
