### ISSUE TITLE
PLEASE COMPLETE WITH CONST NXT TYM

### ISSUE THREAD

**Issue by striderdadiff** [NexiusTailer/Nex-AC#312]
/sdcard/Termux-Pawn/nex-ac.inc(2432) : error 214: possibly a "const" array argument was intended: "button2"
/sdcard/Termux-Pawn/nex-ac.inc(3716) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(3726) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(3737) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(3772) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(3936) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4054) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4065) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4089) : error 021: symbol already defined: "OnPlayerTakeDamage"
/sdcard/Termux-Pawn/nex-ac.inc(4107) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4145) : error 021: symbol already defined: "OnPlayerGiveDamage"
/sdcard/Termux-Pawn/nex-ac.inc(4163) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4186) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4262) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4299) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4389) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4399) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4515) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4557) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4595) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4633) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4708) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4736) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4778) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4823) : error 239: literal array/string passed to a non-const parameter
/sdcard/Termux-Pawn/nex-ac.inc(4870) : error 239: literal array/string passed to a non-const parameter

**Comment by NexiusTailer** [comment]
It's an issue in stdlib includes and latest zeex compiler versions, not in anticheat
