### ISSUE TITLE
Multiple warnings

### ISSUE THREAD

**Issue by Clicked47** [NexiusTailer/Nex-AC#314]
_**Hi!**
I have a problem trying to install this anticheat on a base gamemode. Multiple warnings (> 200) in the nex-ac.inc file, which are related to labels in special actions, weapons **(warning 213)**. In addition to some more related to literal array/string passed to a non-const paramete **(warning 239)**. I am using the latest version of the qawno compiler.
I would greatly appreciate any help. I'm getting back into programming after 5 years away.
Greetings_

**Comment by NexiusTailer** [comment]
All those warning does not related to nex-ac itself, it's the fault of qawno and its omp libraries which have wrong tags since they're not backwards compatible with samp ones

**Comment by NexiusTailer** [comment]
As the solution, use samp standart includes
