### ISSUE TITLE
Mistake in the code

### ISSUE THREAD

**Issue by Lashoo28** [NexiusTailer/Nex-AC#317]
I noticed something like this and it should be like that? Not only here, there are several other places

![bandicam 2024-06-10 19-12-23-378](https://github.com/NexiusTailer/Nex-AC/assets/94623387/c1797531-aaa1-4775-803f-743b80a3aac1)

**Comment by NexiusTailer** [comment]
It is intended due to the compiler limitation of 31 character so it should be cut like that :/
