### ISSUE TITLE
Ghost Hack cant detect

### ISSUE THREAD

**Issue by KirovNoName** [NexiusTailer/Nex-AC#321]
https://github.com/NexiusTailer/Nex-AC/assets/109130619/64b40d01-029e-451d-8883-72974a5922ce

cant detect ghost hack

**Comment by NexiusTailer** [comment]
How it looks like from the side of the cheater?

**Comment by NexiusTailer** [comment]
This doesn't look like fake afk by the provided video since the cheater has become invisible for a victim. That's why I needed the view how it look from the cheater's side.

**Comment by NexiusTailer** [comment]
Checked the cheat source, it's basic invisible surfing. You should use [Pawn.RakNet](https://github.com/katursis/Pawn.RakNet) as a dependency so the anticheat can apply additional sync checks for surfing. If it doesn't help and there are still some cases when the cheat works, use [rakcheat](https://github.com/f0Re3t/nex-ac_rakcheat) (it has more validations exactly for player surfing teleports).

**Comment by NexiusTailer** [comment]
> > This doesn't look like fake afk nor ghost hack by the provided video since the cheater has become invisible for a victim. That's why I needed the view how it look from the cheater's side.
> 
> https://streamable.com/x6bd7p
> 
> here

https://github.com/NexiusTailer/Nex-AC/issues/321#issuecomment-2213469727
