### ISSUE TITLE
Use Nex-AC with open.mp

### ISSUE THREAD

**Issue by aujiz11** [NexiusTailer/Nex-AC#323]
Is it stable when using Nex-AC on the open.mp platform? Since I want to use Nex-AC on open.mp and found a lot of warnings, I just want to make sure that after fixing all the warnings Nex-AC will work fine, Thanks.

**Comment by NexiusTailer** [comment]
Hi, yes. It works under omp server the same as under samp server as long as omp server won't change anything from compatibility stuff. Omp includes are incompatible with samp from the start, so the problem is only in them.
