### ISSUE TITLE
Nex-AC conflict problem

### ISSUE THREAD

**Issue by aujiz11** [NexiusTailer/Nex-AC#324]
My server is using omp-stdlib, I have added **Nex-AC** to the command and have removed the warnings and errors, however when starting the server it may have caused a conflict with **Pawn.CMD** Because the PC_EmulateCommand function cannot be used. After the server had been open for a while (about more than 1 hour), it crashed without any logs.

**Comment by NexiusTailer** [comment]
So, the problem is probably in Pawn.CMD and its PC_EmulateCommand function.

**Comment by aujiz11** [comment]
> Vì vậy, vấn đề có thể nằm ở Pawn.CMD và hàm PC_EmulateCommand của nó.

Hmm, I just need to remove 1 of 2 from every stable complete command.

**Comment by NexiusTailer** [comment]
Which 1 of which 2?

**Comment by aujiz11** [comment]
> Which 1 of which 2?

Sorry, I said it wrong, my server still works fine if I remove Nex-AC or Pawn.CMD from the server.

**Comment by aujiz11** [comment]
```
#include <open.mp>

#include <streamer>
#include <Pawn.CMD>
#include <a_mysql>
#include <sscanf2>
#include <samp_bcrypt>
#include <Pawn.RakNet>

#include <colandreas>
#include <PawnPlus>
#include <pp-mysql>
#include <pp-bcrypt>

#include <YSI\YSI_Data\y_foreach>
#include <YSI\YSI_Coding\y_malloc>
#include <YSI\YSI_Data\y_bit>
#include <YSI\YSI_Coding\y_va>
#include <YSI\YSI_Core\y_utils>

#include <YSI\YSI_Players\y_android>
#include <YSI\YSI_Game\y_vehicledata>
#include <YSI\YSI_Game\y_weapondata>

#define DEBUG
#define AC_DEFAULT_COLOR 0xFF6347FF

#include <nex-ac_vn.lang>
#include <nex-ac>

#include <weapon-config>
#include <easyDialog>
#include <vehicle_plus>
#include <pawn-easing-functions>
#include <skin-tags>
```

**Comment by NexiusTailer** [comment]
Are you now running your server under omp, right? Which version of the server is currently crashes? Is it nightly or release build?

**Comment by aujiz11** [comment]
omp server [v1.2.0.2670](https://github.com/openmultiplayer/open.mp/releases/tag/v1.2.0.2670)

**Comment by aujiz11** [comment]
yes, it creates a omp_minidump.dmp file

**Comment by NexiusTailer** [comment]
So, send it to the omp decelopers
