### ISSUE TITLE
BUGGY AND UNSTABLE!

### ISSUE THREAD

**Issue by Datcyx** [NexiusTailer/Nex-AC#329]
Crashers don't detect and Invalid seat crash is also bug it kick player for no reason, for example player became  driver and switch to passenger it will kick players!

**Comment by NexiusTailer** [comment]
Crashers are well detected and anti-invalid seat crasher works without issues in the current version

**Comment by NexiusTailer** [comment]
Have any concretics to prove the opposite? Share it first!
