### ISSUE TITLE
False positive for airbreak when surfing on object

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#330]
When surfing on an object at a slightly high speed, vertically upwards, the anti cheat accuses the use of airbreak (code 0).

**Comment by NexiusTailer** [comment]
Well, there's unfortunately no native GetPlayerSurfingPlayerObjectID implemented in samp server, so this means that anticheat cannot obtain the surfing object of a player if this object is player-object type. However, Nex-AC starts to check this immediately after he finds this native declared from any other source (YSF, open.mp). So if you're running your server under omp, just declare this native:

```pawn
native GetPlayerSurfingPlayerObjectID(playerid);
```

or use omp-stdlib includes where it's already declared. In case if you're on samp server and if you use YSF plugin, you can also just do:

```pawn
#include <YSF>
```

before the anticheat so it can see the native declared in it and use it for checking.

**Comment by Walter-Correa** [comment]
It worked, I just needed to put `#include <YSF>` before `#include <nex-ac>`. Thanks!
