### ISSUE TITLE
Issue with Using SetPlayerPos

### ISSUE THREAD

**Issue by Telzin2k** [NexiusTailer/Nex-AC#337]
When I log into my server and enter my password, I spawn the player using **SpawnPlayer**, and in **OnPlayerSpawn**, I also use **SetPlayerPos**. However, after the player is positioned, they are detected as suspected of **002 Anti-teleport hack (onfoot)**.

Any solution or modification I could apply?

**Comment by NexiusTailer** [comment]
Provide the code you use inside OnPlayerSpawn callback

**Comment by Telzin2k** [comment]
I did some tests and noticed that when the player is spawned directly from the dialog return, he is detected. However, when I set his position in 'OnPlayerSpawn', he is not detected.

`
// Login dialog return.
Callback DIALOG_LOGIN(playerid, dialogid, response, listitem, string:inputtext[])
{
	if(response)
	{
		new String[50];
		format(String, sizeof(String), ACCOUNTS_FILES, GetPlayerNameEx(playerid));

		new SHA256_Pass[65];
    	SHA256_PassHash(inputtext, SHA256_SALT, SHA256_Pass, sizeof SHA256_Pass);

		if(!strcmp(SHA256_Pass, DOF2_GetString(String,"Password"), false))
		{
			Player[playerid][pLogged] = true;
			TogglePlayerSpectating(playerid, false);

			LoadPlayerAccount(playerid);
			HidePlayerLogin(playerid);
			SetPlayerPos(playerid, Player[playerid][pPos][0], Player[playerid][pPos][1], Player[playerid][pPos][2]);

			SendClientMessage(playerid, -1, "DBUG: Successfully logged in");
			return 1;
		}
		else
		{
			Player[playerid][pLoginAttempt] ++;

			if(Player[playerid][pLoginAttempt] >= MAX_LOGIN_ATTEMPT)
				return Kick(playerid);

			new String2[180];
			format(String2, sizeof(String2), "\n{FC1515}Attention: The password you entered is incorrect!\n\n{FFFFFF}Please enter your password again to log in to the server.\n\nMaximum login attempts: %d/%d", Player[playerid][pLoginAttempt], MAX_LOGIN_ATTEMPT);
			
			Dialog_ShowCallback(playerid, using public DIALOG_LOGIN<iiiis>, DIALOG_STYLE_PASSWORD,
			" ", String2, "Entrar", "Cancelar");

			return 1;
		}
	}
	else SelectTextDraw(playerid, 0x808080FF);
	return 1;
}
`

Is there something I can do, or should I really leave the 'SetPlayerPos' in 'OnPlayerSpawn'?

**Comment by Telzin2k** [comment]
Sorry, live and learn. But sometimes I get confused.

Why does this code work without cheat detection?
`public OnPlayerSpawn(playerid)
{
	SetPlayerPos(playerid, Player[playerid][pPos][0], Player[playerid][pPos][1], Player[playerid][pPos][2]);
	return 1;
}`

And this code makes the player get detected?

`public OnPlayerSpawn(playerid)
{
	if(Player[playerid][pLogged] == false)
	{
		Player[playerid][pLogged] = true;
		SetPlayerPos(playerid, Player[playerid][pPos][0], Player[playerid][pPos][1], Player[playerid][pPos][2]);
	}
	return 1;
}`

**Comment by NexiusTailer** [comment]
Both cases are ok and should work correctly, so idk. Can you show me the anticheat debug information from server_log on this detection?

**Comment by Telzin2k** [comment]
`"[19:08:43]" [connection] incoming connection: 127.0.0.1:54280 id: 0
"[19:08:43]" [join] Telzin2k has joined the server (0:127.0.0.1)
"[19:08:51]" [Nex-AC debug] Dist: 1185.024536, dist set: 25000.000000, speed: 0, pos x, y, z: -379.116760, 1122.576904, 19.854516, old pos x, y, z: 0.000000, 0.000000, 0.500000
"[19:08:51]" [Nex-AC] Suspicion on the ID 0. Reason code: 002 (2)
"[19:08:51]" [part] Telzin2k has left the server (0:2)`

**Comment by Telzin2k** [comment]
I added a debug message and tested and found out when I remove the bool variable "Player[playerid][pLogged] = true;
" the dbug message repeats and the player is not detected in the anti cheat, but when I put the bool variable "Player[playerid][pLogged] = true;
" the message only shows once and the player is detected in anti cheat.

**this way the player is not detected**

```
public OnPlayerSpawn(playerid)
{
	if(Player[playerid][pLogged] == false)
	{	
		SetPlayerPos(playerid, Player[playerid][pPos][0], Player[playerid][pPos][1], Player[playerid][pPos][2]);
		SendClientMessage(playerid, -1, "Spawned...");
	}

	return 1;
}
```
**this way the player is detected.**

```
public OnPlayerSpawn(playerid)
{
	if(Player[playerid][pLogged] == false)
	{	
		Player[playerid][pLogged] = true;
		SetPlayerPos(playerid, Player[playerid][pPos][0], Player[playerid][pPos][1], Player[playerid][pPos][2]);
		SendClientMessage(playerid, -1, "Spawned...");
	}

	return 1;
}
```

A lot of madness, but I can't understand what could be happening.

I need the player to be spawned only once in this location, as it was his last location. So I need to use this variable so that it is set only once to its last location when it enters the server.

**Comment by NexiusTailer** [comment]
Judging by the first log, the position which was considered "cheated" by the ac is `-379.116760, 1122.576904, 19.854516`, while should've been `0.000000, 0.000000, 0.500000`, as it was the last legitimate.


> I added a debug message and tested and found out when I remove the bool variable "**Player[playerid][pLogged] = true**" the dbug message repeats and the player is not detected in the anti cheat, but when I put the bool variable "**Player[playerid][pLogged] = true**" the message only shows once and the player is detected in anti cheat.

So, when the exact case with a kick happens? Does it happen on the first spawn, or after any further spawns only?
