### ISSUE TITLE
Invalid weaponid

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#340]
**Hacker on the server:**
```
[16:31:43] [debug]  Accessing element at index 107 past array upper bound 46
[16:31:43] [debug] AMX backtrace:
[16:31:43] [debug] #0 0006a358 in public OnPlayerWeaponShot (playerid=0, weaponid=107, hittype=0, hitid=0, Float:fX=0.00000, Float:fY=0.00000, Float:fZ=0.00000) at D:\...\pawno\include\nex-ac.inc:7097
```

**Comment by NexiusTailer** [comment]
[Line 7097](https://github.com/NexiusTailer/Nex-AC/blob/6ccee7f88670d3c9645b2e70c9fcf981e5eb0dce/src/v1.9.65/nex-ac.inc#L7097) doesn't have anything related to weaponid

**Comment by Walter-Correa** [comment]
> [Line 7097](https://github.com/NexiusTailer/Nex-AC/blob/6ccee7f88670d3c9645b2e70c9fcf981e5eb0dce/src/v1.9.65/nex-ac.inc#L7097) doesn't have anything related to weaponid

Maybe because I'm not using the latest version, but since the problem is in **OnPlayerWeaponShot**, it shouldn't be that hard to locate!

**Comment by NexiusTailer** [comment]
Maybe just update?

**Comment by Walter-Correa** [comment]
> Maybe just update?

That's right, but until another hacker comes along to try this again, I might have an outdated include again!

**Comment by NexiusTailer** [comment]
You won't have an outdated include if you just update it to the latest version, no need to wait for anyone until they comes or not, as it doesn't matter when you have unsupported (outdated) anticheat version with bugs which might be (and probably are) already fixed in the current release.
