### ISSUE TITLE
Kicked for removing jetpack

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#36]
If you equip the jet-pack, then press the ENTER/EXIT button, the jet-pack drops on the ground, but the anti-cheat detects this as a 018.
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
So I checked it and found nothing. Can I see some short video with a problem, please?

**Comment by rt-2** [comment]
Strangely I am not able to do it today, I think the update might have fixed it.
Thank you,
rt-2
