### ISSUE TITLE
Nex-AC is getting proplems 

### ISSUE THREAD

**Issue by JohnMagdy** [NexiusTailer/Nex-AC#40]
hello sir, iam getting proplems with  this include errors: 
`pawno\include\nex-ac.inc(1266) : error 017: undefined symbol "ac_GetSpeed"
 pawno\include\nex-ac.inc(1266) : warning 215: expression has no effect
 pawno\include\nex-ac.inc(1266) : warning 215: expression has no effect
 pawno\include\nex-ac.inc(1266) : warning 215: expression has no effect
 pawno\include\nex-ac.inc(1266) : error 001: expected token: ";", but found ")"
 pawno\include\nex-ac.inc(1266) : error 029: invalid expression, assumed zero
 pawno\include\nex-ac.inc(1266) : fatal error 107: too many error messages on one line`
please help

**Comment by NexiusTailer** [comment]
Please show me how you include the anticheat and maybe also (if possible) some parts of this script

**Comment by JohnMagdy** [comment]
`#include a_samp
#include a_http
#include Ldudb
#include KZI
#include streamer
#include sscanf2
#include izcmd
#include Dini
#include fly
#include gmenu
#include dialogs
#include mSelection
#include geoloaction
#include irc
#include floodcontrol
#include nex-ac

forward OnCheatDetected(playerid, ip_address[], type, code);
public OnCheatDetected(playerid, ip_address[], type, code)
{
    Ban(....);
   // and some others (sorry cant share all the code)
   return 1;
}'

**Comment by rt-2** [comment]
I wouldn't suggest you ban people for an automatic detection, kicking is more than enough, there is some false flags sometimes.

**Comment by JohnMagdy** [comment]
Thanks @rt-2 your suggestion applied, it wasn't good to ban the players on every cheat detect becuase there might be false Detects sometimes......
but the proplem isn't fixed yet :-( please help

**Comment by rt-2** [comment]
Well one thing that comes to my mind (If you haven't modified the file at all) is what version are you using, do you have the server R2 and using the r2 file?

**Comment by JohnMagdy** [comment]
yes SAMP 0.3.7-R2
yes Nex-AC-R2

**Comment by rt-2** [comment]
test it on a blank gamemode

**Comment by JohnMagdy** [comment]
on blank gamemode it has no proplem and after including I-ZCMD found the proplem it gets fucked becuase of I-ZCMD include `\pawno\include\nex-ac.inc(4567) : error 021:  symbol already defined: "OnPlayerCommandText"` 
and after installing Nex-AC on my gamemode i get this errors `\pawno\include\nex-ac.inc(3072) : warning 202: number of arguments does not match definition // return ac_OnPlayerTakeDamage(playerid, issuerid, amount, weaponid, bodypart);
\pawno\include\nex-ac.inc(3086) : error 025: function heading differs from prototype // forward ac_OnPlayerTakeDamage(playerid, issuerid, Float:amount, weaponid, bodypart);
\pawno\include\nex-ac.inc(4567) : error 021: symbol already defined: "OnPlayerCommandText"`  please  fix the proplem

**Comment by rt-2** [comment]
Do the same thing you did, obviously the problem is in your gamemode not the anti-cheat.
Just test for conflict over and over like you did to find izcmd.

**Comment by JohnMagdy** [comment]
so no way to fix it

**Comment by rt-2** [comment]
I just told you how to, the problem is on your side, you have o find the conflict yourself.
