### ISSUE TITLE
Kicking for Health Hack because of weapon-config.inc

### ISSUE THREAD

**Issue by XpDeviL** [NexiusTailer/Nex-AC#44]
I'm using weapon-config include. And it has it's own health system. So Nex-AC is kicking me for health hack. How can i fix this or disable health hack protection? 
(I already tried setting 0 to 12. and 13. options in nex-ac_settings.cfg. But it didn't work)

**Comment by NexiusTailer** [comment]
How did you try to disable these anticheats in the config file?

![image](https://user-images.githubusercontent.com/13169094/27291566-3f33ea14-5519-11e7-827a-292b7c49fa78.png)
In this scheme the highlighted value is the trigger for turning on/off the anticheat number 18 (the number of anti-cheat for enabling/disabling is behind '//')

**Comment by XpDeviL** [comment]
In the inc file, it says 12. and 13. options are health and armour protections. 
https://i.imgur.com/mq3QRug_d.jpg?maxwidth=640&shape=thumb&fidelity=high

I made them value to 0.
https://i.imgur.com/3m5itiN_d.jpg?maxwidth=640&shape=thumb&fidelity=high

But it didn't worked.
What do you mean by EnableAntiCheat? Is it effects whole anti-cheat or some features?

**Comment by NexiusTailer** [comment]
> But it didn't worked.

Perhaps the encoding of the file was changed... Try to edit it on the computer


> What do you mean by EnableAntiCheat? Is it effects whole anti-cheat or some features?

This function allows you to disable or enable a specific anticheat code for all players on the server (there is also for one player - EnbaleAntiCheatForPlayer). See the "[Functions](https://github.com/NexiusTailer/Nex-AC#functions)" section in description for more information about them.

**Comment by XpDeviL** [comment]
Thanks for the answers. I will try it as soon as possible and write here the consequence.

**Comment by XpDeviL** [comment]
Where can i find the IDs of the anti-cheats? If health and armor IDs are 12 and 13, EnableAntiCheat didn't work. I tried 12 and 13.

**Comment by NexiusTailer** [comment]
@XpDeviL You can see it [here](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9/v1.9.26/r2/nex-ac.inc#L140-L197).

Take a look at the arguments of this function:

EnableAntiCheat(
* acid - Anti-cheat  ID to enable/disable
* enable - toggle anti-cheat (1 - enable, 0 - disable)      

);

**Comment by XpDeviL** [comment]
I tried EnableAntiCheat(12, 0); but it didn't work? Also tried id 13.

**Comment by NexiusTailer** [comment]
Which way does not work: it doesn't disable the code (IsAntiCheatEnabled still returns 1 for this code) or it is disabled, but the punish still go?

**Comment by XpDeviL** [comment]
![1](https://user-images.githubusercontent.com/20479749/28209884-4c918918-689d-11e7-8129-46c508e101a4.PNG)
![2](https://user-images.githubusercontent.com/20479749/28209885-4c9cfd2a-689d-11e7-95a9-71ec13ef637c.PNG)

Here's the debug.

**Comment by NexiusTailer** [comment]
You are kicked by the code 52 (this is protection from NOPs). You can disable this code separately if it's necessary
