### ISSUE TITLE
CreateDynamicVehicle

### ISSUE THREAD

**Issue by harrwe** [NexiusTailer/Nex-AC#47]
Приветствую, можете добавить поддержку CreateDynamicVehicle (http://forum.sa-mp.com/showthread.php?t=580937) в античите, а то при каждом обновление переписывать античит не хочется.

**Comment by NexiusTailer** [comment]
Планирую добавить примерно в v1.9.28
Если не сложно, как-нибудь всё-же скинь наработки)

**Comment by Romz24** [comment]
Зачем? Его вроде никто не юзает.
