### ISSUE TITLE
Bug with OnPlayeriveDammage

### ISSUE THREAD

**Issue by R0ot16** [NexiusTailer/Nex-AC#49]
v1.9.27
Hi,
C:\xampp\htdocs\lsmem\pawno\include\nex-ac.inc(3097) : warning 202: number of arguments does not match definition
C:\xampp\htdocs\lsmem\pawno\include\nex-ac.inc(3111) : error 025: function heading differs from prototype
with :
#include <a_samp>
#include <a_mysql>
#include <YSI\y_hooks>
#include <progress>
#include <eSelection>
#include <easyDialog>
#include <zcmd>
#include <sscanf2>
#include <geolocation>

how i can fix this ? 
thanks

**Comment by R0ot16** [comment]
hmmm.. i'm sorry, problem with my GM , not with nex-ac.. time to sleep, i think.

**Comment by NexiusTailer** [comment]
Next time, look, what public is on the line with an error, in this case it is:
```
OnPlayerGiveDamage(playerid, damagedid, Float:amount, weaponid, bodypart)
```
and then find this public in your script and check the correctness of your arguments in it, I think you're missed this:
> bodypart
