### ISSUE TITLE
Only 1 warning

### ISSUE THREAD

**Issue by Terzic123** [NexiusTailer/Nex-AC#50]
pawno\include\nex-ac.inc(4797) : warning 201: redefinition of constant/macro (symbol "OnPlayerPickUpDynamicPickup")

How to solve this problem, please help me. 
I solved all errors and warnings but this i can not.
Thank you if you can help me :) <3

**Comment by NexiusTailer** [comment]
Find includes which also hooks this public (OnPlayerPickUpDynamicPickup) and which is included before the anticheat, and then make an hook method similar to [ALS Hook Method 7](http://forum.sa-mp.com/showthread.php?t=570910) in this includes.
