### ISSUE TITLE
redefinition and prototype differ 

### ISSUE THREAD

**Issue by JokersNight** [NexiusTailer/Nex-AC#51]
F:\Works\Serevr\pawn-editor\include\nex-ac.inc(2332) : warning 201: redefinition of constant/macro (symbol "RepairVehicle")
F:\Works\Serevr\pawn-editor\include\nex-ac.inc(4660) : warning 202: number of arguments does not match definition
F:\Works\Serevr\pawn-editor\include\nex-ac.inc(4674) : error 025: function heading differs from prototype
F:\Works\Serevr\pawn-editor\include\nex-ac.inc(6029) : warning 201: redefinition of constant/macro (symbol "OnVehicleDamageStatusUpdate")

these are the errors coming up  
i have took the 1.9.27 version nex-ac

**Comment by NexiusTailer** [comment]
See #50 and #49
