### ISSUE TITLE
 could?

### ISSUE THREAD

**Issue by BrasilianZ** [NexiusTailer/Nex-AC#52]
Could you do an anti-airbreak for those versions where the speed of the player always returns to `0.0`? Example on S0beit Slono Boyko when using AirBreak, GetPlayerVelocity returns to `0.0`

**Comment by NexiusTailer** [comment]
It is already done and this kind of airbreaks detects by anti-teleport or by anti-airbreak.

**Comment by BrasilianZ** [comment]
I know this, but my server has basic systems and so I need something more precise to detect before the player even wiggles

**Comment by NexiusTailer** [comment]
I think in either ways anticheat should pass a few times when there is a suspection on this kind of airbreak hack to prevent possible false detections.
