### ISSUE TITLE
Filterscript

### ISSUE THREAD

**Issue by BrasilianZ** [NexiusTailer/Nex-AC#53]
### I did this in filterscript but when compiling, the FS did not exceed 152kb

```
#include <streamer>
#include <foreach>
#include <YSI\y_utils>
#include <YSI\y_va>
#include <YSI\y_timers>
#include <YSI\y_hooks>

#define FILTERSCRIPT

#include <nex-ac>
```

**Comment by NexiusTailer** [comment]
It works: anticheat (being connected to the filterscript) hooks its functions and sends them to the gamemode. That's why the size of the filterscript isn't as large as the size of the gamemode with the main anticheat module
