### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BrasilianZ** [NexiusTailer/Nex-AC#55]
Is it possible to extract Anti-Airbreak from this include? I just need him :(

**Comment by NexiusTailer** [comment]
Yes, I think it's possible.

Check these lines:
https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9/v1.9.28/r2/nex-ac.inc#L4433-L4446
https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9/v1.9.28/r2/nex-ac.inc#L4161-L4175

**Comment by BrasilianZ** [comment]
there are more things missing

**Comment by NexiusTailer** [comment]
This is just the main part of the code, the core which I posted on the links above. Of course, you will have to fully explore its working principle in order to find and extract all the code that relates to it.
