### ISSUE TITLE
[bug] PutPlayerInVehicle

### ISSUE THREAD

**Issue by reAL128** [NexiusTailer/Nex-AC#56]
После использования **PutPlayerInVehicle**
В данном транспорте HP устанавливается на 0 и срабатывает естественно античит:

**[Nex-AC debug] AC veh health: 0.000000, veh health: 1000.000000, vehicleid: ????, playerid: 0**

Тестировалось на дефолтном **grandlarc.pwn**

UPD: работает не только с **PutPlayerInVehicle**, если сесть просто в машину - HP тоже на 0 ставит.
Если через пару секунд сесть в тоже самое авто, хп не изменяется.
P.S. Машины созданы через **AddStaticVehicleEx** 

Video:  https://youtu.be/TJsJ-FAinuU

**Comment by NexiusTailer** [comment]
Стоит проверить наличие других фильтрскриптов с кодом, который и даёт при входе в авто 0 хп. Либо если таковых нет - проверить, не в клиенте ли дело, т.к. явно видно по посадки в авто, что хп у неё 1000.0. Попробуй для этого сделать тоже самое без подключения античита.
Также лучше поставить на всякий случай crashdetect.

**Comment by reAL128** [comment]
**crashdetect** ничего не подсказывает.

Проверил только что без античита, всё превосходно, других **FS** не были подключены.

Вывод: проблема в библиотеке с античитом (возможно это не так)

**Comment by reAL128** [comment]
В общем, убрал все плагины, оставил только **grandlarc** + **nex-ac.inc**

Всё так же HP на 0

**Comment by NexiusTailer** [comment]
Проблема была как раз в порядке подключения античита, нужно вот так:
```
#include <a_samp>
#include core
#include float
#include "../gamemodes/nex-ac.inc"
#include "../include/gl_common.inc"
#include "../include/gl_spawns.inc"
```
