### ISSUE TITLE
Run time error 6: "Invalid instruction" in public OnPlayerConnect ()

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#57]
Hi, so I recently updated and got this error:
```
[09/11/2017 11:28:34] [connection] incoming connection: 96.22.69.173:62426 id: 1
[09/11/2017 11:28:36] [join] Yanick_Coulombe has joined the server (1:96.22.69.173)
[09/11/2017 11:28:36] [debug] Run time error 6: "Invalid instruction"
[09/11/2017 11:28:36] [debug]  Unknown opcode 0x78000000 at address 0x00000005
[09/11/2017 11:28:36] [debug] AMX backtrace:
[09/11/2017 11:28:36] [debug] #0 00000000 in public OnPlayerConnect ()
```
with this gamemode, but it seems to only do the error when the second player connects:
```
#include <a_samp>
#include <YSI\y_hooks>
#include <nex-ac>
main() { }
```
Everything seems to work normally after that...
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
What compiler are you using and what version of samp also?
If you're using Zeex's Compiler, please specify it's version.

**Comment by rt-2** [comment]
Last version of samp I think.
And here is the compiler window content:
```
Pawn compiler 3.10.4	 	 	Copyright (c) 1997-2006, ITB CompuPhase

Header size:           7864 bytes
Code size:           449972 bytes
Data size:           496244 bytes
Stack/heap size:      16384 bytes; estimated max. usage=1992 cells (7968 bytes)
Total requirements:  970464 bytes

```

**Comment by NexiusTailer** [comment]
Try to update YSI

**Comment by rt-2** [comment]
I also tried to update YSI today before doing the test

**Comment by NexiusTailer** [comment]
It seems that yes.
Using the latest version of YSI and zeex's compiler everything is fine.
![image](https://user-images.githubusercontent.com/13169094/32621697-b0a54de4-c591-11e7-9666-1a8d55410b8c.png)

Also I would like to clarify: are the above logs made in the -d3 mode?
You can also share the archive with your test server, where this problem occurs (with YSI, compiler, all includes, etc.).

**Comment by NexiusTailer** [comment]
s the problem still relevant? Can we check it on your side (or can I somehow get the compiled/source files that having this problem)?

**Comment by rt-2** [comment]
Yes I'm sorry I haven't had time yet, was working all week end.
I will send you that.

**Comment by rt-2** [comment]
Here is an archive to test http://sa-arp.net/invalid_on_connect.7z
Also I doscovered that you absolutely need crashdetect to detect any problem,, otherwise it just seems alright.
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
You should disable y_hooks before nex-ac and check it again, because I think that the problem somewhere in y_hooks, probably... (Actually I found a similar problem where y_hooks was also used and caused this) Zeex/samp-plugin-crashdetect#6

**Comment by rt-2** [comment]
Ok but you were the one that previously told me to place y_hooks right before nex-ac....
Should I start an issue on YSI's repo?
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
Nex-AC uses y_hooks if anticheat sees that y_hooks is connected (so y_hooks must be connected before anticheat for this). I asked to disable it only in this situation, because it is obvious that there is nothing more to provoke this error except y_hooks. Therefore, I think so, you should send some information to the YSI repository on this issue (if it really disappears after disabling y_hooks).

**Comment by Zile420** [comment]
I also have this problem
And I realized that it did not YSI \ y_ini or YSI\y_hooks anyhow together

**Comment by Zile420** [comment]
These two can not function

**Comment by Zile420** [comment]
i think you created a fucking error in latest version

**Comment by NexiusTailer** [comment]
Well, if this error occurs in several people, then apparently it really was my mistake somewhere. Another question that might help me to find it: Do you have this problem if the sandbox protection (code 40) is disabled?

**Comment by rt-2** [comment]
I havent had time to write an issue on YSI's repo yet, Im really more into work and have less time for samp,,,
Do you still think it's a YSI issue? I could try to write one tonight maybe?
rt-2

**Comment by NexiusTailer** [comment]
@rt-2 Try to disable anticheat code 40 (sandbox protection) and just test again: if the problem will no longer be, then it is my mistake in last release and I will try to fix it (but I'm not sure in it for now)

**Comment by NexiusTailer** [comment]
It seems I found the problem and I think this is fixed in 1.9.29

**Comment by rt-2** [comment]
I just tried with the last version and it is fixed

**Comment by rt-2** [comment]
When I use 1.9.32 with an empty gamemode, I have this bug again, sometimes on the first connection, sometimes on the second connection.
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
@rt-2 This time I have no idea what the problem may be, except in YSI

**Comment by rt-2** [comment]
Ok next time I work on SAMP I will investigate toward YSI,
Thank you,
rt-2
