### ISSUE TITLE
 warning 200: symbol  truncated to 31 characters

### ISSUE THREAD

**Issue by Marcoddx** [NexiusTailer/Nex-AC#58]
Привет, тут у тебя ошибочки, идет более 31 символа в названии, исправь в дальнейшем. =) 
`nex-ac.inc(5998) : warning 200: symbol "_ALS_OnPlayerEnterRaceCheckpoin" is truncated to 31 characters
nex-ac.inc(6035) : warning 200: symbol "_ALS_OnPlayerLeaveRaceCheckpoin" is truncated to 31 characters
nex-ac.inc(6076) : warning 200: symbol "_ALS_OnPlayerClickPlayerTextDra" is truncated to 31 characters
nex-ac.inc(6117) : warning 200: symbol "_ALS_OnVehicleDamageStatusUpdat" is truncated to 31 characters
nex-ac.inc(6202) : warning 200: symbol "_ALS_OnPlayerSelectDynamicObjec" is truncated to 31 characters`

**Comment by NexiusTailer** [comment]
Привет, эти ошибки скорее всего вызваны другими инклудами. Покажи весь их список, который у себя подключаешь.
