### ISSUE TITLE
Nex-ac versioning

### ISSUE THREAD

**Issue by Mrucznik** [NexiusTailer/Nex-AC#61]
Why don't you use git versioning for nex-ac.inc file?
I think it would be better, to have one file, and creating releases in https://github.com/NexiusTailer/Nex-AC/releases.
With that, users of Nex-AC will be able to see changes in code on the github page.

**Comment by Jeroen52** [comment]
I also wondered why this was a thing, it kinda defeats the purpose of Git.

**Comment by NexiusTailer** [comment]
So, I made a little bit different thing: now users will have only one version in the current repository branch, while all previous versions can be accessed in the commits history.
