### ISSUE TITLE
Location nex-ac in script

### ISSUE THREAD

**Issue by Mariusik1800** [NexiusTailer/Nex-AC#62]
Before it's what must be placed (streamer) and what more?

**Comment by NexiusTailer** [comment]
[Streamer plugin](https://github.com/samp-incognito/samp-streamer-plugin), [foreach](https://github.com/karimcambridge/SAMP-foreach), [y_hooks](https://github.com/Misiur/YSI-Includes), [Timerfix plugin by Dan](https://github.com/udan11/samp-plugin-timerfix) (if it's used) and [sscanf](https://github.com/maddinat0r/sscanf) must be included before anticheat.
