### ISSUE TITLE
y_hooks issue

### ISSUE THREAD

**Issue by demon-debjit** [NexiusTailer/Nex-AC#63]
Directory\pawno\include\nex-ac.inc(2690) : error 021: symbol already defined: "@yH_OnGameModeInit@002"
Directory\pawno\include\nex-ac.inc(2694) : error 021: symbol already defined: "@yH_OnGameModeInit@002"
Directory\pawno\include\nex-ac.inc(2741) : error 021: symbol already defined: "@yH_OnGameModeExit@002"
Directory\pawno\include\nex-ac.inc(2745) : error 021: symbol already defined: "@yH_OnGameModeExit@002"
Directory\pawno\include\nex-ac.inc(2778) : error 021: symbol already defined: "@yH_OnPlayerConnect@002"
Directory\pawno\include\nex-ac.inc(2782) : error 021: symbol already defined: "@yH_OnPlayerConnect@002"
Directory\pawno\include\nex-ac.inc(2884) : error 021: symbol already defined: "@yH_OnPlayerDisconnect@002"
Directory\pawno\include\nex-ac.inc(2888) : error 021: symbol already defined: "@yH_OnPlayerDisconnect@002"

**Comment by NexiusTailer** [comment]
You should include y_hooks in every script.
