### ISSUE TITLE
Modular Gamemode

### ISSUE THREAD

**Issue by Sanady** [NexiusTailer/Nex-AC#64]
Hello, I post question on SA-MP forum but no body replies :D never mind, I am using modular gamemode, in which I am using OnPlayerSpawn in separate module. But when I respawn after death I got kicked out for Ammo hack (infinity), I tried to include anticheat into module but no result, still same issue, so now I am asking is nex-ac working on modular gamemodes?

**Comment by NexiusTailer** [comment]
Hello. What do you mean by "modular"? Does this mode consists of different filterscripts or includes as modules? Show me please how (in which order) and where do you include the anticheat and also show the structure of the mode (ie what modules it consists of)

**Comment by Sanady** [comment]
It consists includes as modules. 

#include "./PwFItems/TeamBalancer.pwn"
#include "./PwFItems/TeamInfo.pwn"
#include "./PwFItems/TeamZones.pwn"

**Comment by NexiusTailer** [comment]
Try to include anticheat before any module.

**Comment by NexiusTailer** [comment]
Ok, then show what you see in the console when kicking, i.e. what exactly anticheat displays.
