### ISSUE TITLE
Ложное срабатывание античита 002

### ISSUE THREAD

**Issue by harrwe** [NexiusTailer/Nex-AC#66]
_Описание бага:_ 
Если человек выйдет из afk из машины которая передвигалась пока он был afk его кикнет.

_Выполнение бага:_ 
Для осуществление бага нужны 2 человека и ТС. 
- 1 человек садится за руль
- 2 человек садится на пассажирское место. 
- 2 человек (Пассажир) входит в afk.
- 1 человек (Водитель) уезжает далеко.
- 1 человек (Водитель) выходит из ТС.
- 2 человек (Пассажир) выходит из afk.
- 2 человек (Пассажир) выходит из ТС.

2 человека (Пассажира) кикает античит с кодом **002**

**Comment by NexiusTailer** [comment]
Данная проблема проверялась только на локальном сервере через песочницу, или действительно была при тестировании двумя разными игроками?

Проверил у себя на песочнице - сработало, но там проблема непосредственно в рассинхроне пассажира, потому что в первый раз при выходе из афк он посылает OnUnoccupiedVehicleUpdate со старой позицией до афк, и машину с ним тпхает на её реальное место, а во всех последующих попытках он уже почему-то просто перестаёт посылать что-либо серверу и сам новые данные не синхронизирует. Собственно поэтому мне и кажется, что проблема тут именно в использовании песочницы.

**Comment by harrwe** [comment]
Тестировал на локальном, но с 2 реальными игроками.

**Comment by NexiusTailer** [comment]
Тогда ставь как наказание именно за этот чит телепорт обратно.

**Comment by NexiusTailer** [comment]
Проверил это также с другим тестером, и его при выходе из афк на пассажирском месте в незанятой тачке античит тпхает вместе с этой тачкой на её реальную позицию (код 005, где как наказание тп на реальную позицию стоит вместо кика по умолчанию), причём тпхает обратно его при каждой попытке.
