### ISSUE TITLE
Nex-Ac Compile Errors

### ISSUE THREAD

**Issue by earltacs** [NexiusTailer/Nex-AC#67]
You've made some errors and typo's

> C:\Users\Joker\Documents\GitHub\EHRP\pawno\include\nex-ac.inc(1597) : warning 219: local variable "infoo" shadows a variable at a preceding level
C:\Users\Joker\Documents\GitHub\EHRP\pawno\include\nex-ac.inc(5920) : error 017: undefined symbol "DEBUG"
Pawn compiler 3.10.6	 	 	Copyright (c) 1997-2006, ITB CompuPhase

And this one

>4 Errors.
C:\Users\Joker\Documents\GitHub\EHRP\pawno\include\nex-ac.inc(5920) : error 029: invalid expression, assumed zero
C:\Users\Joker\Documents\GitHub\EHRP\pawno\include\nex-ac.inc(5920 -- 5922) : error 057: unfinished expression before compiler directive
C:\Users\Joker\Documents\GitHub\EHRP\pawno\include\nex-ac.inc(5920 -- 5922) : fatal error 107: too many error messages on one line
Compilation aborted. 

This is the version
> #define	NEX_AC_VERSION				"1.8.8"

so I think my issue is done... Hope it gets updated soon :)

It's fixed on my end though
`#undef DEBUG` I removed that, but I'm still trying to replace it and find ways to fix it

But I don't where I got this?
>C:\Users\Joker\Documents\GitHub\EHRP\gamemodes\ehrp.pwn(1592) : warning 203: symbol is never used: "args"
C:\Users\Joker\Documents\GitHub\EHRP\gamemodes\ehrp.pwn(1589) : warning 203: symbol is never used: "string"

I don't have unused args, nor used the varable args on my gamemode and have not had an unused string on my script either. I got this error after updating to the 1.8.8 version of the ac

EDIT:
I found the symbol is never used though... I fixed everything too...

but the `#undef DEBUG` though, I don't know how it works yet. Can I have some brief or little explanation why it got undefined but not redefined on that line?

**Comment by NexiusTailer** [comment]
At first, look at this:
https://github.com/NexiusTailer/Nex-AC/blob/ca1e17ee26f1ee57db2148031deadc137173cdad/src/v1.9/v1.9.32/r2/nex-ac.inc#L7031-L7034
Undefine is used only inside the check if this define exists. This is done to ensure that all the following included scripts that will suddenly have a define with the same name will not give any errors with the fact that they coincide.

**Comment by earltacs** [comment]
Ahhh okay.. I get it now thanks for that...
