### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by alterego29** [NexiusTailer/Nex-AC#68]
Why are you guys not using
`OnIncomingConnection(playerid, ip_address[], port)`?

It should be better since it gets called first before `OnPlayerConnect(playerid)`

I've tried created and tested my own anti-flood and anti-dos using both and OnIncomingConnection really works better at getting the ip and checking, imo wise. Of course your check would be different than mine, but that's just a question and my own comparison at the least. Maybe it'll spark an idea for the nex-ac

**Comment by NexiusTailer** [comment]
OnIncomingConnection doesn't allow you to get anything except playerid and IP. Any functions like IsPlayerNPC and GetPlayerVersion will return incorrect data (just 0 or nothing, if it's a string), so in my case this public is practically useless.

**Comment by alterego29** [comment]
Ahhh... I do get the point, I forgot that NPC are also allowed to join the server...

`announce 0
chatlogging 0
weburl www.ehrp.com
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
maxnpc 0
logtimeformat [%H:%M:%S]
language English`
but doesn't it that the server blocks any ip connection that has NPC labelled on it when it is set to 0 on NPC configuration or when the NPC within the server is equal to the number of set maximum npc's? That's how I think it works though...

and doesn't it that the server already checks the server version from the beginning not allowing any packet to be sent towards the client, basically not allowing the player to fully connect into the server???

or does the check only works on your anti-cheat to make sure that the version was not spoofed just to get through? sorry for the bother though... I'm just curious...

**Comment by NexiusTailer** [comment]
> or does the check only works on your anti-cheat to make sure that the version was not spoofed just to get through? sorry for the bother though... I'm just curious...

I think the version can be spoofed even with these checks, but it's better if this protection was, than if it was not at all. In the end, you can just look at the code in OnPlayerConnect: most of it is just resetting the variables to its default values for the logged-in player, and there's no point in moving them to OnIncomingConnection.

And about NPC, I think you should test it yourself :)
The fact that I can't get any player data like IsPlayerNPC in this public isn't very attractive for moving protections from OnPlayerConnect.

**Comment by alterego29** [comment]
Okay then I might do some testing on my own and find out how things work.. There's no better way than testing the waters on my own :) thanks by the way and I've tested some of your nex-ac already and most are working fine. I'm looking for bugs or problems to report though... 👍
