### ISSUE TITLE
Anti Ammo Hack

### ISSUE THREAD

**Issue by PatchwerkQWER** [NexiusTailer/Nex-AC#7]
Hi,

There's problem with anti ammo hack (detonator). When I have 50x "Satchel Charge" and I drop 5 bombs I get detonator - it's okay. But when I detonate the bombs I have still detonator because I have still 45x "Satchel Charge" but AC kick me for ammo hack (add) [detonator]. 

In simplicity: When I have still "Stachel" detonator doesn't remove after use. 

Cheers

**Comment by NexiusTailer** [comment]
Thank you, I'll fix this in the next update! :)

**Comment by PatchwerkQWER** [comment]
I have tip for better dialog crash (%)
```
	if(AntiCheatInfo[playerid][acACAllow][45])
	{
               for(new i, l = strlen(inputtext); i < l; i++){
                         if(inputtext[i] == '%') inputtext[i] = '#';
               }
	}
```

Cheers

**Comment by NexiusTailer** [comment]
I spent some of the tests, from which it follows that:
...
[17:54:29] 1: 436 ms
[17:54:29] 2: 169 ms
...

Code:
...

	new inputtext[128] = "dfdfshjdsfJHbjhdfsHH6467%s43HHGG56jdfgksdfjk45dkgFdsg";
	new gtc = GetTickCount();
	for(new j; j < 100000; j++)
	{
		for(new i, l = strlen(inputtext); i < l; i++)
		{
			if(inputtext[i] == '%') inputtext[i] = '#';
		}
	}
	printf("1: %d ms", GetTickCount() - gtc);
	new ac_i;
	gtc = GetTickCount();
	for(new i; i < 100000; i++)
	{
	    while((ac_i = strfind(inputtext, "%")) != -1) strdel(inputtext, ac_i, ac_i + 1);
	}
	printf("2: %d ms", GetTickCount() - gtc);

...
