### ISSUE TITLE
Данный античит включает в себя защиту от всех типов крашеров игроков на 0.3.7?

### ISSUE THREAD

**Issue by ronixtey** [NexiusTailer/Nex-AC#70]

**Comment by NexiusTailer** [comment]
Которые вредят игрокам непосредственно - да, защиты от них всех присутствуют. Возможна работа недавно вышедшего крашера через команду /kiss (если она есть на сервере), но там, как я понимаю, читер всего лишь ставит себе невалидный угол поворота, а сервер не делая никаких проверок в команде узнаёт её у него и ставит другому игроку (в результате чего жертву крашит, а читер остаётся на сервере, т.к. у него встроенный анти-крашер). Собственно, это по сути единственное, что античит пока не предотвращает непосредственно, но я думаю что это уже в первую очередь лучше проверять в самой команде /kiss (угол поворота читера там равен NaN).

**Comment by NexiusTailer** [comment]
Не очень понял что такое Лагшот (lagcomp ты наверное имел в виду), но если он включен - то анти-weapon crasher имеется и будет работать. От bullet crasher'а защита уже в 0.3.7 нативная вроде как. При выключенном lagcomp режиме, соответственно, защиты не работают, поскольку и в крашерах смысла нет.

**Comment by ronixtey** [comment]
да, имел ввиду если lagcompmode = 0, стрельба по пингу

**Comment by ronixtey** [comment]
на сервере игроков крашат, и по заявлению самих крашеров у них Weapon и Bullet crash, на сервере выключен lagcompmode

**Comment by NexiusTailer** [comment]
Ну если они вызывают OnPlayerWeaponShot с выключенным lagcompmode, значит по идее их должен кикнуть анти-lagcomp spoof (защита от вызова OnPlayerWeaponShot на серверах, где он отключен).

**Comment by ronixtey** [comment]
я просто не ставил сей античит, спасибо за ответ
надеюсь этот spoof поможет
