### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by iamaul** [NexiusTailer/Nex-AC#71]
```
[30/03/2018 11:29:08] [debug] Server crashed while executing dm.amx
[30/03/2018 11:29:08] [debug] AMX backtrace:
[30/03/2018 11:29:08] [debug] #0 00000005 in public ac_OnPlayerConnect (0) from dm.amx
[30/03/2018 11:29:08] [debug] #1 0000b6ec in ?? (0, 1, 0, 0, 4, 0, 0, 0, 0, 0, ... <1073741813 arguments>) from dm.amx
[30/03/2018 11:29:08] [debug] #2 0003c630 in public OnPlayerConnect () from dm.amx
```

My server crashed while connecting to the server and I logged with crashdetect. I guess those crashes appears from Nex-AC **ac_OnPlayerConnect**

My OnPlayerConnect:
```
#include <YSI\y_hooks>

hook OnPlayerConnect(playerid)
{
    RaceCheck[playerid]++;
    ResetPlayerData(playerid);
    LoadPlayerTextdraws(playerid);
    TogglePlayerSpectating(playerid,1);
    CheckPlayer(playerid);
    return 1;
}
```

**Comment by NexiusTailer** [comment]
Give me the code of ResetPlayerData, LoadPlayerTextdraws and CheckPlayer functions and also what dependencies (includes) you use?

**Comment by iamaul** [comment]
Here you go: https://gist.github.com/iamaul/4f20c85a44311dd95dab40655b23ff4c, I am currently using the latest Nex-AC version. 

these are my includes order: https://imgur.com/a/V9q1F

**Comment by NexiusTailer** [comment]
YSI and especially y_hooks should be included before the anticheat.

**Comment by iamaul** [comment]
I placed nex-ac before YSI includes, take a look at my includes

**Comment by iamaul** [comment]
Ok, I defined anticheat before the anticheat now but still have this issue:
```
[30/03/2018 14:46:40] [debug] Server crashed while executing dm.amx
[30/03/2018 14:46:40] [debug] AMX backtrace:
[30/03/2018 14:46:40] [debug] #0 00000005 in ?? (0, 1, 0, 0, 4, 0, 0, 0, 0, 0, ... <1073741813 arguments>) from dm.amx
[30/03/2018 14:46:40] [debug] #1 00010680 in public OnPlayerConnect () from dm.amx
```
I don't even have OnPlayerConnect in the script dm.amx

**Comment by NexiusTailer** [comment]
I'm sure that something that have emits in itself causes this problem. I think this is one of the YSI libraries (maybe y_hooks)

**Comment by iamaul** [comment]
previously, my gamemode isn't structured and not having y_hooks at all and it works. Now, I rewrite the gamemode to module and uses y_hooks

**Comment by iamaul** [comment]
Previously, my gamemode isn't structured and not having y_hooks at all and it works. Now, I rewrite the gamemode to module and got this issues (y_hooks). Yeah probably y_hooks causes this shit, unless I changed the way to not using y_hooks and hooks manually every callbacks, hell na. You should fix these problems

**Comment by NexiusTailer** [comment]
I don't know what I should fix as anticheat doesn't use any emits in OnPlayerConnect (and anywhere else), and also there is no any unsafe code in OnPlayerConnect.

**Comment by iamaul** [comment]
Ah aight then, going to remove y_hooks! 👎
