### ISSUE TITLE
Плохо работает античит на speedhack?

### ISSUE THREAD

**Issue by reAL128** [NexiusTailer/Nex-AC#77]
Тестировалось как на localhost так и на хостинге.
Совершенно странно ловит speedhack.

Вот видео: https://www.youtube.com/watch?v=X59LU5qYkVU

Возможно, я что-то не так делаю.

**Comment by NexiusTailer** [comment]
Там всё немного сложнее. Как ты заметил в видео, варнинги для спидхака по умолчанию включены (и выставлены на максимум в 1), оттого при такой настройке античит на спидхак ловит его только после второй попытки (т.к. максимум подозрений на него 1, то соответственно > 1 уже детект), а обнуляются эти варнинги раз в 3 секунды, т.е. при таком раскладе необходимо два рывка в 20 км за три секунды. Сделано это для предотвращения ложных срабатываний, когда при врезании одного более массивного транспорта в другой, второй мог сильно отлетать с водителем внутри, резко прибавляя скорость, за что водителя второго тс кикало за сх. При введении варнингов такие ситуации прекратились, но и детект также ухудшился.

Тут уже либо делать без варнигов, но с сообщением администрации, либо закрывать глаза на ситуации с ложными при авариях, либо оставлять как есть сейчас. И кстати на детект также влияет то, что сх в этом собейте довольно плавный, отчего скачки скорости там происходят не часто.

**Comment by reAL128** [comment]
Днём сниму видео, как из-за этого спидхака ловит невиновного за него.
Постараюсь в ситуации хостинга тестировать
