### ISSUE TITLE
Nex-AC 

### ISSUE THREAD

**Issue by AlexJemison** [NexiusTailer/Nex-AC#80]
Здравствуйте . Обновил античит к версии v1.9.36 . И здесь выскочило несколько ошибок. Как решить. К этому использовал версию 1.9.20 . Мод Arizona RP . 

`C:\Users\Jemison\Desktop\SAMP\Life Mod\pawno\include\nex-ac.inc(3130) : warning 202: number of arguments does not match definition
C:\Users\Jemison\Desktop\SAMP\Life Mod\pawno\include\nex-ac.inc(3144) : error 025: function heading differs from prototype
C:\Users\Jemison\Desktop\SAMP\Life Mod\pawno\include\nex-ac.inc(3165) : warning 202: number of arguments does not match definition
C:\Users\Jemison\Desktop\SAMP\Life Mod\pawno\include\nex-ac.inc(3179) : error 025: function heading differs from prototype
C:\Users\Jemison\Desktop\SAMP\Life Mod\pawno\include\nex-ac.inc(7101) : error 017: undefined symbol "SUSPICION_2"
C:\Users\Jemison\Desktop\SAMP\Life Mod\pawno\include\nex-ac.inc(7102) : error 017: undefined symbol "SUSPICION_1"
C:\Users\Jemison\Desktop\SAMP\Life Mod\gamemodes\mrp.pwn(66962) : symbol is never used: "CheatKick"`

 Варнинг 1
forward _SetGun(playerid, weaponid, ammo);
public _SetGun(playerid, weaponid, ammo)
{
	new slot = GetWeaponSlot(weaponid);
	if(slot == 0xFFFF) return false;

	gunmute[playerid] = gettime()+3;

	if(PI[playerid][pAmmos][slot] < 7)
	{
		PI[playerid][pGuns][slot] = 0;
		PI[playerid][pAmmos][slot] = 0;
		AmmoSlot[playerid][slot] = 0;
		WeaponInfo[playerid][weaponid] = false;
		AmmoInfo[playerid][weaponid] = 0;
		return 0;
	}
	WeaponInfo[playerid][weaponid] = true;
	AmmoSlot[playerid][slot] = ammo;
	AmmoInfo[playerid][weaponid] = AmmoSlot[playerid][slot];

	PI[playerid][pAmmos][slot] = ammo;
	PI[playerid][pGuns][slot] = weaponid;

	GivePlayerWeapon(playerid, weaponid, ammo);
	if(PI[playerid][pAmmos][slot]==0) PI[playerid][pGuns][slot]=0;
	return true;
}

Ошибка 
PI[playerid][pAmmos][slot] = ammo;
PI[playerid][pGuns][slot] = weaponid;

Варнинг 2 / 2 строчка
	GivePlayerWeapon(playerid, weaponid, ammo);
	if(PI[playerid][pAmmos][slot]==0) PI[playerid][pGuns][slot]=0;
	return true;

forward _ResetGun(playerid);
public _ResetGun(playerid)
{
	gunmute[playerid] = gettime()+3;
	ResetPlayerWeapons(playerid);
	for(new x; x < 13; x ++)
	{
		PI[playerid][pAmmos][x] = 0;
		PI[playerid][pGuns][x] = 0;
		AmmoSlot[playerid][x] = 0;
	}
 // Тут 3179
	for(new i = 0; i < 47; i++)
	{
		WeaponInfo[playerid][i] = false;
		AmmoInfo[playerid][i] = 0;
	}

	PI[playerid][pLastGun]=0;
	PI[playerid][pLastAmmo]= 0;
	return true;
}

7101-7102 строчка Здесь мапинг 
CreateDynamicObject(3850, 1747.603027, 443.424988, 19.628000, 0.000000, 0.000000, 176.000000, -1, -1);
CreateDynamicObject(620, 1833.163330, 383.032257, 10.492040, 0.000000, 0.000000, 22.520000, -1, -1);

**Comment by NexiusTailer** [comment]
Строчки, на которые жалуется компилятор, в античите а не в моде, соответственно ты посмотрел не на те.
Первые 4 варнинга и ошибки возникают из-за устаревших аргументах в пабликах. Для этого узнай названия пабликов на этих строчках в античите, затем найди их в моде и обнови в них аргументы. Также (если это не поможет) обнови все стандартные инклуды сампа.
Далее, ошибки связанные с незадефайненностью "SUSPICION_2" и "SUSPICION_1", скорее всего, возникли вследствие того, что у тебя не подключен .lang файл (хотя тогда античит должен был бы выдавать ошибку о его отсутствии) либо этот .lang файл был изменён и в нём отсутствуют "SUSPICION_2" и "SUSPICION_1".
Последний варнинг к античиту не относится.

**Comment by AlexJemison** [comment]
Решил последний Варнинг. Я забыл обновить перевод. Но как узнать названия пабликов . Мод я брал под основу . И здесь мало пока понимаю так как мало времени с ним работаю

**Comment by NexiusTailer** [comment]
Посмотреть на строчках ач, на которые были ошибки...

1. Строка 3130 и 3144: OnPlayerTakeDamage ->
Найти у себя в моде OnPlayerTakeDamage и проверить, чтобы его аргументы были такими (скорее всего у тебя не будет последнего - bodypart):
```
public OnPlayerTakeDamage(playerid, issuerid, amount, weaponid, bodypart)
```
2. Строка 3165 и 3179: OnPlayerGiveDamage ->
Найти у себя в моде OnPlayerGiveDamage и проверить, чтобы его аргументы были такими (скорее всего у тебя не будет последнего - bodypart):
```
public OnPlayerGiveDamage(playerid, damagedid, Float:amount, weaponid, bodypart)
```

**Comment by AlexJemison** [comment]
Спасибо . Теперь еще 2 ошибки . А что тут ?

```
C:\Users\Jemison\Desktop\SAMP\Мой сервер\Life Mod\pawno\include\nex-ac.inc(3130) : warning 213: tag mismatch
C:\Users\Jemison\Desktop\SAMP\Мой сервер\Life Mod\pawno\include\nex-ac.inc(3144) : error 025: function heading differs from prototype
C:\Users\Jemison\Desktop\SAMP\Мой сервер\Life Mod\gamemodes\mrp.pwn(66961) : symbol is never used: "CheatKick"
```

**Comment by NexiusTailer** [comment]
Первые две я уже скинул выше.

**Comment by AlexJemison** [comment]
Я в шоке. Заменил 2 паблик и были ошибки я написал прошлое сообщение. Здесь твоя ответил я решил проверить и я все же заменил. Пересмотрел, заняло 10 минут все идеально но есть ошибки. И тут я решаю еще раз заменить тем же текстом. Хотя я не понимал зачем это делаю. Так вот все хорошо, все работает. Осталось исправить одно предупреждение: CheatKick

> CheatKick(playerid,number,type)
> {
> 	new string[128];
> 	format(string, 128, "[АнтиЧит]:{FFFFFF} %s[%i] кикнут: Код: %i Тип: %i",Name(playerid),playerid,number,type);
> 	SendAdminsMessage(COLOR_RED,string,1);
> 	J_Kick(playerid);
> 	return true;
> }

А что здесь изменить

**Comment by NexiusTailer** [comment]
> Последний варнинг к античиту не относится.

И тем не менее можно просто перевести этот варнинг в переводчике и узнать, что от тебя хочет компилятор.

**Comment by AlexJemison** [comment]
Ну это раньше выводило сообщение о причине кика. Сейчас деактивировал сделал как комментарий. 
Спасибо Вам
