### ISSUE TITLE
Teleport hack

### ISSUE THREAD

**Issue by FilPix** [NexiusTailer/Nex-AC#81]
During the use of anti-cheat for several months I can not fix the false on 002 (2). I do not understand why a player can just go or run, but it will be false. And this is not the only code. Is it possible, when I for example use not intercepted function SetPlayerPos (for example), and its analogue SetPlayerPosEx (example!)?

`[Nex-AC debug] Distance: 125.640327, distance set: 442.642669, speed: 0.0, pos x, y, z: 1492.083984, -1114.626831, 135.828125`

`[Nex-AC debug] Distance: 147.814697, distance set: 154.001434, speed: 0.0, pos x, y, z: 1466.514648, -1020.560974, 24.287143`

`[Nex-AC debug] Distance: 30.025289, distance set: 839.902282, speed: 20.0, pos x, y, z: 1978.487792, -1176.328735, -10.000000`

**Comment by NexiusTailer** [comment]
So do you get false detections only when using SetPlayerPos(Ex) or it can be even without teleporting a player by the server? Also show the code of your hooked SetPlayerPos function and the code where you teleport any player (I need to the way you teleport him).

**Comment by FilPix** [comment]
Anticheat said that the player is suspected of teleporting. When I watch him, I see that a person is just running along the road and does not bother anyone. After a while, there may be another one on it, but he ran like that and ran.

I removed all my functions a couple of months ago and put it on native ones. As a result, the false became much less.

I no longer know what to do, because maybe the problem in my gamemode.

**Comment by FilPix** [comment]
Most often works when entering or leaving the interior and even with unstable ping.

**Comment by NexiusTailer** [comment]
Please recheck this issue on v1.9.37
