### ISSUE TITLE
Conflict with MySQL

### ISSUE THREAD

**Issue by XEGARE** [NexiusTailer/Nex-AC#82]
Привет. 
Конфликтует с MySQL:
`C:\server\pawno\include\a_mysql.inc(33) : error 001: expected token: "-identifier-", but found "="
C:\server\pawno\include\a_mysql.inc(38 -- 39) : error 029: invalid expression, assumed zero
C:\server\pawno\include\a_mysql.inc(38 -- 39) : warning 213: tag mismatch: expected tag "E_LOGLEVEL", but found none ("_")
C:\server\pawno\include\a_mysql.inc(38 -- 39) : error 008: must be a constant expression; assumed zero
Pawn compiler 3.10.8	 	 	Copyright (c) 1997-2006, ITB CompuPhase`

Если закоментить nex-ac, то все окей: 
`Pawn compiler 3.10.8	 	 	Copyright (c) 1997-2006, ITB CompuPhase`

MySQL R41-4. 
Nex-AC 1.9.38. 
Zeex Compiler - 3.10.8

**Comment by NexiusTailer** [comment]
Спасибо. Временное решение - a_mysql подключать перед античитом, в следующей версии попытаюсь это исправить.
