### ISSUE TITLE
Cheat code list with names

### ISSUE THREAD

**Issue by HaoSs07B** [NexiusTailer/Nex-AC#83]
Is there a list of the code numbers and theyr specific name ?
Thanks.

**Comment by NexiusTailer** [comment]
[Here](https://github.com/NexiusTailer/Nex-AC/blob/77eb67f522a80c3be37f0f78197fc427a0efec28/src/v1.9.38/r2/nex-ac.inc#L192-L249) (even if you have already found it yourself, I think it will be useful to someone who will also find this issue)
