### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by XEGARE** [NexiusTailer/Nex-AC#87]
Приветствую. Почему когда игрок использует пополнение ХП, то ему выставляется старое значение, а когда пополняет броню, то кикает?

**Comment by NexiusTailer** [comment]
Пополнение хп и брони каким образом происходит? Нужен конкретный код, который это воспроизводит.

**Comment by XEGARE** [comment]
Не правильно я выразился. Почему когда игрок  пополняет хп читами, то ставится старое значение, а когда броню, то кикает? Почему не сделать установку старого значения и для брони?

**Comment by NexiusTailer** [comment]
Когда игрок пополняет хп читами пешком, то его кикает также, как когда он пополняет броню читами пешком. Возвращает хп только транспорту, если игрок начитерил хп для него сидя в нём. Причина возвращения - читер может пополнить хп в каре и моментально выйти, а античит сработает лишь на следующего вошедшего в неё, т.е. именно потому кик там не вариант.

А почему по умолчанию у большинства остальных античитов (например, на то же хп и броню пешком) стоит кик - я считаю, так надёжнее. В любом случае каждое наказание по умолчанию можно изменить самостоятельно, используя OnCheatDetected из мода.

**Comment by XEGARE** [comment]
Понял. Принял. Благодарю за ответ.
