### ISSUE TITLE
#03 Anti-teleport hack (in vehicle)

### ISSUE THREAD

**Issue by PatchwerkQWER** [NexiusTailer/Nex-AC#9]
Hi,

I find bug. When someone is in vehicle and I teleport his somewhere without vehicle he will be kicked. Reason "#03 Anti-teleport hack (in vehicle)"

Solution: in ac_SetPlayerPos add check if player is in vehicle or just reset variable with saved vehicleid.

Cheers @NexiusTailer

**Comment by PatchwerkQWER** [comment]
Another bug @NexiusTailer 
Sometimes (im not sure why) I will be kicked after PutPlayerInVehicle. Same reason (id 3)

**Comment by PatchwerkQWER** [comment]
Here are some informations about PutPlayerInVehicle bug (003):

It kick me in `OnPlayerInteriorChange`
But i setplayerinterior before PutPlayerInVehicle
code:
```
				gCarSchoolVehicle[playerid] = CreateVehicle(456, -2164.1926,-2325.8091,30.6501,141.6458, 233, 233, -1);
				SetVehicleVirtualWorld(gCarSchoolVehicle[playerid], SCHOOL_VW+playerid);
				SetPlayerVirtualWorld(playerid, SCHOOL_VW+playerid);
				SetPlayerInterior(playerid, 0);
				PutPlayerInVehicle(playerid, gCarSchoolVehicle[playerid], 0);
```

**Comment by NexiusTailer** [comment]
When I tested the second case, it hasn't been anything like it.
In any case, I increased the delay (after which the anticheat again checks the position). I hope this helps..
