### ISSUE TITLE
SAMP 0.3-DL support

### ISSUE THREAD

**Issue by infin1tyy** [NexiusTailer/Nex-AC#90]
I don't really understand what differs between 0.3.7 R1 and R2 but I see there is no option to use 0.3-DL. Could you add support for it - thank you.

**Comment by NexiusTailer** [comment]
The main difference between r1 and r2 releases is the use of new public OnTrailerUpdate and some new functions like GetConsoleVarAs... instead of deprecated GetSeverVarAs...
I don't think that 0.3DL is a full-fledged release, because the developer didn't even bother to post it on the official site. But still you can use the version for 0.3.7 R2. As far as I've tested, it's absolutely compatible.

**Comment by infin1tyy** [comment]
Issue is, I'm getting some compiling errors when using Nex AC, I'm assuming it is because there is no support for 0.3DL.

Here's my includes list.
#include <a_samp>
#include <a_mysql>

#include <streamer>
#include <sscanf2>
#include <foreach>
#include <YSI\y_hooks>
#include <evf>

#include <nex-ac>
#include <Pawn.CMD>
#include <easydialog>
#include <kickbanfix>
#include <redis>

D:\SAMP Server Files\pawno\include\nex-ac.inc(3235) : warning 202: number of arguments does not match definition
D:\SAMP Server Files\pawno\include\nex-ac.inc(3235) : warning 202: number of arguments does not match definition
D:\SAMP Server Files\pawno\include\nex-ac.inc(3249) : error 025: function heading differs from prototype
D:\SAMP Server Files\pawno\include\nex-ac.inc(6849) : error 025: function heading differs from prototype

Hope you can help! :)

**Comment by NexiusTailer** [comment]
No, it's not because of that. The problem is in your obsolete includes like a_samp etc, so update your server to the latest version including all default includes.

**Comment by infin1tyy** [comment]
I'm on the latest includes. I update them every SAMP release - however I did follow your advice of updating my includes and I've done so. No difference at all.
Just some extra information if you need it - I'm using Zeex compiler. Not the stock of the 'russian guys' as they call it.

**Comment by infin1tyy** [comment]
It seems like my script doesn't like nex ac, lmao. I tried it with another and it compiles perfectly.
💭 Could be an include it doesn't like? I don't know.

**Comment by NexiusTailer** [comment]
Ahh, then your script uses outdated parameters in some publics. Look for the names of publics on lines the compiler is giving errors in anticheat. Next, find these publics in your gamemode and update their params.
