### ISSUE TITLE
Weapon Pickups

### ISSUE THREAD

**Issue by ronixtey** [NexiusTailer/Nex-AC#95]
Из-за чего может срабатывать 15 и 16 коды при поднятии пикапа оружия?
Если пикап создавался при старте мода, ничего не делает
А если поднять только что созданный пикап, срабатывает

Пикап от Стримера

**Comment by NexiusTailer** [comment]
Может срабатывать в принципе, если отключено учитывание таких пикапов с оружием через
```
#define AC_USE_PICKUP_WEAPONS false
```

Если такого нет, то нужен минимальный код, которым это можно будет воспроизвести на чистом моде.
