### ISSUE TITLE
Adding Min/Max Timespan Definitions to the Anti-Flood Connects.

### ISSUE THREAD

**Issue by Zorono** [NexiusTailer/Nex-AC#97]
Hello dude, so it 'd be great if you added Min/Max timespan definitions(to control the time in ms between every connect and other...) to the Anti-Flood Connects System... smiliar to _Ryder's one(https://forum.sa-mp.com/showthread.php?t=320649).

**Comment by NexiusTailer** [comment]
If you're talking about anti-reconnect, the min time for which a player can reconnect the server can be configured through anticheat define:
```
#define AC_MIN_TIME_RECONNECT			12		//In seconds
```

But if you need a protection against too fast OnPlayerConnect calls (although I don’t understand why it might be needed), then you can configure it natively in the server.cfg file via such variable:
```
minconnectiontime //0 by default
```
