### ISSUE TITLE
VehicleVelocity and NOP's - False Detection bug

### ISSUE THREAD

**Issue by Zorono** [NexiusTailer/Nex-AC#98]
Hello dude, so i am Facing some problems with the `VehicleVelocity`  and NOP's as it detects **anyone** as cheater with the Cheat Type `NOP's` once he connect to the server....
and the `VehicleVelocity` functions is being crazy... it detected me as Cheater with the Cheat Type `Teleport hack (vehicle to player)` when i was using `VehiceVelocity`:
I was running the following code too many times at less than 3 seconds to make a kind of cool boost...
```
					new Float:vx, Float:vy, Float:vz;
					GetVehicleVelocity(GetPlayerVehicleID(playerid), vx, vy, vz);
					SetVehicleVelocity(GetPlayerVehicleID(playerid) ,vx*2,vy*2 ,vz*2);
```

Edit: and i detected me as Cheater with the Cheat Type `Teleport hack (vehicle to player)`  when i jumped from my `Rustler` Vehicle and was Diving with the Parachute...(Just mentioning every little thing happened at that moment if it could help...). and The ` Anti-GodMode from bullets (onfoot)` is not working at least 50% Tested using Hacking Bots... but it connects with `GodMode` and keeps on Playing with **0% Health** -_- (it was working as well as expected before upgrading to 0.3.DL...)

Edit2: and it detected me too as Cheater with the Cheat Type `Teleport hack (in vehicle)` when i was using an Teleport Command(SetPlayerPos)...

Server&Client Version: 0.3.DL-R1

**Comment by NexiusTailer** [comment]
I need anticheat logs for each case of detection and some examples how it can be reproduced (maybe some short videos and the code for the last issues).

**Comment by Zorono** [comment]
https://youtu.be/cgXkBHcXYMg
```
First Shot: Player_Name has been Kicked by Security System [Reason: Teleport hack (in vehicle)]
Second Shot: Player_Name has been Kicked by Security System [Reason: Teleport hack (vehicle to player)]
```
https://youtu.be/VKz4qtIVbY8
```
Player_Name has been Kicked by Security System [Reason: Weapon hack]
This happens only on connection outages...(Timeout)
```
`Teleport hack (in vehicle)`: Teleport Command(SetPlayerPos) - This happens only on connection outages...(Timeout)
`Anti-GodMode from bullets (onfoot)`: Anti-Max Health - This happens only on connection outages...(Timeout)
`Anti-NOP's`: OnConnect Kick - This happens only on connection outages...(Timeout)

Configuration file: https://pastebin.com/xftjdzYG
Customized Configurations:
```
#define AC_MAX_CONNECTS_FROM_IP	2
#define AC_MAX_RCON_LOGIN_ATTEMPT 3
#define AC_DEFAULT_COLOR 0xFF0000AA
#define NO_SUSPICION_LOGS
#define AC_MIN_TIME_RECONNECT 8
```

**Comment by Zorono** [comment]
and it detects me when i was using the following Fly Script(https://forum.sa-mp.com/showthread.php?t=309467) as Cheater with Cheat Type `FlyHack (onfoot)`

**Comment by NexiusTailer** [comment]
> https://youtu.be/cgXkBHcXYMg
> 
> ```
> First Shot: Player_Name has been Kicked by Security System [Reason: Teleport hack (in vehicle)]
> Second Shot: Player_Name has been Kicked by Security System [Reason: Teleport hack (vehicle to player)]
> ```
> https://youtu.be/VKz4qtIVbY8
> 
> ```
> Player_Name has been Kicked by Security System [Reason: Weapon hack]
> This happens only on connection outages...(Timeout)
> ```
> `Teleport hack (in vehicle)`: Teleport Command(SetPlayerPos) - This happens only on connection outages...(Timeout)
> `Anti-GodMode from bullets (onfoot)`: Anti-Max Health - This happens only on connection outages...(Timeout)
> `Anti-NOP's`: OnConnect Kick - This happens only on connection outages...(Timeout)
> 
> Configuration file: https://pastebin.com/xftjdzYG
> Customized Definitions:
> 
> ```
> #define AC_MAX_CONNECTS_FROM_IP	2
> #define AC_MAX_RCON_LOGIN_ATTEMPT 3
> #define AC_DEFAULT_COLOR 0xFF0000AA
> #define NO_SUSPICION_LOGS
> #define AC_MIN_TIME_RECONNECT 8
> ```

All the video link are broken and logs don't contain debug information (#define DEBUG)

> and it detects me when i was using the following Fly Script(https://forum.sa-mp.com/showthread.php?t=309467) as Cheater with Cheat Type `FlyHack (onfoot)`
> https://youtu.be/D4Tx5FudrqA
> 
> ```
> Player_Name has been Kicked by Security System [Reason: FlyHack (onfoot)] 
> This happens only on connection outages...(Timeout)
> ```
> please make a kind of Ping checker inside of other cheating checkers...

Include the anticheat into this filterscript so thus anticheat will have knowledge (by functions hooking) that the fly hack is performing by the server.

**Comment by Zorono** [comment]
I'm so sorry, Video Links are fixed(switched from private to public)...
`Teleport hack (in vehicle)`(VehicleVelocity) - `[Nex-AC debug] Dist: 285.952606, dist set: 436.262084, acSet[8]: -1, speed: 822, veh: 1964`
Runtime error(OnPlayerDeath)
```
[debug] Run time error 4: "Array index out of bounds"
[debug]  Attempted to read/write array element at index 65535 in array of size 1000
[debug] AMX backtrace:
[debug] #0 003c9dd0 in public ac_OnPlayerDeath (playerid=0, killerid=65535, reason=54) at D:\gamemodes\grandlarcy.pwn:****
[debug] #1 00020338 in public OnPlayerDeath (playerid=0, killerid=65535, reason=54) at D:\pawno\include\nex-ac.inc:3465
[debug] #0 003b0d34 in public ac_OnPlayerStateChange (playerid=0, newstate=2, oldstate=1) at D:\gamemodes\grandlarcy.pwn:****
[debug] #1 0003f664 in public OnPlayerStateChange (playerid=0, newstate=2, oldstate=1) at D:\pawno\include\nex-ac.inc:6040
```
`Teleport hack (vehicle to player)`(Jumping from Plane and Parachute Diving) - `[Nex-AC debug] Dist: 15.832823, old pos diff: 2.832569, old pos z: 212.750473, veh: 430, playerid: 0`

**Comment by NexiusTailer** [comment]
> https://youtu.be/cgXkBHcXYMg

Too sharp acceleration here is quite noticeable, as if it was done with speedhack. Maybe you used something else with it?

> https://youtu.be/VKz4qtIVbY8

Why the player spawns twice (again in the sea)? Most likely the glitchy spawn system is the reason for this.

> Runtime error
> 
> ```
> [debug] Run time error 4: "Array index out of bounds"
> [debug]  Attempted to read/write array element at index 65535 in array of size 1000
> [debug] AMX backtrace:
> [debug] #0 003c9dd0 in public ac_OnPlayerDeath (playerid=0, killerid=65535, reason=54) at D:\gamemodes\grandlarcy.pwn:27474
> [debug] #1 00020338 in public OnPlayerDeath (playerid=0, killerid=65535, reason=54) at D:\pawno\include\nex-ac.inc:3465
> .....
> [debug] #0 003b0d34 in public ac_OnPlayerStateChange (playerid=0, newstate=2, oldstate=1) at D:\gamemodes\grandlarcy.pwn:25140
> [debug] #1 0003f664 in public OnPlayerStateChange (playerid=0, newstate=2, oldstate=1) at D:\pawno\include\nex-ac.inc:6040
> ```

It's your crashes in grandlarcy.pwn (see the lines numbers at the end of debug info), not in the ac

> `Teleport hack (vehicle to player)`(Jumping from Plane and Parachute Diving) - `[Nex-AC debug] Dist: 15.832823, old pos diff: 2.832569, old pos z: 212.750473, veh: 430, playerid: 0`

> As for "Teleport hack (vehicle to player)" - anticheat teleports the unoccupied vehicle back to its previous position by default, and the punishment isn't set to kick for this code by default too.

> `FlyHack (onfoot)`(Flying Script) :
> 
> ```
> [Nex-AC debug] Anim: 978, old anim: 978, weaponid: 0, spec act: 0
> [Nex-AC debug] Anim: 959, old anim: 959, weaponid: 0, spec act: 0
> ```

> Include the anticheat into this filterscript so thus anticheat will have knowledge (by functions hooking) that the fly hack is performing by the server.

**Comment by Zorono** [comment]
Okay thanks iam going to do some tests and then send you the results...

**Comment by Zorono** [comment]
Suggestion: *Add an function which gives the ability to GetPlayerInterior(with AC Protection...) `AntiCheatGetPlayerInterior` to be used with Anti-NOP's...
Bug report: *It detects me as cheater with the Cheat type: `Dialog hack` when i tried to select an dialog item from `ls_building1` **filterscript**'s dialog... (i am going to send you some Debug logs soon...)

**Comment by NexiusTailer** [comment]
@Zorono as for dialog hack: you shold include "nex-ac" in each filterscript you have, but only after "#define FILTERSCRIPT" (and if you don't have this define in your fs, then add it at the top of script before everything other).

**Comment by Zorono** [comment]
Hello dude 
* It 'd be great if you added an function which gives the ability to convert from AntiCheatGetSpeed function format to Official PlayerVelocity function's XYZ Coords...

**Comment by NexiusTailer** [comment]
This API is not designed to expand your capabilities in scripting in general, it is only for better interaction with anticheat and its data (so this is just an opportunity to get its inside information from the ac and nothing more). That is why I wouldn't want to add some extra variables to the anticheat in player statistics only in order to use them in external functions without using in any way in the anticheat inside.

**Comment by Zorono** [comment]
please can you give me a example on setting player Velocity using `SetPlayerVelocity` and `AntiCheatGetSpeed`

**Comment by NexiusTailer** [comment]
You can declare your custom function to set speed according to the same formula as in the ac:
```
SetPlayerSpeed(playerid, speed)
{
	if(speed < 1) speed = 1;
	new Float:vX, Float:vY, Float:vZ;
	if(GetPlayerVelocity(playerid, vX, vY, vZ))
	{
		new cur_speed = floatround(VectorSize(vX, vY, 0.0) * 179.28625);
		if(cur_speed <= 0)
		{
			new Float:angle;
			GetPlayerFacingAngle(playerid, angle);
			new Float:newVelX = floatcos((angle -= 270.0), degrees) * speed / 179.28625;
			SetPlayerVelocity(playerid, newVelX, floattan(angle, degrees) * newVelX, 0.0);
		}
		else
		{
			new Float:vMultiplier = float(speed) / float(cur_speed);
			SetPlayerVelocity(playerid, vX * vMultiplier, vY * vMultiplier, vZ * vMultiplier);
		}
		return 1;
	}
	return 0;
}
```
And use it like:
```
SetPlayerSpeed(playerid, AntiCheatGetSpeed(playerid));
```

**Comment by Zorono** [comment]
Thanks alot @NexiusTailer for that awesome help and example :100: :1st_place_medal:

**Comment by Zorono** [comment]
Hello dude, it detects me as Cheater with cheat type `Dialog hack` when i was using the following custom dialog script... https://forum.sa-mp.com/showthread.php?t=570213
```
[Nex-AC debug] AC dialog: -1, dialogid: 2, listitem: 12, playerid: 0
```

**Comment by NexiusTailer** [comment]
Try to include nex-ac before PreviewModelDialog.inc
