### ISSUE TITLE
SpawnPlayer false cheat detection

### ISSUE THREAD

**Issue by MarkTimber** [NexiusTailer/Nex-AC#99]
I'm using SpawnPlayer function after login/register systems, and sometimes anticheat detects teleportation/pickup teleportation hacks when SpawnPlayer is used. Then my skin is set to ID 0 (CJ) insead of one which is saved in my database. 

`[Nex-AC debug] Dist: 1226.964965, dist set: 25000.000000, speed: 0, old pos x, y, z: 0.000000, 0.000000, 0.000000
[23:20:29] [Nex-AC] Įtartina žaidėjo veikla kurio ID: 0. Priežasties kodas: 002 (2)
[23:20:29] [Nex-AC debug] Dist: 1224.430908, dist set: 1224.430908, acSet[8]: -1, speed: 0, old pos x, y: 0.000000, 0.000000
[23:20:29] [Nex-AC] Įtartina žaidėjo veikla kurio ID: 0. Priežasties kodas: 002 (6)`

**Comment by NexiusTailer** [comment]
Is there some code to reproduce this case?

**Comment by MarkTimber** [comment]
After successful login:
`SetSpawnInfo(playerid, NO_TEAM, 0, pInfo[playerid][pPosX], pInfo[playerid][pPosY], pInfo[playerid][pPosZ], pInfo[playerid][pPosA], 0, 0, 0, 0, 0, 0); // Player position variables
SpawnPlayer(playerid);`
OnPlayerSpawn:
`GivePlayerMoney(playerid, pInfo[playerid][pMoney]); // Player money variable
SetPlayerSkin(playerid, pInfo[playerid][pSkin]); // Player skin variable`
For now I have disabled on-foot teleport and teleport pickup anticheats for certain player as soon as player connects to the server. I have commented ignition of these anticheats under `OnPlayerSpawn`, but as soon as I uncomment them, problem appears again. With these two functions disabled everything seems working fine. (I have been working for few hours now, and I was connecting to the server like hundred times. Everythings looks good). Also I have commented DEBUG in nex-ac.inc, so it wouldn't spam my console. I think that's all.

**Comment by NexiusTailer** [comment]
So, the problem is that you use SetSpawnInfo function before calling OnPlayerRequestClass, so its anticheat data is overwritten in this public.

Try to use SetSpawnInfo in OnPlayerRequestClass or OnPlayerRequestSpawn since they are called after your login system, but before the actual spawn.

**Comment by MarkTimber** [comment]
I've created a 100ms timer after successful login, and put there SetSpawnInfo and SpawnPlayer. Everything works perfectly now, but I really don't like this idea, there should be more optimised way of doing that.

**Comment by MarkTimber** [comment]
I found the solution. I just put my mysql account check query into OnPlayerRequestClass, and now LoadPlayerAccount callbacks for sure will be loaded atfer that one. Unfortunately this method adds few more seconds of waiting, before login dialog will apprear, since difference in time between OnPlayerConnect and OnPlayerRequestClass is about 3seconds (I have readed about it somewhere recently). Besides that I have found the solution, I still would like to see the fix in next version of nex-ac, and I really would like to put my query in OnPlayerConnect back. Thanks for help, you are amazing, keep going, peace!

**Comment by NexiusTailer** [comment]
All your actions (the dialogs with login and so on) are called from OnPlayerConnect, which means they are called before OnPlayerRequestSpawn. Thus, the script first calls SetSpawnInfo function from the anticheat, in which it sets right coordinates for spawn, and only then they are overwritten in the OnPlayerRequestClass with coordinates that are set for the current class. So, unfortunately, I can’t track in anticheat exactly which coordinates should be used for spawning if you call SetSpawnInfo before OnPlayerRequestClass (except for the fact that they are overwritten by default, that is logical, based on its call sequence).

Try to duplicate your SetSpawnInfo function directly into OnPlayerRequestClass in case if it's called after the player connects.

**Comment by MarkTimber** [comment]
I did as you said, and it seems working fine. Thanks alot for solution!
